perma-id/w3id.org

rd-fairness-tests/.htaccess
Hello,
We updated URLs for the RD tests.
Regards,
Rajaram.
=> Update RD tests

dosdp/.htaccess, dosdp/README.md
@dosumis a lightweight purl system for sharings specs, docs etc around dosdp
=> Adding Dead Simple Ontology Design Patterns

oerbase/.htaccess, oerbase/README.md
Creation of new namespace for the oerBASE github organisation meant to be used by Austrian higher education Open Educational Resources community
=> create directory oerbase for austrian higher education OER community

nfdi4ing/metadata4ing/.htaccess
Add versioning redirects to metadata4ing
=> Add versioning redirects to metadata4ing

nfdi4ing/metadata4ing/.htaccess
@dgarijo sorry for the "spam" of three PRs within two days. We are in the final publishing steps 😛
=> Improve redirects to enable proper Protégé imports

dpv/.htaccess, dpv/README.md
W3C Data Privacy Vocabularies and Controls CG (DPVCG) outputs ; redirected to https://w3c.github.io/dpv/
=> add /dpv entry

brainteaser/.htaccess
Created two new RewriteRules in the .htaccess file concerning URLs of entities belonging to the two namespaces in the ontology: schema elements (ontology/schema) and named individuals (ontology/named-individual).
=> added two new rewrite rules in .htaccess

seo/.htaccess
change default response to HTML page
=> change default response of seo ontology

smarcql/.htaccess, smarcql/README.md
Thanks for the quick and useful suggestions! I think I took all the advice. A stub version of smarcql.ttl file should be present so that should help confirm the intended behavior.
=> Revised pull request for new smarcql ID

smarcql/.htaccess, smarcql/README.md
The smarcql.ttl file isn't published yet, but will be soon.
=> Add entry for smarcql ontology.

TTRpg/.htaccess, TTRpg/README.md
An ontology that describes the general structure and workings of a tabletop role playing game.
=> TTRpg ontology

DigiTwin/.htaccess, DigiTwin/README.md
Gives initial attempt of redirecting to ontology used in collaboration between DigiTwin and IOTICS.  Attempted to follow examples from other folders, but let me know if it needs to be adjusted.
=> Adding DigiTwin

globalise/.htaccess, globalise/README.md
Dear w3id.org-maintainers,
Could you please review this pull request? Please note: the ontology that this identifier points to is still under construction and the domain where it will be hosted cannot be accessed yet.
Thanks,
Lodewijk
=> Pull request for new identifier

fair-enough/.htaccess
Edit the redirect URL in the `.htaccess` file for the `fair-enough` namespace
=> Edit redirect URL for the fair-enough namespace

sqo/.htaccess, sqo/readme.md
We have created an ontology for the creation of scientific questions. The README is very basic, let me know any required changes.
=> Add Scientific questions ontology

EMAI/.htaccess, EMAI/README.md
I would like to add a perma-id for /EMAI.
=> Adding EMAI

SocDOnt/.htaccess, SocDOnt/README.md
Hello everyone.
Please add the SocDOnt (Social Document Ontology) of CEIR (Center for Enterprise Information Research) to perma-id.
If changes are required please let me know.
Best
Muffexx
=> Add SocDOnt - Social Document Ontology

peripleo/.htaccess, peripleo/README.md
Just an initial commit for now to get things up and running. Thanks again.
=> Create Peripleo namespace

tern/.htaccess
Contact information: https://github.com/perma-id/w3id.org/tree/master/tern
=> /tern - Add profile resources. Change some redirects.

tern/.htaccess
Contact information: https://github.com/perma-id/w3id.org/tree/master/tern
=> /tern Add redirect for TERN Ontology cookbook

terror/.htaccess, terror/README.md
=> added terror

terror/.htaccess, terror/README.md
=> Updated link

osdu/.htaccess, osdu/README.md, osdu/htaccess.txt
Please add OSDU ontology to your repo. This is for registering a unique namespace with the prefix osdu.
=> Add OSDU Ontology 

CovidO/.htaccess, CovidO/README.md
=> Add CovidO

sepses/README.md, teamingai/.htaccess, teamingai/README.md
We add an identifier for TEAMING AI project, 
resources website: https://teamingai.wu.ac.at/
official website: https://www.teamingai-project.eu/
=> teamingai pull request

dpv/.htaccess, dpv/README.md
Provides content negotiation for rdf, ttl, n3, jsonld for:
DPV serialisations: dpv, dpv-skos, dpv-owl
DPV extensions: dpv-gdpr, dpv-pd, dpv-tech, dpv-geo
Apologies for the repeated commits
=> dpv: add all paths explicitly

a2a-fair-metrics/.htaccess
Not good PID design but these are for testing.
=> Require / at end of a2a-fair-metrics PIDs

mobility/.htaccess, mobility/osdm/core/.htaccess, mobility/trias/common/.htaccess, mobility/trias/fares/.htaccess, mobility/trias/journey/.htaccess, mobility/trias/location/.htaccess, mobility/trias/mode/.htaccess, mobility/trias/trips/.htaccess, mobility/trias/utility/.htaccess
=> Added Trias

lsq/.htaccess, lsq/README.md
Hi w3id community,
Request according to title. Web page: http://lsq.aksw.org/
Cheers,
Claus
=> Request to add an /lsq/ entry for the Linked Sparql Queries project

idnau/.htaccess, idnau/README.md
A Draft PR for the IDN team to review before putting to w3id maintainers for review.
=> IDN README & stub redirect

TRO/.htaccess, TRO/README.md
A redirection for [Transparent Relations Ontology](https://github.com/mikel-egana-aranguren/Transparent-Relations-Ontology) (TRO). Thanks!
=> Redirection for Transparent Relations Ontology

traceability/.htaccess
This change is to support report generation for trace interop tests
=> Update trace redirects

dpv/.htaccess, dpv/README.md
suffix geo -> changed to legal in config paths
=> dpv: Update path/IRIs

rd-fairness-tests/.htaccess
Hello,
We added new API service to the rd-fairness-tests prefix.
Thank you,
Regards,
Rajaram.
=> New RD test service added

iSeeOnto/.htaccess
Hello,
This is an update for the iSeeOnto project, adding some additional ontology files along with HTML documentation.
Thanks
=> iSeeOnto adding additional ontology files and docs

asdkg/.htaccess, asdkg/README.md
We need to publish the dataset
=> Permanent Identifiers for the Web

vehicle/.htaccess, vehicle/README.md
I would like to add my GitHub.io as a source for vehicle and type approval ontology. Ontology is still dutch.
=> vehicle ontology and type approval

asdkb/.htaccess, asdkb/README.md, asdkg/.htaccess
=> change name

locolligo/.htaccess
Thanks again.
For the record, this change should implement, for example:
`https://w3id.org/locolligo/viaeregiae/iiif/2/saxton%2FHampshire.png/3329,3222,120,120/full/0/default.png`
=>
`https://viaeregiae.org:8183/iiif/2/saxton%2FHampshire.png/3329,3222,120,120/full/0/default.png`
=> Add Viae Regiae IIIF

nmdc/.htaccess, nmdc/README.md
We collaborate with the people who own the w3id `gensc` and `linkml` namespaces
=> creating initial redirect for nmdc (National Microbiome Data Collaborative)

asbingowl/core/.htaccess, asbingowl/keys/.htaccess, asbingowl/keys/2013/.htaccess, asbingowl/readme.md
updated all htaccess files  and readme
Contact: annegoebels95@gmail.com
=> asbingowl update 

profile/.htaccess
updated the handling server for /profile/
=> /profile/ server updated

DnD5eCharacter/.htaccess, DnD5eCharacter/README.md
This ontology is an extension to the [TTRpg](https://w3id.org/TTRpg) ontology. It describes every aspect required to create and describe a character in the game Dungeons & Dragons (5th edition).
All concepts described in this ontology are freely available, none of the purchasable extensions to the game are included here.
This ontology has been created in the context of a master thesis at Ghent University (Belgium).
=> Create DnD5eCharacter ontology

noria/.htaccess
In relation to https://github.com/perma-id/w3id.org/pull/2679
=> noria: correcting target URLs

kim/.htaccess, kim/README.md
Hello,
we added a RewriteRule for a repository containing a controlled vocabulary.
=> add RewriteRule for educationalLevel

sds/.htaccess, sds/README.md
A specification to describe data lineage between Linked Data Event Streams and intermediary processors that introduces a couple of new terms
=> Smart Data Specification added

DigiTwin/.htaccess, DigiTwin/README.md
Changes redirection from HTML version to GitHub .ttl version
=> DigiTwin Updated URI

cpont/.htaccess, cpont/README.md
Requesting addition of /cpont/ namespace, adding initial README.md and .htaccess files.
=> Adding /cpont/ namespace

kg-construct/.htaccess, kg-construct/README.MD
Add w3id for the survey website.
CC: @dachafra @andimou @pheyvaer
=> kg-construct: add survey website

ColActDOnt/.htaccess, ColActDOnt/README.md
Hello everyone.
Please add the ColActDOnt (Collaborative Actions on Documents Ontology) of CEIR (Center for Enterprise Information Research) to perma-id. The publication in our repo follows within the next few weeks.
If changes are required please let me know.
Best
Muffexx
=> Add ColActDOnt - Collaborative Actions on Documents Ontology

ride2rail/README.md, ride2rail/agreements/.htaccess
=> Update ride2rail .htaccess

tao/.htaccess, tao/README.md
First version of .htaccess and README.md for Tourism Analytics Ontology
=> Add .htaccess and README.md for Tourism Analytics Ontology

meta-share/omtd-share/.htaccess
=> Omtd-share update rules

c-path/.htaccess, c-path/README.md
Requesting addition of /c-path/ namespace, adding initial README.md and .htaccess files.
=> Adding /c-path/ namespace

ammo/.htaccess, ammo/ont/.htaccess, ammo/readme.md, ammo/shapes/shacl/.htaccess
Pull request to create namespace for the Additive Manufacturing for Maintenance Operations Ontology project developed at the University of Notre Dame.
=> Adding repository for AMMO

metadocencia/.htaccess
Previous link wasn't the right one.
=> Update correct link to Slack

solid/.htaccess, solid/README.md
Request to add `/solid/` namespace for the [Solid project](https://solidproject.org/).
=> Add /solid/ namespace

akflora/.htaccess, akflora/README.md
Please see `README.md` for more details. 
Thanks for the great `w3id.org` service!
=> Created /akflora/ - for Alaska plant informatics

security/.htaccess
=> define paths to MerkleProof2019, ChainedProof2021

OntoGraphDB/.htaccess, OntoGraphDB/README.md
Maintainer github ids https://github.com/fenixdreamer
=> add maintainer 

isample/vocabulary/material/.htaccess, isample/vocabulary/material/0.9/README.md, isample/vocabulary/sampledfeature/.htaccess, isample/vocabulary/sampledfeature/README.md, isample/vocabulary/specimentype/.htaccess, isample/vocabulary/specimentype/README.md
that endpoint handles content negotiation.
=> isample :   change resolver to http://cor.esipfed.org/ont/api/v0/ont

FTP/Colour/.htaccess
- Entry for the ongoing work regarding a "Fashion Trend Prediction" (FTP) project.
- Initial aspect: *Colour*
=> Fashion Trend Prediction / Colour aspect: entry for GitHub repo

exdoc/.htaccess
sorry for again requesting changes here, edited wrong redirect urls due to error with search and replace in the urls...
=> [exdoc] Update .htaccess

exasure/.htaccess, exasure/readme.md, medtag/.htaccess, medtag/readme.md, sketup/.htaccess, sketup/readme.md, sketx/.htaccess, sketx/readme.md
Added new entries for the ExaMode H2020 European project
=> Added new entries for the ExaMode H2020 European project

traceability/.htaccess
Please merge AFTER https://github.com/w3c-ccg/traceability-interop/pull/326
=> chore: change default target for traceability/interoperability

software-iodata/.htaccess, software-iodata/readme.md
As proposed at https://github.com/SoftwareUnderstanding/software-iodata/issues/1
=> Added software IO data repository

sqo/.htaccess
Updating links to the web-page and ontologies
=> Update semantic question ontology links from v1.0.0 to v1.1.0

FAIR_eva/.htaccess, FAIR_eva/README.md
Vocabulary defining RDA FAIR maturity indicators and its implementation on the tool
=> FAIR EVA Vocabulary

shack/.htaccess, shack/README.md
Please create a `shack` namespace in w3id. See committed README.md. Thanks!
=> initial shack namespace commit

jp-textbook/.htaccess
Add additional identifiers for learning materials in jp-textbook dataset.
=> Add settings for learning unit identifiers in jp-textbook

fides/README.md, hpont/README.md, react/README.md, var/README.md, wfont/README.md
Change maintainer of ontologies
=> Change maintainer of ontologies

ejp-rd/.htaccess
Hello,
I updated some of the EJPRD project application address.
Thanks for the help,
Regards,
Rajaram.
=> EJPRD applications are updated

tern/.htaccess
Contact information: https://github.com/perma-id/w3id.org/tree/master/tern
=> /tern Update redirect

frost/.htaccess, frost/readme.md
Added a new entry for an ontology and subsequent resources
=> updated frost ontology and readme

kim/.htaccess
Renamed a repository and need the change to be reflected here.
Thank you and have a nice weekend!
=> change `schulformen` to `schularten`

uco/.htaccess, uco/README.md
This PR reserves UCO namespace for https://unifiedcyberontology.org/
=> feat(entry): add uco namespace

steel/ProcessOntology/.htaccess, steel/ProcessOntology/README.md
The steel namespace will be split up into different working groups. The processing of steels is the topic of the current working group.
=> Add Namespace ProcessOntology to Steel

unterrichtsvideos.net/.htaccess, unterrichtsvideos.net/README.md
=> add vocab-redirects

research-technology-readiness-levels/.htaccess
minor update to resolve badges (svg/png) via w3id to github
=> update research-technology-readiness-levels: resolve badges

ern-euro-nmd-fdp/.htaccess, ern-euro-nmd-fdp/README.md
=> Update for w3id.org/ern-euro-nmd-fdp

rebase/.htaccess, rebase/README.md
=> fix: fixes #2945

semapv/.htaccess
Adding redirect for vocabulary sub namespace
=> Update .htaccess (semapv)

semapv/.htaccess
=> Fix error in semapv redirect

semapv/.htaccess
I am trying to model the solution after https://httpd.apache.org/docs/2.2/rewrite/flags.html#flag_ne
cc @dgarijo
=> Hopefully last attempt to fix semapv redirect

security/.htaccess
Redirect to new W3C VCWG Security Vocabulary.
=> Redirect to new security vocabulary.

ro/wfrun/.htaccess, ro/wfrun/README.md
Note, 0.1 is not yet live, see https://www.researchobject.org/workflow-run-crate/profiles/0.1-DRAFT/process_run_crate etc.
=> wfrun PIDs for Workflow Run Crate profils

Mach30/.htaccess, Mach30/README.md
=> add Mach30 w3id

pvont/.htaccess, pvont/README.md
Intended for redirection to an ontology file
=> Redirection for research ontology

nfdi4cat/.htaccess, nfdi4cat/README.md
Create identifier for nfdi4cat
=> Add nfdi4cat w3id

ro/wfrun/.htaccess
Removes the trailing slashes from the redirect URLs
=> Fix Workflow Run RO-Crate profile URLs

BridgeMaintenance/.htaccess, BridgeMaintenance/README.md
I'd like to add the persistent URIs to the ontology.
=> persistent URIs for the BMO

gaia-x/.htaccess, gaia-x/README.md
redirect to the official source of reference for gaia-x schema
=> update redirection for gaia-x schema

ontoeng/.htaccess
Revised and simplified because not working as expected with SPARQL update (LOAD). Modeled after https://github.com/perma-id/w3id.org/blob/master/daselab/onto/.htaccess
=> ontoeng - updated .htaccess

coypu/.htaccess, coypu/README.md, coypu/coy_wikidata/.htaccess, coypu/coy_wikidata/README.md, coypu/em-dat/.htaccess, coypu/em-dat/README.md, coypu/global/.htaccess, coypu/global/README.md, coypu/gta/.htaccess, coypu/gta/README.md, coypu/ta/.htaccess, coypu/ta/README.md, coypu/world-port-index/.htaccess, coypu/world-port-index/README.md
CoyPu project (https://coypu.org/) ontology adding.
=> CoyPu redirect rules

age/.htaccess
This PR updates the location of the Age vocabulary and the Level of Assurance 2 vocabulary and context.
=> Add Age Level of Assurance 2 Vocabulary and Context.

semsys/.htaccess
semsys.tuwien.ac.at --> semantic-systems.org
=> update website uri

ecad/.htaccess, ecad/README.md
Hello,
This is PR to add ECAD into the list. We are creating ontologies to use in commercial software and would like to take benefit of a permanent ID and redirect service.
Thank you
Cordially,
Imran KHAN
=> PR to add ECAD

interont/.htaccess, interont/README.md
The interactions ontology enables researchers to explore semantic modeling of both agent-to-agent and agent-to-artifact interactions in multi-agent systems. The ontology is largely based on the state of the art in coordination protocols (e.g. BSPL and Mandrake).
Thank you!
=> Link to interactions ontology

ADHD-KG/.htaccess, ADHD-KG/README.md
Adding redirect from https://w3id.org/ADHD-KG to https://emmanuelpapadakis.github.io/ADHD-KG/
=> Add ADHD-KG redirect

culco/.htaccess, culco/README.md
Linked data namespace /culco for the Cultural AI project, see https://www.cultural-ai.nl/projects/aicult-culturally-aware-ai for details
=> Added /culco namespace for contentious issues in linked data project

sumo/kb/.htaccess
This PR updates sudo/kb rewrite rule
=> chore(sumo-kb): updated rewrite rule

combining-linking-techniques/.htaccess, combining-linking-techniques/README.md
Request to add a w3id.org entry for the Combining Linking Techniques research project. (Thank you!) 
It is a project relating to the domain of entity linking and how to combine in effective ways different approaches in order to improve various aspects of the annotation pipeline.
=> Requesting to add a w3id.org entry for "Combining Linking Techniques"

ro/wfrun/.htaccess
Allows redirection of URLs like https://w3id.org/ro/wfrun/workflow/0.1-DRAFT
=> Workflow Run RO-Crate: allow arbitrary version tag

FAIRVASC/readme.md, fairvasc-fdp/.htaccess, fairvasc-fdp/readme.md
I am a new maintainer of the ontology so I added myself as a new maintainer.
=> added a new maintainer

icon/README.md
Adding Sofia Baroncini (SofiBar in GitHub) as an administrator for this namespace.
=> Adding a new administrator for the icon project

obpa/.htaccess, obpa/readme.md
We have developed a new ontology for building authorities.
=> obpa first instance

kim/.htaccess
Added a RewriteRule to point to https://skohub.io/dini-ag-kim/schulabschluesse/heads/main/w3id.org/kim/schulabschluesse/index.de.html
=> add Rewrite Rule for "schulabschluesse"

wdio/.htaccess, wdio/readme.md
Hello, 
would you like to include my ontology to your repository, thank you. 
Best regards, Christian
=> Adapted changes

lmodel/.htaccess
This PR redirects schema and artifact requests to github
It leverages mod_rewrite variables https://httpd.apache.org/docs/2.4/rewrite/advanced.html#setenvvars
=> feat(lmodel): add schemas and artifacts

fdo/.htaccess, fdo/Readme.md, fdof/.htaccess, fdof/Readme.md
Added prefixes for the FAIR Digital Object Framework and the FAIR Digital Objects.
=> Added fdo and fdof prefixes

cramp-fdp/.htaccess, cramp-fdp/README.md
Hi Daniel!  Hope this looks good to you!
=> for the CRAMP fair data point

fdof/.htaccess
Updated rules for the examples for the FOIS 2023 paper on FDOF-CM
=> Updated rules

imkg/.htaccess
Updated IMKG htaccess with metadata
=> Updated IMKG htaccess with metadata

ldasw/.htaccess, ldasw/README.md
Created a new identifier ldasw. This identifier will be used for my University of Twente course ontology tests.
=> Created ldasw repository

ldasw/.htaccess, ldasw/README.md
- Fixed ontology url
- Fixed README text formats.
=> Updated ontology url

epsilonitalia/.htaccess, epsilonitalia/README.md
=> epsilonitalia

var/.htaccess
The links to access the docs and .xml for the var ontology have been corrected.
=> Links corrected for var ontology

inrupt/.htaccess
Update rewrite rule to redirect to a 'namespace' subdomain of the main Inrupt domain.
=> update rewrite rule to use namespace now

ontouml-catalog/.htaccess, ontouml-catalog/README.md
Creation of permanent identifiers for the OntoUML/UFO Catalog. Matching rules tested with success.
=> Redirection rules for the OntoUML/UFO Catalog

CEON/.htaccess, CEON/readme.md
Redirect the catalogue page to a Github repo at this moment.
=> Update CEON catalogue redirect

ontouml-models/.htaccess
include new 3rd level redirection rule
=> include new rule

inrupt/.htaccess
Temporarily redirect the QA manifest to GitHub pages.
=> Add rewrite rule for QA manifest

kim/.htaccess
I added a rewrite rule for another vocabulary.
=> add eaf-sachgebietssystematik rule

ontouml-models/.htaccess
I am facing a problem with the redirection to a folder containing a space. This is a new attempt to make it work.
=> fix rule attempt

demo-resources/.htaccess, demo-resources/README.md
Correct some errors in the previous ones, and add a new URI for demo-classifications
=> demo-resources: modify previous ones and add a new URI for demo-classifications

demo-resources/.htaccess, demo-resources/README.md
Hopefully this version will work.
=> Correct some errors

LPT/.htaccess, LPT/readme.md
=> First commit

fst/README.md, fst/resource/.htaccess
Hello,
I want to create a namespace for the Chair of Fluid Systems of the Technical University of Darmstadt.
I also have some questions left:
1. Are the README and the .htaccess, I created, appropriate? I tested it on a local apache webserver (httpd) docker container and it works. But I can't tell whether I made mistakes, that didn't have shown up yet.
2. The content negotiation is still work in progress. Is it okay if I leave the code in the .htaccess file or should I remove it and add it back in when I'm 100% happy with it?
3. Your small "Creating a New Identifier"-Guide mentions that users should squash their commits. In GitLab it is usually possible to do this while merging a Pull-/Merge-Request. Is it still necessary for me to do it or will the administrators of this service do it …
=> Create /fst/ namespace + small example

airo/.htaccess, airo/README.md
As w3id urls are case-sensitive, I have created this request for https://w3id.org/airo. 
https://w3id.org/AIRO will be redirected to this new url.
=> Creating airo 

lomap/.htaccess, lomap/README.md
Visit app description in https://arquisoft.github.io/course2223/labAssignmentDescription.html
This application is developed in the practical part of the [Software Architecture course](https://arquisoft.github.io/). 
This course is part of the [Software Engineering degree](http://ingenieriainformatica.uniovi.es/web/ingenieriainformatica/infoacademica/grado) at the [School of Computer Science Engineering](http://ingenieriainformatica.uniovi.es/).
=> Lomap. Application for accademic purpose. 

esw/.htaccess, esw/readme.md
=> Add folder for ESW

arkid/.htaccess, arkid/README.md
Support for Archival Resource Key (ARK) identifiers
=> Support for Archival Resource Key (ARK) identifiers

cmip6dr/.htaccess, cmip6dr/README.md
Adding in a new link to https://192.171.169.110/
=> Adding new link to alternative web application

tsso/.htaccess, tsso/README.md
The resulting ontology serves as the basis to represent technical standards in a machine readable way. It provides elements to define publications, their provisions, their dependencies and possible constraints, among other constructs. This ontology is based on three technical standars, namely the IEC 62443 4-2, ETSI 303645 and the more general NIST Framework for Improving Critical Infrastructure Cybersecurity.
=> TSSO: Technical Security Standard Ontology

tsso/.htaccess, tsso/README.md
Make suggested correction to README file.
=> TSSO: Correct Typo and Indenation in Readme

GerPS-Ontology/.htaccess, GerPS-Ontology/README.md
We need a permanent Identifier for our `GerPS-Ontology`. If something went wrong please contact us! Our Contacts are in the `README.md` File under the headline: `Contact`.
=> GerPS-Ontology was added

sssom/.htaccess
Adding another mapping commons
=> Update .htaccess for sssom

GVTPDOnto/.htaccess, GVTPDOnto/README.md
Dear Author,
I have created a new ontology and I wanted to publish it online using a permanent id. Thus I forked your repository (w3id.org) and created my folder in the GitHub repository (OntoDoc /GVTPDOnto). I need a permanent URI , I added files (.htaccess, README) in the subdirectory (GVTPDOnto).
Please let me know if you approve that and what will be the following steps.
best...
=> permanent URI 

demo-resources/.htaccess, demo-resources/README.md
Adding RewriteRules for dummy-assets, and to the default landing pages
=> Adding RewriteRules for dummy-assets etc

rml/.htaccess
One IRI was missing from #3320
=> rml: add missing RML-star shape IRI

saqi/.htaccess, saqi/README.md
Added Social Air Quality Index Ontology (SAQI)
Redirectting to - https://kracr.iiitd.edu.in/ontology/saqi/
With additional redirection rules to serve serialization formats - 
ttl - https://kracr.iiitd.edu.in/ontology/saqi/saqi.ttl
xml/rdf - https://kracr.iiitd.edu.in/ontology/saqi/saqi.xml
ld-json - https://kracr.iiitd.edu.in/ontology/saqi/saqi.json
=> added saqi w3id

asdkb/.htaccess
I want to change link data. Thank you
=> change links

polifonia/.htaccess
Updating non-working redirects, caused by broken links.
=> Updated broken redirects

italia/lombardia/data/.htaccess
We have updated a small fix to address for redirect.
Regards
Enrico
=> Url fix for redirect

geochem/1.0/.htaccess
the rewrite rule has an httpURI in the query value and the target server requires these to be URL encode, but when the rewrite happens, all the #n encodings in the URI are ignored.  Try fix based on github  #2846.  
see also #2853 
will this work?
=> try to solve urlencoding problem

trusted-wfrun-crate/.htaccess, trusted-wfrun-crate/README.md
Note that [0.3-DRAFT](https://trefx.uk/trusted-wfrun-crate/0.3-DRAFT/) is about to be released as `0.3`.
=> Adding trusted-wfrun-crate

ixo/.htaccess, ixo/readme.md
I'm part of the ixo org on github that created the ixo namespace, as can see here: https://github.com/orgs/ixofoundation/people.
=> ixo: update readme and .htaccess

rml/.htaccess
Add some more FNML resources which where missing. valueMap is removed as it is replaced by inputValueMap.
=> rml: add more FNML resources

geochem/1.0/.htaccess
don't include bogus AIRO changes in my new local checkout. I sync'd my fork with master,  but get message ' Failed to load latest commit information.' Is the repo getting too big to work?
=> remove AllowEncodedSlashes

geochem/1.0/.htaccess
missed this detail in @nicholascar suggestion...
=> put quotes around the rewrite strings with the NE flag.

geochem/1.0/.htaccess
I think its set for special case with the geochem technique URIs?  rewrites work in testing...
=> get rid of URL encoding, ARDC RVA made fix on their side 

encode/.htaccess, encode/readme.md
Dear all, the application has moved server and domain as it will be maintained by the same person at a different institution. Thanks a lot!
=> changing host for application

ga4gh/README.md
As noted in #3361 the readme for GA4GH needed to be updated with contact details. Have expanded as per w3id.org's example readme for `ddgs`. Temporarily included myself and GA4GH's CSO as primary contacts. Will expand with other contacts in due course.
=> Update README.md for GA4GH

ppon/dpp/.htaccess, ppon/dpp/README.md
New ontologyadded with .htaccess file and readme
=> Created new ontology in /ppon/

APD/.htaccess, APD/README.md, APD/glossary/.htaccess, APD/ontology/.htaccess, APD/traits/.htaccess
This PR requests a URI namespace for the AusTraits Plant Dictionary (APD) under the w3id interface
=> Add APD redirect

per/.htaccess, per/README.md, periscope/.htaccess, periscope/README.md, periscope/atlas/.htaccess, periscope/ontology/.htaccess, periscope/web/.htaccess
I have changed the configuration of the directories and modified the .htaccess
=> File configuration updated

geochem/1.0/.htaccess
fix the base URL again... starting to figure out how they work!
=> yet another try at rewrite for RVA, with updated methods vocab

EXTVARTRANS/.htaccess, EXTVARTRANS/README.md
Two new files:
/EXTVARTRANS/.htaccess
/EXTVARTRANS/README.md
=> Adding a permanent identifier for EXTVARTRANS

APD/.htaccess, APD/glossary/.htaccess, APD/release/.htaccess, APD/traits/.htaccess
This PR modifies the redirect for APD
- change subfolder ontology -> release
- enable anchors within APD/traits and APD/glossary
- add nq
- change n3 -> nt
- remove xml
Thanks for reviewing and all your work with w3id.org
=> Modify APD redirect

EUTaxO/.htaccess, EUTaxO/README.md
This PR splits a existing ontology into 4 more manageable ones
=> Split EUTaxO ontology

noria/.htaccess, noria/README.md
Relates to https://github.com/Orange-OpenSource/noria-ontology/pull/2
=> Update .htaccess and README.md for NORIA-O v0.3 compatibility

rml/.htaccess
Some redirections used the wrong URL.
=> rml: fix redirections for RML CC

demato/.htaccess, demato/README.md
Creating persistent uri for the ontology developed by our lab
=> PURL for DeMato Ontology 

demato/.htaccess, demato/README.md
Redirected  the link of the main page to the person who is gonna administer the repo in the future.
=> Updated the github.io page link and contact details 

demo-resources/.htaccess, demo-resources/README.md
We have now finalized the site where the w3id-URIs should be dereferenced to. Update therefore the ReWrite-rules to reflect the final URLs.
=> Update to the final/ultimate URLs

ontouml/.htaccess, ontouml/Readme.md
URL updated after the project's GitHub repository name change.
=> update readme and htaccess

semanticarts/.htaccess, semanticarts/README.md
We have decided to change our namespace convention. This update is to address that change.
=> Update to match new gist namespace

vc/.htaccess
- Add maintainers to /vc/ id.
- Add VC redir to spec.
=> Add Verifiable Credentials rules and details.

mosaic/.htaccess, mosaic/README.md
=> Addition of the mosaic namespace for the mosaic ontology

odi/.htaccess, odi/README.md, odi/desktop.ini
A .htaccess file has been created along with a description in the README.md
=> Creation of a new permament URI for ODI resource

HIMIKO/.htaccess, HIMIKO/README.md
=> feat: add HIMIKO

semanticarts/.htaccess
Another change  in our namespace redirect rule.
=> Update namespace redirect

303/.htaccess
sorry, should have checked the syntax before
=> fixing directoryslash

situannotate/.htaccess, situannotate/README.md
add namespace for SituAnnotate: Annotation Situation ontology
=> add situAnnotate namespace

iqb/README.md
A new member of our organization will make some changes to our redirect rules.
=> Add new maintainer

odissei/ns/dsv-ontology/.htaccess
New ID for the dataset-variable ontology file
=> created new file for the dataset-variable ontology

dsv-ontology/.htaccess
I have changed the url in the .htaccess file
=> changed landing page

polifonia/.htaccess
Improves the music meta record in `polifonia` to avoid another redirect from GitHub.
=> update musicmeta record

OntoExhibit/.htaccess, OntoExhibit/README.md
We created an organization github account specifically for this project and have uploaded the ontology to a repository of this account. Links updated.
=> Updating links to ontology

elementary/.htaccess, elementary/README.md
This redirect is for a research ontology called Elementary.
=> Added redirect for elementary

catenax/.htaccess, catenax/README.md
Debug markdown
Improve forwarding rules
=> bugfix/KA-371 

elementary/.htaccess
My apologies, I did not upfront add accept types for the responses.
=> added accept types

elementary/.htaccess
A minor change in the URL. Thank you!
=> Redirecting root to html instead of owl

mt-metadata/.htaccess, mt-metadata/README.md
Establishing a new W3ID persistent URI namespace for the mt-metadata standard.
=> Add mt-metadata

catenax/.htaccess
These rules add another type of ontology documents to the catenax namespace.
=> feat:KA-327 introduce use case folder/redirections

DCRI-ont-spe/.htaccess, DCRI-ont-spe/readme.md, DCRI-ont/.htaccess, DCRI-ont/readme.md, DCRI-voc/.htaccess, DCRI-voc/readme.md
includes DCRI ontology, vocabulary and special
=> Adding DCRI ontology

nfdi4cat/.htaccess, nfdi4cat/voc4cat/.htaccess, nfdi4cat/voc4cat/README.md
Also improved clarity of readme.
=> nfdi4cat: Reorder & extend redirects for voc4cat

pmd/.htaccess, pmd/README.md
approved by @joergwa (see https://github.com/materialdigital/w3id/pull/1 )
=> add pmd subpath for glass-ontology

esim/README.md
I removed the "is" as suggested in #3547
=> Made correction in README as suggested by @TallTed

coscine/.htaccess, coscine/README.md
Please add a w3id for the research platform Coscine LDP endpoint and static RDF graphs. 
@LukasCBossert: It would be nice if you could give a short acknowledgement that you are ok to be a maintainer for this w3id.
=> w3Id for Coscine

sqo/.htaccess
We are updating some outdated links, now links point to the latest version.
=> Updating links for SQO

mtbls-ejprd/.htaccess, mtbls-ejprd/README.md
Raising this pull request in the hope of securing a unique identifier for [MetaboLight](https://www.ebi.ac.uk/metabolights/)'s bespoke  [Fair Data Point](https://www.fairdatapoint.org/).
=> Merge mtbls-ejprd changes

ecfo/.htaccess, sqo/.htaccess
=> small changes to ecfo and sqo

sssom/.htaccess
(sorry for keeping this in draft mode for so long, needed to get some permissions for this)
=> Add fall-thru rule to SSSOM

security/.htaccess
This PR updates the data-integrity security URL redirects to match the latest values that are changing in the spec.
=> Update data-integrity security URL redirects.

stav/.htaccess, stav/README.md
I would like to request for a permanent ID "stav" on w3id.org.
Details are below. Thank you.
STAV: System Trustworthiness and Accountability Vocabulary
Accompanied repo at https://github.com/bact/stav
Contact:
Arthit Suriyawongkul
ADAPT Centre, Trinity College Dublin
arthit.suriyawongkul@adaptcentre.ie
=> stav: Initial commit

a2a-fair-metrics/.htaccess
FDO-like in order to achieve RDA-F1-01M and RDA-F1-01D
=> a2a PIDs for metadata and files

ro/crate/.htaccess
https://w3id.org/ro/crate/0.2/context
redirected to
https://www.researchobject.org/ro-crate/https://www.researchobject.org/ro-crate/0.2/context.json/context.jsonld
=> Add [L]ast flag so we dont double-rewrite

rml/.htaccess
Management only when already inside rml folder.
=> rml: fix subdirectory

lodedo/.htaccess, lodedo/README.md
Added readme and htaccess file as per the recommendation
=> Adding the lodedo permanent URI

rml/.htaccess
Allow content negotiation for full spec and fix for resources
=> rml: add content negotiation for full spec

lodedo/.htaccess
Fix of destination URL error to met the target web-app requirements  . Changes are related to "Redirect to visualisations" section in htaccess file
=> Destination URL fix

ro/doi/.htaccess
* https://w3id.org/ro/doi/10.5281/zenodo.7782262  
--> https://s11.no/2023/phd/evaluating-fdo/PR-RequirementSpec-3.0/  
(for https://doi.org/10.5281/zenodo.7782262)
* https://w3id.org/ro/doi/10.5281/zenodo.7781926  
--> https://s11.no/2023/phd/evaluating-fdo/PR-RequirementSpec-2.1/  
(for https://doi.org/10.5281/zenodo.7781926)
=> RO-Crates for FDO specs

rml/.htaccess
Tested now with a local setup instead of a htaccess tester.
=> rml: fix redirections again

catenax/.htaccess, catenax/README.md
This PR improves the catenax namespace forwarding rules following the release process of the semantic models behind.
=> Introduce versioned access, introduce taxonomy subspace, forward to namespace site presentation.

CHFDM/.htaccess, CHFDM/README.md
please add this w3id to the main repository
=> redirection for CHFDM ontology

foodpairing_inspire_kg/.htaccess, foodpairing_inspire_kg/readme.md
Added the Foodpairing Inspire KG, which is a KG that contains 102 food ingredients, a 4-layer taxonomy of 150 ingredient categories, sensory information for the ingredients (aromas, tastes, textures, trigeminals), functional benefits of ingredients, and ingredient pairings.
=> Added the Foodpairing Inspire KG

citizenship/.htaccess
Preemptively adding v2 context redirect.
=> Add citizenship v2 redirect.

everycred/.htaccess, everycred/README.md
Added EveryCRED W3C Permanented identifier!
**What is EveryCRED ?**
EVERYCRED is an exceptionally adaptable platform for the issuance, viewing, and verification of credentials. Notably, this platform is structured around the fundamental concepts of DID (Decentralized Identifiers) and W3C Verifiable Credentials, embracing cutting-edge technology.
**Rewrite URL -**
-  https://www.everycred.com/  ->  https://w3id.org/everycred
- https://www.everycred.com/schema/v1/context.json -> https://w3id.org/everycred/v1
**Contact Email -**
admin@everycred.com
gourav.patidar@viitor.cloud
=> EveryCRED: Added everycred W3C permanent identifier

FAIR_Training_LDP/.htaccess
=> move to CBGP on port 80 because the stupid eduroam blocks non-standard ports

mixs/.htaccess
Account for changes to the mixs repo's directory structure
=> Update mixs .htaccess

inrupt/README.md
Just some minor wording and formatting tweaks to the registration README.
=> tweaks to wording of README

ioc/.htaccess
Internet of Construction project (ioc) ontology, was made aware that some redirects do not work as intended.
=> .htaccess adapted - should now also work for oops! pitfall-scanner

vc/confidence-method/.htaccess
Adding confidence method spec being incubated at CCG.
=> Add CCG confidence method spec.

nen2660/.htaccess, nen2660/README.md, nta8035/.htaccess
@redmer . I merged the previous three. Can you approve this?
=> BIMLoket is renamed to NL-DigiGo. Corresponding repo links are adjusted

chalkgrp/.htaccess, chalkgrp/README.md
Create initial redirections for the Chalk Research Group resources.
=> Chalk Research Group namespace creation

CMECS/.htaccess
Updated Rewrite Rule to resolve redirects to IRIs
=> Updated Rewrite Rule 

CMECS/.htaccess
=> Update .htaccess (#2)

demo-resources/.htaccess
=> Add redirect rules for demo data quality assessments

shp/.htaccess, shp/readme.md
added version support  + linked to different repository
=> updates to .htaccess

stap/.htaccess, stap/README.md
=> Add stap namespace

ontofnct/.htaccess, ontofnct/README.md
Add /ontofnct comprising README.md and .htaccess file
=> Add new entry for the FNCT ontology (ontofnct)

italia/work-accident/controlled-vocabulary/.htaccess, italia/work-accident/data/.htaccess, italia/work-accident/onto/.htaccess
Update work-accident Onto and Vocabularies URI of INAIL (the National Institute for Insurance against Accidents at Work)
=> Update work-accident Onto and Vocabularies URI

ontobio/.htaccess, ontobio/README.md
Ontobio is a Biographical Ontology
=> Add ontobio

italia/work-accident/controlled-vocabulary/.htaccess
Update rewrite rules and conditions inside the .htaccess
=> Update .htaccess inside controlled-vocabularies  of Work Accident

salmon/.htaccess, salmon/README.md, salmon/SynSim/.htaccess, salmon/SynSim/README.md, salmon/TinyButMighty/.htaccess, salmon/TinyButMighty/README.md
* SynSim algorithm.
* TinyButMighty dataset.
=> SALMON: entry for project studies

salmon/README.md
GitHub ID: https://github.com/salmon-kg/SALMON
=> Update main README: add SALMON GitHub

pygraft/.htaccess, pygraft/README.md
GitHub Repo: https://github.com/nicolas-hbt/pygraft/tree/master
=> Create an Entry for PyGraft

polifonia/.htaccess
Fixed the bug (typo) for an ontology of the Polifonia Ontology Network (Meetups)
=> Fix bug redirect meetups ontology

polifonia/.htaccess
add redirect rules for Meetups KG
=> Update .htaccess adding redirect rules for Meetups Knowledge Graph

polymat/.htaccess, polymat/ReadMe.md
this creates the namespace for the PolyMat ontology
this is an ontology in the space of polymer membrane research. we currently have TTL and OWL serializations. more may follow at some point.
=> add polymat namespace

polymat/.htaccess
Sorry, there was mistake made in the content negotiation rules. 
this commit should fix those. (at least it does so in my local tests)
=> polymat: fix content negotiation

ro/README.md
=> ro: update contact details in README.md

okp4/README.md, okp4/ontology/.htaccess
Implement URL redirection for the [OKP4 protocol's ontology](https://github.com/okp4/ontology).
Thanks :heart:
=> Add OKP4 protocol Ontology permanent links

ifcc/.htaccess, ifcc/README.md
Files for the IUPAC FAIR Chemistry Cookbook (IFCC) namespace
=> Adding the IFCC namespace

hto/.htaccess, hto/README.md
New entry files for the [Heritage Text Ontology](https://github.com/frances-ai/HeritageTextOntology) namespace. Thanks!
=> Adding the hto namespace

iaam/i40fd/.htaccess, iaam/i40fd/README.md
This redirect allows access to the Industry 4.0 Field Device Ontology (i40fd) which is a research project under development by the Institute of Applied Automation and Mechatronics at the University of Applied Sciences Aachen in Germany.
=> Added iaam/i40fd namespace

pmd/co/.htaccess, pmd/glass-ontology/.htaccess, pmd/ont_pub_tmplt/.htaccess, pmd/pgo/.htaccess, pmd/tto/.htaccess
Hi,
unfortunately my test setup was not perfect and another edit is needed to get the wanted functionality.
@joergwa could you please approve this change?
Thanks,
Matthias
=> Update for pmd: Fix error due to change in directory structure

italia/social-security/README.md, italia/social-security/controlled-vocabulary/.htaccess, italia/social-security/data/.htaccess, italia/social-security/onto/.htaccess
Add social-security to w3id.org/italia for redirecting to ontologies and open data of INPS (National Institute for Social Security)
=> Add social-security to w3id.org/italia

isample/opencontext/specimentype/.htaccess, isample/opencontext/specimentype/0.1/.htaccess, isample/vocabulary/material/0.9/README.md, isample/vocabulary/material/1.0/.htaccess, isample/vocabulary/material/1.0/README.md, isample/vocabulary/material/README.md, isample/vocabulary/sampledfeature/.htaccess, isample/vocabulary/sampledfeature/0.9/.htaccess, isample/vocabulary/sampledfeature/0.9/README.md, isample/vocabulary/sampledfeature/1.0/.htaccess, isample/vocabulary/sampledfeature/1.0/README.md, isample/vocabulary/specimentype/0.9/.htaccess, isample/vocabulary/specimentype/README.md
not sure why redirects for vocabulary/sampledfeature are returning 'Internal Server Error'. Make content in that .htaccess identical to others that work
=> update readmes and comments, try to fix Sampledfeature redirects

pkg/.htaccess, pkg/README.md
Redirects for PKG (Personal knowledge graphs) vocabulary resources.
=> Init /pkg/

zbmed-semtec/.htaccess, zbmed-semtec/README.md, zbmed-semtec/projects/.htaccess, zbmed-semtec/projects/README.md, zbmed-semtec/theses/.htaccess, zbmed-semtec/theses/README.md
We are adding redirections for projects and theses carried out in the ZB MED SemTec team, including corresponding metadata in JSON-LD.
=> Add redirections for ZB MED SemTec team

zbmed-semtec/.htaccess, zbmed-semtec/projects/.htaccess, zbmed-semtec/theses/.htaccess
* Fix bug with / at the end
* Add redirection to json file for ending /jsonld
* Add redirection to ro-crate json file for ending /ro-crate
=> Update zbmed-semtec redirections

italia/republic-history/.htaccess, italia/republic-history/README.md, italia/republic-history/onto/.htaccess
Please include this new bunch of negotiations pertaining to The "Portal of Sources for the History of the Italian Republic" project.
=> adding italia/republic-history/

ldac/.htaccess, ldac/README.md
Request to add a new ldac namespace
=> Add ldac redirection

vep-ejprd/.htaccess, vep-ejprd/README.md
Fixes: https://github.com/perma-id/w3id.org/pull/3834
Tested
=> Fix issues in vep-ejprd-vp

mlso/.htaccess
Addition of SKOS taxonomies redirects
=> Redirects update

ODE_AM/AMAO/.htaccess, ODE_AM/CEMAO/.htaccess, ODE_AM/MAO/.htaccess, ODE_AM/PBFAO/.htaccess, ODE_AM/README.md, ODE_AM/WAAMAO/.htaccess
Add New Namespaces for MaterialDigital initiative ODE_AM
=> Add ODE_AM Namespace

arp/.htaccess, arp/README.md
This W3ID provides a persistent URI namespace for the Hungarian national repository service "Adatrepozitórium Platform" ([ARP](https://science-research-data.hu/en)).
=> Add /arp namespace for use by the ARP project

ifcc/.htaccess
=> IFCC: updated one ID, added 13 more

str/.htaccess, str/README.md
Dear team,
thank you for adding persistent towards https://semiceu.github.io/STR-AP
=> adding redirection for str

arp/.htaccess, arp/README.md
Also use more consistent naming for env vars.
=> Fix /arp/schema redirects

pmd/README.md, pmd/mo/.htaccess
Microscopy Ontology (MO) was added and README was adjusted, accordingly.
=> Added microscopy ontology (MO)

ldac/.htaccess
Fix the destination to point at raw json file.
=> LDAC: Fix /context destination

ioc/README.md
Hi David,
I fixed my git in the readme. Thanks for pointing it out.
Greetings,
Lukas
=> git handle fixed

pmd/README.md, pmd/materials-mechanics-ontology/.htaccess
Adding htaccess file with redirects for a new application ontology (materials-mechanics-ontology) under pmd space.
=> Adding pmd/materials-mechanics-ontology space

reloc/.htaccess, reloc/README.md
added reloc folder with htaccess and readme file
=> add reloc folder

ic/standards/.htaccess
Update a bunch of links to fix sharepoint.
=> Update for Sharepoint re-org/new specifications

strenda/.htaccess, strenda/README.md
Hi there,
we would like to create this new namespace.
Thanks so much in advance! Best,
Robert
=> creates the STRENDA namespace

traits.build/.htaccess, traits.build/README.md, traits.build/release/.htaccess
Hi, This PR creates a namespace for traits.build data model under the w3id interface. 
Thanks for your work on w3id.org!
=> Create traits.build namespace

README.md, index.html
* Update w3id.org index.html to match the latest content in README.md
* Also fixes minor numbering and reference in README.md (these were not cause any issue previously in terms of functionality/appearance, only Markdown markup inconsistencies)
This will fix #3736
=> root: Update w3id.org/index.html to match latest README.md

podio/.htaccess
Redirection to specific version
=> Podio ontology specific version redirect

polyneme/.htaccess, polyneme/README.md
=> add polyneme namespace

.gitignore, ifcc/.htaccess
=> add id from pugview recipe

zeri/.htaccess, zeri/README.md
This space will host the ontologies developed by the Zeri Foundation (University of Bologna) (see Readme)
=> Add space "zeri"

ad4gd/.htaccess
Add AD4GD rules for sensors -> hosted RAINBOW instance
@rapw3k, as the `ad4gd` maintainer, are you ok with this?
=> [AD4GD] Rules for sensors

evo/.htaccess, evo/README.md
The EVO ontology aims to enhance reusability and interoperability, fostering seamless information, integration and collaboration across various EV-related applications and systems.
=> EVO (E-Vehicle Ontology)

gaia-x/.htaccess
Remove redundant root folder name
=> fix: fix redirection rules for Gaia-x

BCI-ontology/.htaccess
=> BCI-Ontology: update .htaccess

gdmt/.htaccess, gdmt/README.md
Please can you review and approve this PR?
=> Initial set up of gdmt id with README and htaccess

ldsw/.htaccess, ldsw/README.md
Workspace contains .htaccess and README.md
=> Added "ldsw" folder for ontology testing

CA-ODE4HERA/BiblioOnto/.htaccess, CA-ODE4HERA/BiblioOnto/README.md
Updated URL of ontology and source repository
=> Clean Aviation ODE4HERA project (2024-2026): updated URL

kim/.htaccess
Added a Rewrite Rule for a new repository.
=> add kompendium

hacid/.htaccess, hacid/README.md, hacid/onto/.htaccess
See `README.md` for additional details
=> Rules for ontologies and LOD of the HACID project

phydit/.htaccess
My apologies - I did not check the URLs and it had a typo. Thank you!
=> Corrected the url

hsu-aut/cask/.htaccess, hsu-aut/caskman/.htaccess, hsu-aut/css/.htaccess
updates GitHub URLs after moving repositories
=> [hsu-aut] updates GitHub URLs after moving repos

MoRe-SFB1475/README.md
Fix typo in heading and add a second person responsible for the redirects.
=> update README of MoRe-SFB1475

README.md
per @scor, "Thanks for letting me know. You can simply remove the reference since I'm no longer involved." fixes #3705
=> remove OpenSpring from participants list

termcat-ld/.htaccess, termcat-ld/README.md
Termcat-ld is a terminological graph converted from terminologia oberta resources.
=> ADD PERMALINK FOR TERMCAT LD

ifcc/.htaccess
Add ID for new cookbook recipe.
=> add id for iupac units in excel

moont/.htaccess
Changes in my respository structure made an adjustment of the corresponding redirect necessary
=> MoOnt: adjust redirect

aimaix/.htaccess, aimaix/README.md, aix/.htaccess, aix/README.md
two closely connected new ontologies (AixLib (aix) and Alignment of AixLib to IFC (AIMAix))
=> Add rules for aix and aimaix

bs/.htaccess, bs/README.md, libeas/.htaccess, libeas/README.md, mbl/.htaccess, mbl/README.md, msl/.htaccess, msl/README.md
4 closely interconnected ontologies representing Modelica Libraries
=> Add rules for modelica libs

ic/standards/.htaccess
Updates for new values URLs and some cleanup.
=> Updates for new values

chemrof/.htaccess
See https://github.com/chemkg/chemrof/issues/10
=> Update .htaccess, change master to main for chemrof

podio/.htaccess
- Rewrite rules have been modfied to allow any version redirect as suggested by @dgarijo 
- New redirect rule added to /demo
- Improved comments
=> Rewrite to handle multiple versions and demo rule 

neural-electronic-interface-ontology/.htaccess, neural-electronic-interface-ontology/README.md
Add redirect for the Neural Electronic Interface Ontology.
=> Add Neural Electronic Interface Ontology

neural-electronic-interface-ontology/.htaccess
Let me try to get the redirect to the owl and/or obo files working.
=> Update neio .htaccess

emmo/.htaccess, emmo/README.md
Added redirection rules for application ontologies. They should be treated similar to domain ontologies.
=> Added redirection rules for application ontologies

np/l/.htaccess
Sorry for bothering you again, Daniel. No hurry for this one. And thanks a million for your terrific work in keeping the w3id service up!! :)
=> Add flags to rules in /np/l/

tree/.htaccess
=> Corrected redirection target in the TREE namespace

dpv/.htaccess
- /owl does not work
- /dpv-owl does not redirect
- /dpv-gdpr does not redirect
- /dpv-pd does not redirect
- /legal/eu/gdpr redirects to eu-gdpr instead of just gdpr
To debug, see https://harshp.com/dpv-x/status-check
=> /dpv fix broken w3ids in #3958

arto/.htaccess, arto/README.md
ARTO spec and related documentation.
=> Artwork Object Ontology (ARTO) entry

isample/biology/biosampledfeature/1.0/README.md, isample/opencontext/specimentype/0.1/README.md, isample/opencontext/specimentype/README.md, isample/vocabulary/material/README.md, isample/vocabulary/materialsampleobjecttype/.htaccess, isample/vocabulary/materialsampleobjecttype/1.0/.htaccess, isample/vocabulary/materialsampleobjecttype/1.0/README.md, isample/vocabulary/materialsampleobjecttype/README.md, isample/vocabulary/specimentype/.htaccess, isample/vocabulary/specimentype/1.0/.htaccess, isample/vocabulary/specimentype/1.0/README.md
update for material sample object type vocabulary supersedes specimen type vocab.   Clean up readme files
=> updates for new material sample object type vocab

isample/vocabulary/material/.htaccess, isample/vocabulary/materialsampleobjecttype/.htaccess, isample/vocabulary/materialsampleobjecttype/1.0/.htaccess
didn't get it right first time...
=> fixes in redirects for new vocab

isample/vocabulary/materialsampleobjecttype/1.0/.htaccess, isample/vocabulary/specimentype/1.0/.htaccess
=> forgot the '%' before the variables

gptto/.htaccess
The IRIs for entities in the ontology did not resolve to the appropriate ontology file.
=> Fix redirects for gptto

comein/.htaccess
Add redirect for resources to current repository
=> add resource redirect

iqb/.htaccess
Please, add two new rules. Thank you in advance.
=> Add studies and staff

radx/.htaccess, radx/README.md
Initial set up of namespace for RADx project.
=> create namespace for RADx

iqb/.htaccess
Sorry. I want to delete the unnecessary rules that I added last pull request. Thank you in advance
=> Delete rules for studies and staff

jicamarca/.htaccess, jicamarca/README.md
Redirection for datasets of the Jicamarca data repository
=> New redirect for Jicamarca data repository

polymat/.htaccess, polymat/ReadMe.md
we changed the tool for ontology documentation, so the forwardings need to be adapted as well.
thanks for merging.
=> polymat: change forwardings & update contacts

ldac/.htaccess
Add new redirect /pilars under /ldac/
=> /ldac/ Add redirect for pilars

ekdd/.htaccess, ekdd/README.md
Ontology & Knowledge Graph of The National Center for Public Administration (EKDDA)
=> Knowledge Graph of The National Center for Public Administration (EKDDA)

italia/public-policies-analysis/controlled-vocabulary/.htaccess
Update rewrite rules for public policies analysis.
=> Update rewrite rules for public policies analysis

kgcp/KGQP/.htaccess
=> Adding KGQP

axone/README.md, axone/ontology/.htaccess
Implement URL redirection for the [Axone](https://axone.xyz) protocol's [ontology](https://github.com/axone-protocol/ontology).
(This has been extensively tested using materials provided in PR #4121).
Thanks ❤️
=> Add entry for Axone protocol

tekniker/.htaccess, tekniker/readme.md
This pull request is to create PURLs to enable linked data descriptions of resources from [TEKNIKER ](https://www.tekniker.es/en) equipment. 
The desired functionality of the redirect rules has been tested and confirmed using [madewithlove](https://htaccess.madewithlove.com/).
=> Create PURLs for TEKNIKER linked data

big-map/.htaccess, big-map/readme.md
This pull request updates the rules in the .htaccess file to support more general re-directs between URIs and documentation html pages. 
The desired behaviour has been tested and verified through [madewithlove](https://htaccess.madewithlove.com/).
=> Update big-map .htaccess rules

ARK/.htaccess, ARK/readme.md
This pull request removed old contacts from ARK folder and added new ontology links to READM.md and .htaccess.
=> Updated ARK folder

fom/.htaccess, fom/readme.md
This repository contains the .htaccess file to set up Persistent Uniform Resource Locators (PURLs) for linked data resources related to **[FOM](https://www.fomtechnologies.com/)** equipment.
This work is initialized as part of the BATMACHINE Innovation Action in Horizon Europe
- Project Title: BATMACHINE Boosting Europe’s sustainable battery cell industrial manufacturing value chain by developing an optimised machinery with intelligent control processes to minimise costs, scrap and energy consumption
- Grant Agreement No.: 101104246
- Website: [BATMACHINE](http://batmachineproject.eu/)
The .htaccess file provided in this repository is intended to be used with the w3id.org Persistent URL (PURL) service. It redirects requests made to specific paths within the FOM Application Ontology to …
=> FOM Resource PURLs

ssv/.htaccess, ssv/README.md
This PR adds the ssv/ namespace for data related to [Signature Sound Vienna](https://iwk.mdw.ac.at/signature-sound-vienna), a digital musicology project investigating the Vienna Philharmonic Orchestra's New Year's Concert series, funded by the Austrian Science Fund [FWF P 34664-G](https://doi.org/10.55776/P34664).
More information may be found in the following publications:
[Weigl et al., 2022](https://doi.org/10.1145/3543882.3543892) and [Weigl et al., 2023](https://doi.org/10.1145/3625135.3625144).
=> Add ssv/ namespace (Signature Sound Vienna)

ssv/.htaccess
As per https://github.com/perma-id/w3id.org/pull/4154 (thx @dgarijo)
=> ssv/ (Signature Sound Vienna): fix RewriteRules in .htaccess

omega-x/.htaccess
Fix an issue following wrong rule ordering. 
Best regards,
=> Omega-X, re-order redircetion rules.

clarin_el_dictionary/.htaccess
Update redirections to remve 9090 port from the URIs
=> Clarin:EL vocabulary remove 9090 port in URIs

openbadges/.htaccess, openbadges/README.md
This updates:
- Contact information
- Redirection to Open Badges v2.0 JSON-LD context file
=> Updates to openbadges

omega-x/.htaccess
Switch turtle display to raw format
Best regards,
=> Switch turtle display to raw format

opentecr/.htaccess
adds the TECRDB resource within the opentecr namespace
Thanks for your work! :)
=> opentecr: adds a resource

fep/.htaccess
Update the .htaccess to support JSON-LD, RDF/XML, and Turtle term definitions.
=> FEP: support term definitions as ontology/schema

ColActDOnt/.htaccess, SocDOnt/.htaccess
=> Fix typos in .haccess of ColActDOnt and SocDOnt

cnr-ispc/.htaccess
Add rewrite rule for html lode documentation of the ontology
=> html rewrite in .htaccess

aerOS/README.md, aerOS/building/.htaccess, aerOS/continuum/.htaccess
More info: https://aeros-project.eu
=> Add aerOS project

citizenship/.htaccess, utopia/.htaccess
- Main files in /utopia/.
- Alt URL in /citizenship/.
=> Add utopia redirects.

elementary/.htaccess, elementary/README.md
I am consolidating the repositories in a more consistent manner, therefore changing the redirections. Thank you!
=> Realigned elementary to github.io repository

vdl/.htaccess
Adds a redirect to version 2 of the VDL context file.
=> Add VDL version 2 context file redirect

iadopt/.htaccess, iadopt/ont/.htaccess
we intend to change the structure of our github pages, so we need to adjust the forwardings here as well
=> iadopt: update rules for changed folder structure

age/.htaccess, age/README.md, cit/.htaccess, cit/README.md
- Remove unneeded `index.html` from URLs.
- Use `age-vocab` page for both `age` contexts.
- Improve READMEs.
- Fix `age` vocab link.
- Add myself as a contact.
=> Update `age` and `cit`.

indonesia-history/.htaccess, indonesia-history/README.md
[indonesia-history] 
Create indonesia-history directory.
create .htaccess file
create README.md file
=> Request new identifier (indonesia-history)

scs/.htaccess
Update tested .htaccess file using rewrite rules
=> Update SCS redirect rules

gaia-x/.htaccess
=> Fix Gaia-X LinkML Redirects

cit/.htaccess
Use vocab repo context instead of npm/js context package.
=> Update cit link.

ro/wfrun/.htaccess, ro/wfrun/process/.htaccess, ro/wfrun/provenance/.htaccess, ro/wfrun/workflow/.htaccess
=> Latest version PIDs for ro/workflow-run profiles

orka/.htaccess, orka/README.md
I would like to have a permanent link for my Ontology for Robotic Knowledge Acquisition (ORKA).
Let me know if I need to do anything else.
Thank you very much!
=> added ORKA

salmon/LLM-SPARQL/.htaccess, salmon/LLM-SPARQL/README.md
Adding the LLM-SPARQL entry project.
=> LLM-SPARQL entry

sri/.htaccess
Extend rewriting for /sri namespace:
Extend the rewriting for `doc` and `git` by also forwarding arbitrary URI postfixes.
=> feat(sri): forward also with arbitrary postfix

opentecr/.htaccess
Thanks in advance! Great and important work! :)
=> opentecr - Update link

ekdd/.htaccess, ekdd/README.md
=> URI for EKDD retracted

FATO/.htaccess, FATO/README.md
=> FATO update

np/.htaccess
Sorry for the follow-up pull request. This was difficult to test locally.
=> Correct reference to custom HTTP header in /np

mlao/.htaccess, mlao/README.md
Creating a new identifier for Multi-Level Annotation Ontology (MLAO) and add redirection for MLAO ontology.
=> add redirection for mlao ontology

udo/.htaccess, udo/readme.md
The identifier for the udo ontology has been added.
=> Added udo identifier

vc-barcodes/.htaccess
Adds a redirect for the v1 context file for vc-barcodes.
=> Add vc-barcodes v1 context redirect.

dfc/.htaccess, dfc/README.md
Initial set up of redirects for datafoodconsoritum.org ontology & taxonomy.
=> Initial Data Food Consoritium setup of folder (dfc/), readme & .htaccess

utopia/.htaccess
Use generic pattern for versioned context rules.
=> Improve utopia rules.

dfc/.htaccess, dfc/README.md
* Fix to DFC .htacccess file.
* Fixes to README.md & .htaccess
* Adjusted .htaccess sequencing
=> DFC - Fix typo in ontology redirect (#1)

vpa/.htaccess, vpa/README.md
Added a redirection for the Verified Permissions and Authorization Ontology (VPA)
=> added redirection for vpa ontology

reseo/README.md
Update contact points and add new maintainers so they can make further changes in the future if required.
=> Update reseo ontology with new maintainers

DATA-FW/.htaccess, DATA-FW/README.md
Creation of a permanent identifier for the DATA-FW ontology.
=> DATA-FW Ontology

dfc/.htaccess
* DFC - removed subdirectory from redirects.
=> DFC - Removed subdirectory (#2)

dmpqv/.htaccess, dmpqv/README.md
This is for my master thesis "Automated Quality Indicators for Machine-actionable Data Management Plans" at TU Wien. My supervisor asked me to provide a w3id. Thank You!
=> Create rules for DMP Quality Vocabulary

enershare/.htaccess, enershare/README.md
Dear W3id Team,
Could you please, merge the pull request to have access to the ENERSHARE project.
Thank you for your help,
Best regards,
Lynda TEMAL
=> enershare project 

micoll-map/.htaccess, micoll-map/readme.md
Add w3id for the public and open-source project: MICOLL Map - a web based application to enable historical routes consultation.
=> Add w3id for the public and open-source project: MICOLL Map

pmd/demodata/tensiletest_42CrMoS4/.htaccess
Hi,
this fixes an error I had in the last commit for [pmd/demodata/tensiletest_42CrMoS4](https://github.com/MattTJung/w3id.org/tree/master/pmd/demodata/tensiletest_42CrMoS4). @MarkusSchilling @BerndBayerlein could one of you please approve this.
BR
Matthias
=> fix htaccess for pmd demodata tensiletest_42CrMoS4

pmd/demodata/tensiletest_42CrMoS4/.htaccess
Hi,
I found another typo, sorry for the inconvenience. @MarkusSchilling @BerndBayerlein please approve.
See you,
Matthias
=> Fixed a typo in .htaccess

ga4gh/.htaccess
Closes ga4gh/tasc#50. Reviewed and approved by @andrewyatz in ga4gh/w3id.org#3.
=> revise GKS links

rdf-connect/.htaccess, rdf-connect/README
Rules for the permanent identifier https://w3id.org/rdf-connect
=> Add rdf-connect namespace

UniverseTBD/PathFinder/.htaccess, UniverseTBD/PathFinder/README.md, UniverseTBD/PathFinder/codebase/.htaccess, UniverseTBD/PathFinder/dataset/.htaccess
IDs for the PathFinder artefacts: app, dataset, and codebase.
=> UniverseTBD > PathFinder

people/johannesschrott/.htaccess, people/johannesschrott/README.md
I added an redirection to the software CobADQ that I created as part of my thesis.
=> Added redirection to a software contributed by me

iberz/.htaccess
fixed the rules to reflect the knowledge graph's structure
=> fixed .htaccess to direct to webpages

malke/.htaccess, malke/README.md
A PR to add an identifier for my project on Ethiopic *malkəʾ* poetry.
=> Add "malke" identifier

matolab/openbis/.htaccess
=> fix matolab/openbis redirect

lara/.htaccess, lara/README.md, oso/.htaccess, oso/README.md
Please add lara w3id
LARA (Laboratory Automation Robotic Assistent) is an open source Research Data Management Suite and 2nd generation Electronic Lab Notebook with the goal to automate most of the data and metadata entering process by providing a rich infrastructure for lab communication, orchestration, data/metadata storage, evaluation and exchange. It utilises Ontology based semantic web technology to make data findable via SPARAQL.
Thanks :)
=> Add lara  w3id

ERKNet/fdp/.htaccess, ERKNet/fdp/README.md
=> Creating New Identifier for ERKNet FDP

APTO/.htaccess, APTO/README.md, AlmesCore/.htaccess, AlmesCore/README.md, AlmesCore/json/.htaccess
New request of identifier for the Agriculture Product Types Ontology (APTO).
=> Identifier for the Agriculture Product Types Ontology (APTO)

auscope-geochemistry-network/.htaccess
=> ht.access update

gaia-x/README.md
- Add a few useful links
- Update contact list
=> docs(gaia-x): update README

dfgfo/.htaccess, dfgfo/README.md
Hi, this is our first draft for an ontology identifier. It's WIP - we will still update some targets and probably come back for further edits. Thanks for merging and all the best, Susanne
=> Add identifier dfgfo (WIP)

aio/README.md
=> Update README.md for AIO to reflect renaming the github org

aio/.htaccess
This change sets up individual PURLs for both classes and individual owl products. cc @realmarcin @turbomam
=> Update .htaccess for AIO

CEIR/.htaccess
The list of codes will be added to the new repo within the next days. :)
=> Add CWC (Collaborative Work Codes) to CEIR

elementary/.htaccess
Addition URL to redirect to example domain ontology for HVAC.
=> added redirect to hvac vocabulary

evdoxus/.htaccess, evdoxus/README.md
Ontology moved to another server
=> Moved to a new location

people/johannesschrott/.htaccess
Fixed the redirection to the CobADQ software
=> Fixed redirection

ic/standards/.htaccess
=> Update for new policy references

lobid/.htaccess, lobid/README.md
* Adjust redirects for LBZ vocabularies
* Add README for lobid
ref https://github.com/hbz/lbz-vocabs/issues/2
=> Update lobid redirects

tav/.htaccess, tav/README.md
Hi,
I have to tried to create a redirection to TAV, which can be viewed here:
https://github.com/arzoo-ebbs/tav
Hope-- I have done everything correctly!
=> TAV Update

resiliont/.htaccess
=> Update .htacess for resiliont 

sml/.htaccess
4 extra `RewriteRule` for part 2 of the standard. 
Fixed 404 error.
=> Added seperate ruleset for sml2 files

rio/.htaccess, rio/README.md
This pull-requests provides redirects for the [Risk Identification Ontology](https://github.com/Onto-Med/RIO).
=> Add RIO config

hefquin/.htaccess, hefquin/readme.md
Provide redirects for the HeFQUIN project github, vocabularies, and project page.
=> add HeFQUIN redirects

ro/wftest/.htaccess, ro/wftest/README.md
Adds redirects for the [Workflow Testing RO-Crate profile](https://crs4.github.io/workflow-testing-ro-crate/).
=> Add redirects for Workflow Testing RO-Crate

doves/.htaccess, doves/README.md
Please could you review and accept the creation of a new identifier that relates to the DOVeS ontology?  Many thanks, Matthew.
=> Creation of doves identifier

ldac/.htaccess
Moved the PILARS repo on github pages
=> Update .htaccess cos I moved a website

pmd/co/.htaccess
added support for redirecting different versions
=> Update pmd co .htaccess; added support for versioning

pko/.htaccess, pko/README.md
Add an entry for the Procedural Knowledge Ontology (PKO). Currently redirecting to the Github repository.
=> Add entry for Procedural Knowledge Ontology (PKO)

etap/.htaccess, etap/README.md
Added first PR for ETAP ontology redirect.
=> Added ETAP ontology

ro/doi/.htaccess
https://by-covid.github.io/baseline-use-case-comparative-analysis/
=> Permalink for BY-COVID RO-Crate

GayLesbianBisexualTVCharacters/README.md, Greens/README.md
See the original closed PR [here](https://github.com/perma-id/w3id.org/pull/4423). Update was to add contact information in .htaccess files to README files in ./GayLesbianBisexualTVCharacters and ./Greens.
=> Updating README.md in both directories per @dgarijo's comment in pull request 4423

inrupt/README.md
Pat is no longer administering the persistent resources.
=> Switch Inrupt administrator to be David Bowen

ro/crate/.htaccess
More details: https://github.com/ResearchObject/ro-crate/issues/297
=> changed redirect per discussion

fairchecker/.htaccess, fairchecker/README.md
a redirection mechanism for FAIR-Checker IDs
=> Permanent ids for FAIR-Checker project

odissei/README.md, odissei/ns/mcal/.htaccess
- added Jacco as contact point in readme
- added mcal redirects to triple store hosted by triply
=> Added redirects for MCAL subproject 

polifonia/.htaccess
Fixing redirects for the choco and jams onotologies
=> Bug fixing .htaccess

fairchecker/.htaccess
=> 2 redirect rules for pointing /data/$id and /assessments/$id to the fair-checker web site 

dob/.htaccess, dob/README.md
Dear maintainer,
Could you please create a permanent identifier for the dob ontology?
I hope I provided you with the correct documents via this way.
Project: Open Built Environment Data
Prefix: dob
Namespace: https://w3id.org/dob
Best, Gary
gary@xri.online
=> Create a permanent identifier for the dob ontology and instance data

GayCities/.htaccess, GayCities/README.md
=> Added and tested GayCities endpoint

faircookbook/.htaccess
project: faircookbook
action: update to .htaccess
comment: target page not released yet
=> faircoobook  / update .htaccess / minting FCB086

ontove/.htaccess
In this commit, the `.htaccess` file has been updated to correctly resolve all requested files based on the `Accept` header.
=> update .htaccess ontove ontology

sebi/.htaccess, sebi/README.md
=> sebi uri request

pharmaccess/.htaccess, pharmaccess/README.md
Hi,
We are adding the directory for services developed by PharmAccess.org.
Regards,
César and Femke
=> Adding PharmAccess directory and MomCARE URL

fuel/.htaccess, fuel/README.md
Let me know if any changes are required. Thanks
=> New entry for fuel

GaboInLOD/.htaccess, GaboInLOD/README.md
we are building the first Domain URI
=> created a domain URI for our project GaboInLOD

virtual-reality-ontology/.htaccess, virtual-reality-ontology/Readme.md
I am creating this for research work with industrial implications.
=> virtual reality ontology

womo/.htaccess, womo/README.md
added womo ontology with htaccess forwarding to my github
=> Add womo ontology to w3id.org

caapt/ontology/.htaccess, caapt/ontology/README.md
I am a PhD student and would like the use the w3id domain to make LOD resources for my project available. Thank you!
=> CAAPT namespace request

hereditary/ontology/genomics/.htaccess, hereditary/ontology/phenoclinical/.htaccess
I added the content response for RDF/XML and Turtle request for https://w3id.org/hereditary/ontology/genomics/schema/.
Note: The rules have been tested before creating the PR.
=> Added RDF/XML and Turtle content response

KITI/.htaccess, KITI/README.md
KITI (Knowledge Graph for the Internet of Things) ontology added.
By Francisco Javier Zorzano Mier, UPM, Nov 24.
=> KITI (Knowledge Graph for the Internet of Things) ontology

geosrs/alignments/.htaccess, geosrs/application/.htaccess, geosrs/co/.htaccess, geosrs/cs/.htaccess, geosrs/datum/.htaccess, geosrs/planet/.htaccess, geosrs/projection/.htaccess
- create repositories for the extensions under /geosrs
- adapted the htaccess to be able to redirect to the corresponding extensions files
=> Updated redirections for extensions

sensotwin/.htaccess, sensotwin/applicationontology/.htaccess, sensotwin/workflow/.htaccess
- change & correct workflow location
- change project overview location
- add fallback ontology gh-page location
- add fetch all rules & location
=> sensotwin change targetlocations

aio/.htaccess
the ordering of the rules is switched around a little here for my own sanity. not the most helpful diff.
=> switch back to mostly static

vliz-be-opsci/.htaccess, vliz-be-opsci/README.md
We are a developper team from the [flanders marine institute](https://vliz.be/en) dedicated to open science.
We would like to use this platform to expose our namespaces/ontologies, profiles and knowledge graphs.
=> Create .htaccess README.md vliz-be-opsci

ga4gh/.htaccess
New re-write rule in place to support additional URLs from @ahwagner
=> GA4GH Update .htaccess update

CoPla/.htaccess, CoPla/README.md
Ontology which was developed as part of the project "Decision Support for Companion Planting" (https://github.com/kai-vu/companion-planting-decision-support)
=> CoPla - Companion Planting Ontology

GerPS-onto/FIMDatenfelder/README.md, GerPS-onto/ontology/README.md
contacts update for Gerps_-onto and GerPS-Datefield!
=> Update Ontologie contacts

pedropaulofb/.htaccess, pedropaulofb/README.md
Add readme and .htaccess files. Created with the intention of sharing academic and professional contributions.
=> Add pedropaulfb

gaia-x/.htaccess
=> Update Gaia-X JSON-LD context routes

dmont/.htaccess, dmont/README.md
add w3id for dmont, Device Management Ontology
=> add dmont: Device Management Ontology

earthsemantics/.htaccess, earthsemantics/readme.md
Add earthsemantics identifier for semantic artefacts published on [EarthPortal](https://earthportal.eu/).
=> Added earthsemantics identifier

opengpt-x/README.md
The README.md file was updated with the correct permalink.
=> Update the README.md for "opengpt-x"

peo/.htaccess
I modified the htaccess because the html page was wrong
=> modified .htaccess

isample/vocabulary/materialsampleobjecttype/.htaccess
tried to get fancy, didn't work.
=> ENV:currentversion wasn't working, hard code like other vocabs

gaia-x/.htaccess
=> Update gaia x documentation

coach/.htaccess, coach/README.md
Hello Maintainer,
I kindly request the addition of this new ID, which will be utilized for publishing open-source ontology.
Thank you for considering this request, and please let me know if further details are needed.
Best regards,
Enrico@LinkedData.Center
=> New "coach" ontology namespace

dcs-se-extension/.htaccess, dmpqv/.htaccess
HI,
in pull request #4614 I accidentally edited a file out of my scope. Here only the relevant files for my ids are edited.
Thank you!
Best,
Lukas
=> update .htcaccess to align with repo move

dacbarbos/.htaccess, dacbarbos/README.md
Create new W3ID/workspace for DACBARBOS Brand.
=> Add dacbarbos w3id

dacbarbos/README.md
Suggested change by @TallTed after the merge of PR 4616
=> Update README.md for dacbarbos

dataspace/.htaccess, dataspace/README.md
Hello,
Here is a request to add a redirection for an ontology for data space, based on the work of the European funded project DSSC.
Best
Pierre
=> feat: add dataspace redirection for the data space ontology - DSSC

nco/.htaccess, nco/readme.md
=> request to initialize nco

vital-records/.htaccess
This PR adds the vital records vocabulary redirects.
=> Add Vital Record vocabulary.

unterrichtsvideos.net/.htaccess
- add new redirect rule for metadata specs
=> Add redirect to metadata specs

AnonymizationOntology/.htaccess, AnonymizationOntology/ReadMe.md
this creates the namespace for the Anonymization Ontology, an ontology to describe capabilities and other characteristics of software for anonymizing datasets
=> add AnonymizationOntology namespace

dseco/.htaccess, dseco/README.md
Target repo : https://github.com/Orange-OpenSource/dseco
=> Added dseco folder

ci/.htaccess, ci/README.md, cr/.htaccess, cr/README.md, cterm/.htaccess, cterm/README.md
Added identiiers for construction project management ontologies together with @Cassa97
=> [CI,CR,CTERM] Add identifiers 

rml/.htaccess
Same as other specs, but now also for RML Logical View.
Also fixes a change in the ontology.
=> RML Logical View redirects

doll/.htaccess, doll/README.md
Please check and pull our changes for the doll directory which will be used for the Dictionary of Letterlocking project. We have added contact details to the README file. Thank you.
=> doll setup and initial config

nco/.htaccess, nco/readme.md
modifying the redirect for subdirectory.
=> fixing redirects for subdirectory

bbo/.htaccess, bbo/readme.md
=> request for w3id purl - bbo

CBGP-App/.htaccess, CBGP-App/README.md
the ontology to run our front-end database interface
=> adding the CBGP application ontology redirect

nih-grants/.htaccess, nih-grants/README.md
Adding to make referencing of NIH grant announcements easier using identifiers. Tested all rewrite rules using htaccess tester on 27 January 2025. README includes contact information. Functions for NOT, PA, PAR, PAS, RFA, and RFS identifiers as of 27 January 2025.
=> Wrote and tested NIH grant redirects.

coato/.htaccess, coato/README.md
CoatO is an ontology of thin film sputtering processes.
=> Add CoatO - an ontology for thin films

courses/.htaccess, courses/README.md
New request with updated directory name
=> Push coursesonto (updated directory)

dseco/.htaccess
Added dseco redirect rule for direct access to named ontology file.
Added dseco redirect rule for generic access to latest (1.5.0) ontology file.
=> Modified dseco redirect rules.

kgcp/paper2lkg/.htaccess
=> KGCP: Adding access to the "paper2lkg" repo

iaam/i40fd/vocab/canopen-ifm/.htaccess, iaam/i40fd/vocab/canopen-ifm/README.md
This vocabulary adds support for ifm CANOpen devices.
=> iaam/i40fd: Added canopen vocabulary

kgcp/DPFusion/.htaccess
DPFusion research project entry point.
=> Adding the entry point to the DPFusion project

rio/.htaccess
* Simplify .htaccess for RIO
* Ontology files have been renamed
=> Update RIO redirects

GayPassport/.htaccess, GayPassport/README.md
Added and tested for all example URLs.
=> Adding information for Gay Passport website.

ontoforge/.htaccess, ontoforge/readme.md
Added redirects for the vocabularies of the OntoForge community
=> Added redirects for the vocabularies of the OntoForge community

lumc/.htaccess
Add BEAT COVID study and dataset redirections
=> Add beatcovid redirections

eduvocs/.htaccess, eduvocs/README.md
Add basic redirect rules of application, specific rules first (if they change at later point)
=> (add) eduvocs

kgcp/DPFusion/.htaccess, kgcp/README.md
1. Update the DPFusion repo name.
2. README update.
=> DPFusion repo rename & README update

eduvocs/.htaccess
Fix for a double encoding issue (Trying to fix it without the NE flag first)
=> (fix) double encoding issue

eduvocs/.htaccess
(fix) apache double encoding issue; restructured routes [apologies for the effort)
=> (eduvocs) fix: id route

CMECS/.htaccess
Please replace existing rewrite rule for CMECS with this one. Thank you.
=> Update .htaccess for Ecoportal

ga4gh/.htaccess
The rewrite rule should match the other GKS products based on recent changes. Approved by ourselves in a local repo
=> Updated GKS va-spec rewrite rule

unterrichtsvideos.net/.htaccess
=> (unterrichtsvideos.net) fix invalid route

tempo/.htaccess, tempo/README.md
Added the updated Data Template Ontology (TempO)
The Update is based on the DT Ontology. The Namespace was changed due to possible confusion between Digital Twins (DT) and Data Tempates (DT)
=> Added information for the Data Template Onotology (TempO)

CMECS/.htaccess
Please replace existing rewrite rule for CMECS with this one (Ecoportal admin recommended rewrite rule) Thank you.
=> Update .htaccess- CMECS Ecoportal

khmo/.htaccess, khmo/readme.md
requesting purl for http://w3id.org/khmo and http://w3id.org/khmo/merged
Thank you
-Tuan
=> submission for khmo

rml/.htaccess
Redirects for https://github.com/kg-construct/rml-io-registry
=> rml: add RML IO Registry

ontoforge/windprofile/.htaccess
Added redirects for the windprofile taxonomy
=> Create .htaccess for windprofile

semts/.htaccess, semts/README.md
[Pull request #4763](https://github.com/perma-id/w3id.org/pull/4763) was missing some of the mentioned changes:
- Removed "LogLevel alert rewrite:trace3" from .htaccess
- Changed path name in README
=> Fix for PR #4763 Update for SemTS 

tss/.htaccess, tss/README.md
Initial htaccess redirects for RDF Time Series Snippets
=> tss: add RDF Time Series Snippets

codemeta/.htaccess
Fixes: https://github.com/codemeta/codemeta/issues/376
=> codemeta: properly rewrite versioned requests for json-ld

iqb/.htaccess
Sorry I made a mistake in the regular expression. Could you please accept my pull request again. Have a nice day
=> Rewrite rule for iqb-specifications

iqb/.htaccess
Please add the new rewrite rule for verona interfaces. Thank you.
=> Please add the new rewrite rule for verona interfaces for iqb

dano/.htaccess, dano/README.md
Dear maintainers, 
I would like to add a permanent identifier as defined by the pull request. Thank you!
Kind regards
Phillip
=> [dano] added permanent identifier for DAnO ontology

UniverseTBD/AstroLLaVA/.htaccess, UniverseTBD/AstroLLaVA/README.md
Redirect to the project's repo.
=> AstroLLaVA project entry

metpo/.htaccess, metpo/README.md
closes 
- https://github.com/berkeleybop/metpo/issues/4
- https://github.com/perma-id/w3id.org/issues/4788
=> create metpo namespace

aksw/.htaccess, aksw/README.md
for @aksw projects
- also including https://w3id.org/aksw/norse# namespace for Scaseco/jenax
Thanks
=> add AKSW identifier

UniverseTBD/AstroLLaVA/dataset/.htaccess, UniverseTBD/AstroLLaVA/dataset/README.md
Adding the used dataset for the project.
=> AstroLLaVA dataset entry

metpo/.htaccess
=> Update .htaccess for bioportal redirection

first-responder/.htaccess, first-responder/README.md
- Change from vcplayground.org hosted contexts to fr-spec hosted contexts.
- Update README links.
- Related changes: https://github.com/digitalbazaar/fr-spec/pull/3
=> Update first-responder redirects.

salmon/Doc-KG/.htaccess, salmon/Doc-KG/README.md
Doc-KG: Unstructured Documents to Knowledge Graph Construction, Identification and Validation with Wikidata.
=> Doc-KG Entry for the SALMON Project

tkz/.htaccess, tkz/README.md
Added tkz folder with .htaccess and README
=> Added tkz folder with .htaccess and README

aco/.htaccess
making the redirect more simple
=> Update .htaccess to simplify rules

elmo/.htaccess, elmo/README.md
the Ecolink Model Ontology needs permanent IDs!
=> Added folder and .htaccess for elmo

gerps/ontology/datafield/.htaccess, gerps/ontology/process/.htaccess, gerps/ontology/software/.htaccess
I am a bit inexperienced with .htaccess files, so I overlooked that `RewriteCond` only applies to the next `RewriteRule` (which of course makes sense). I fixed that by adding some bloat to our .htaccess files. 
If anyone has a good idea how to simplify the files, I am open to recommendations.
=> GerPS Ontologies: fix broken content negotation

dataset-forge/.htaccess, dataset-forge/README.md
this pull request adds a new URI 'https://w3id.org/dataset-forge' for the Dataset Forge resource. It includes a README.md file.
Maintenance
This URI will be maintained by @YoucTagh 
Contact
For more information, please contact [yousouf.taghzouti@inria.fr](mailto:yousouf.taghzouti@inria.fr)
=> add config for `dataset-forge`

g17/.htaccess, g17/readme.md
The Graceful17 Ontology (g17)
Repository created to store the redirections of the Graceful17 Ontology.
=> Add Graceful17 Ontology redirection

g17/.htaccess
=> Changes to rewrite rules

coso/.htaccess, coso/README.md
fix redirect to allow multiview to support different redirects from the root folder. Cleaned up readme page to add bullets for maintainers.
=> COSO allow multiview 

pmd/README.md, pmd/fsp/.htaccess
Flame Spray Pyrolysis Ontology
=> FSP-Ontology

skmo/.htaccess, skmo/readme.md
Hi, we would like to kindly request the purl of: http://w3id.org/skmo
=> request to create skmo

lumc/.htaccess, lumc/README.md
Removed Rajaram from and added Anna to maintainers.
Added identifier for COMODULATE dataset.
=> Updated maintainers and added identifier

kdm/.htaccess
Sorry for pushing the fix just minutes after the first push/merge... `.htaccess` is not my daily bread.
=> Fixed bug with encoded hash.

barks.n.bytes/.htaccess, barks.n.bytes/readme.md
This redirect maps https://w3id.org/barks.n.bytes to https://ritamargherita.github.io/barks.n.bytes/
=> Add redirect for barks.and.bytes

semts/.htaccess
Fixed a mistake with regex patterns: Used %1 instead of $1 (commit 475bab4)
=> [semts] Update htaccess

cacao/.htaccess
Correcting comments as suggested in #4893
=> Cultural Artefacts Contextual Ontology - Correction

WEHI-SODA-Hub/.htaccess
=> Fix WEHI-SODA-Hub

eclipse-cap/.htaccess, eclipse-cap/README.md
The [Eclipse Conformity Assessment Profile (CAP)](https://eclipse-dataspace-cap.github.io/) is an ontology, reference implementation and testbed (TCK) to express in RDF the information from [ISO/IEC 17000:2020 Conformity assessment — Vocabulary and general principles](https://www.iso.org/standard/73029.html) processes.
=> Add eclipse-cap redirect

eclipse-cap/.htaccess
inspired from https://github.com/perma-id/w3id.org/blob/master/gaia-x/.htaccess
=> feat: handle ontology object short links

glue/.htaccess, glue/README.md
Addition of glue folder which directs to GLUE ontology documentation and ontology files
=> Addition of 'glue' folder

smartedge/recipe-model/.htaccess
Added .htaccess redirections for the SmartEdge Recipe-model schema
=> Create .htaccess for recipe-model

q2forge/.htaccess, q2forge/README.md
this pull request adds a new URI 'https://w3id.org/q2forge' for the Q²Forge resource. It includes a README.md file.
Maintenance
This URI will be maintained by @YoucTagh 
Contact
For more information, please contact [yousouf.taghzouti@inria.fr](mailto:yousouf.taghzouti@inria.fr)
=> add config for `q2forge`

tido/.htaccess, tido/README.md
Hi,
In order to ensure accessibility of my developed resource, I would like to request a permanent w3id. I believe I have followed the instructions correctly, but if not, please let me know and I will make the necessary changes. 
Best,
Ritten Roothaert
=> Request for permanent w3id for the TIDO ontology 

cacao/.htaccess
Making a small change to the redirect
=> cacao to cacao-ontology

health-ri/.htaccess, health-ri/README.md
I'm adding a new folder for Health-RI, the organization I work for. The folder includes a `README.md` and an `.htaccess` file. My affiliation with Health-RI can be verified via the official website linked in the README.
Thanks for your support! Please let me know if you have any questions or need anything else.
Best regards,
Pedro
=> add readme and htaccess files for health-ri

semts/.htaccess
Added a "code" path to htaccess, linking to the github repository
=> [semts] Updated htaccess

mirapie/.htaccess, mirapie/README.md
This redirect points to the ontology documentation page of the MIRAPIE ontology
=> Add mirapie

aruna/.htaccess, aruna/README.md
We changed our major URL from aruna-storage.org to aruna-engine.org
Thus pull request will change the URLs in the redirect rules accordingly. Moreover, I slightly changed the description in the readme and added a history section as well.
Thanks for the service!
=> Update description and URLs to reflect our new base URL aruna-engine.org

miro/.htaccess, miro/README.md
This pull request creates the w3id for my MIrO ontology.
=> MIrO ontology

nfdi4cat/pid4cat-model/.htaccess, nfdi4cat/pid4cat-model/README.md
Add support for multi-version schema & adjust to new docs layout.
=> Update nfdi4cat/pid4cat configuration

nfdi4cat/pid4cat-model/.htaccess, nfdi4cat/pid4cat-model/README.md
Fix wrong base url path from last update. Sorry for the avoidable extra work.
=> Fix nfdi4cat/pid4cat configuration

dfc/.htaccess
We're getting an error on one of our redirects - the latest version isn't picking up the directory. I've added a wildcard to resolve that.
=> Correct error on dfc latest version redirect.

dh-atlas/.htaccess
=> Fix overwriting rule

dfgfo/.htaccess
=> Update .htaccess of dfgfo

usage-project/.htaccess, usage-project/README.md
Semantic URIs for the [USAGE project](https://www.usage-project.eu/).
=> Add `/usage-project/` - USAGE project

icbo/.htaccess, icbo/readme.md
I would like to kindly request to add the icbo w3id url.
=> request to add icbo url

cff/.htaccess
Thanks for merging #5014 so quickly!
Unfortunately, I failed to commit a bug fix in the default `RewriteRule`, which this PR now fixes.
Tested the complete `.htaccess` file in an online tester as well this time.
Sorry for the extra work, and thanks for merging!
=> Fix default RewriteRule for `/cff/`

nen2660/.htaccess, nta8035/.htaccess, sml/.htaccess
A user (@pmaria) found a content negotiation error with resolving these ontologies. 
This fix should solve them.
=> fix: conneg for nen2660, nta8035, sml

information-resource-registry/.htaccess, information-resource-registry/README.md
=> Adding information-resource-registry redirect

fff/.htaccess, fff/README.md
Refirection for the FAIR2ADAPT Fairification Framework
=> Redirection for the FAIR2ADAPT Fairification Framework

golem/.htaccess
… to support [FOOPS](https://github.com/oeg-upm/fair_ontologies) compliance.
=> Add content negotiation and versioned IRI redirect for GOLEM ontology

gerps/README.md, gerps/ontology/datafield/.htaccess, gerps/ontology/law/.htaccess, gerps/ontology/software/.htaccess
Simplify gerps ontology redirects (drop "AddType" statements), add new redirect for GerPS-Law
=> Gerps Ontologies: Simplify and add new redirect

dqd-ap/.htaccess
Fixed a typo in forwarding URLs
=> Fixed typo in forwarding URLs

squirrels/README.md, squirrels/fuzzy-sl/.htaccess, squirrels/ogham/.htaccess
=> added squirrel resources from fuzzy-sl and ogham LOD

h2v/.htaccess, h2v/README.md
I would like to add the redirect rules for h2v, the Hydrogen Valley Ontology
=> add redirect rules for h2v

xfsc/.htaccess
Awaiting approval from @clange.
=> Update XFSC redirect to point to Eclipse GitHub

APTO/.htaccess
I updated the script to support content negotiation using AgroPortal.
=> Update .htaccess (APTO)

dolce-bias/.htaccess, dolce-bias/readme.md
This repository containes the documentation of an extension of the ontology DOLCE with observations, inferences, and biases.
It is a first-order theory based on DOLCE written in the format of MACE4/PROVER9 to automatically establish the consistency of the theory by finding a model.
This theory is in press for the conference FOIS conference 
https://www.dmi.unict.it/fois2025/?page_id=303
=> Request of identifier for repository https://github.com/appliedontolab/DOLCE-Bias

riskman/.htaccess, riskman/README.md
Apologies for the repeated request. 
I'd like to allow for trailing slashes.
Thanks!
=> Update Riskman redirects.

egdi/.htaccess, egdi/README.md
This PR adds new permanent identifiers for resources in EGDI (European Geological Data Infrastructure).
=> egdi redirection

egeologija/metadata/.htaccess
Added noescape (NE) flag to handle rewrites properly.
=> Updated flags of rewriteRule

aerospace-x/.htaccess, aerospace-x/README.md
Add Aerospace-X Perma ID based on Gaia-X Ontology
=> Aerospace-X PermaID creation

ldac/.htaccess
Add new redirect /collections-profile under /ldac/
=> /ldac/ Add redirect for collections-profile

fusion/.htaccess, fusion/README.md
redirection will go to the repo at https://github.com/ukaea/ukaea-metadata
=> Creating 'fusion' identifier/namespace for our fusion energy schemas

isample/earthenv/mingroup/.htaccess, isample/earthenv/mingroup/1.0/README.md, isample/vocabulary/materialsampleobjecttype/.htaccess
for minGroup and material sample object type
=> try fixing htaccess to work with non-versioned URIs 

energy-domain/.htaccess
I've just updated our htaccess change due to internal repo directory structure change
Thanks for your work!
=> htaccess change due to internal repo directory structure change

inspec/.htaccess
adds support for [w3id.org/inspec/specification](http://w3id.org/inspec/specification)
=> adding specification endpoint to inspec

KulturVok/.htaccess, KulturVok/README.md
Redirections from https://w3id.org/KulturVok<ANYTHING>  to https://museumsvokabular-de.github.io/Museumsvokabular-Hub/<ANYTHING>
=> added htaccess and readme for KulturVok

KulturVok/.htaccess
RewriteRule wrongly contained terms/ copypasta. Removed.
=> fixed rewrite rule

lit/.htaccess, lit/README.md
Minor updates to README (showing codebase is private for now), and using new private domain.
=> Minor updates to README and new private domain

ewc-onto/.htaccess, ewc-onto/README.md
added .htaccess and readme.md for ewo-onto
=> add new perma-id (ewc-onto)

geosfair/.htaccess
Add new rules to manage more resources
=> Add new rules

nco/.htaccess, nco/readme.md
request to modify NCO PURL - adding new (/base) and soft edits
=> modifying NCO

ontostart/.htaccess, ontostart/README.md
This PR adds `ontostart/.htaccess` with redirects for the `ontostart` namespace.
=> Add ontostart redirects

megabanana/.htaccess
Changed the RewriteRule target from the us-west1 to the us-central1 Google Cloud Run region for megabanana. This updates the redirect destination for all incoming requests.
=> Update redirect URL in .htaccess

write/ontology/.htaccess, write/thesaurus/.htaccess
Updates of the htaccess rules for the ontology and the thesaurus.
=> update of the htaccess rules

signal-description-ontology/.htaccess, signal-description-ontology/README.md
I want to redirect to the documentation of my ontology and host ontology resources.
=> Signal Description Ontology

ft/rdm/.htaccess
PID is shortened and therefore changes to .htaccess are made.
Internally, devices are no longer sorted by category but are located together within devices folder. This allows for flexible changing categories of individual devices and categories themselves, as they are no longer included in the PID.
Sven Brock, Chair of Fluidics, TU Dortmund University, Germany
E-Mail: sven.brock@tu-dortmund.de
Github: sven-brock
=> ft - refactor rewriterule

valuesets/.htaccess, valuesets/README.md
ValueSets
=========
Homepage:
* https://linkml.io/valuesets/
Documentation:
* https://github.com/linkml/valuesets/
Bioportal:
* https://bioportal.bioontology.org/ontologies/VALUESETS
Contact:
* Chris Mungall cjmungall AT lbl DOT gov @cmungall
* Mark Andrew Miller MAM AT lbl DOT gov @turbomam
* Justin Reese JustinReese AT lbl DOT gov @justaddcoffee
* Melissa Haendel melissa AT tislab DOT org @mellybelly
=> adding valuesets prefix

kim/.htaccess
See
https://github.com/dini-ag-kim/fdm-lernziele/issues/3#issuecomment-2969360991 ff
=> Adjust fdm-glossar rule

fuel/.htaccess
Adding content negotiation for different formats
=> Update .htaccess for FUEL ontology
