perma-id/w3id.org

people/.htaccess
people/nandana/.htaccess

Added a set of URL rewrite rules with content negotiation as discussed in https://github.com/perma-id/w3id.org/issues/65. I tested the change in a local Apache server and it worked as expected.

Rewrite rule for http://w3id.org/people/nandana

---

people/nxg/.htaccess
people/nxg/README.md

Updated .htaccess with people/nxg/skua; added README.md

Updated people/nxg links

---

library/.htaccess

Now every rule has a condition. Finally this should work for all ontologies. Works on my machine.

Added condition for every rule

---

ontolink/.htaccess

Adding a new permalink directory.

Added /ontolink

---

env/.htaccess

Pull request to change https to http  - for @dr-shorthair

http, not https

---

env/.htaccess

Capture string after base and copy to path

---

clipc/meetings/.htaccess

Corrected representation of URL containing a space and added additional links to the meetings section.

corrected space in url and added additional meetings

---

clipc/meetings/.htaccess
clipc/schemas/.htaccess

Corrections to URLs with spaces, and a new link for an xsd schema

Corrections and new schema

---

clipc/docs/.htaccess
clipc/forms/.htaccess
clipc/meetings/.htaccess

Some additions to the list of links, and minor corrections.

correcting names, adding new links

---

isil/.htaccess

Sorry this needs to be corrected.

US-* needs to be lowercase in URI

---

cwl/.htaccess
cwl/README.md

See https://common-workflow-language.github.io/
(not sure if the .htaccess is quite right, but let's see what Travis says :-) )

Add /cwl for Common Workflow Language

---

own-pt/.htaccess
own-pt/README.md

This request adds an initial top-level directory for our Open Wordnet PT schemas + two simple redirects.

Creating entry for Open Wordnet PT.

---

cmip6dr/.htaccess
cmip6dr/README.md

A set of URLs for documents associated with the Coupled Model Intercomparison Project Phase 6 (CMIP6) data request. The data request contains specifications of physical parameters (temperature, ice thickness, soil components, etc), the structure of required output files, and the experiments (numerical simulations) from which the data is requested.

New domain for CMIP6 Data Request

---

food/.htaccess

I would like to request to add a redirection for handling Linked Data entities related with the project FOOD (https://www.expo.cnr.it/en/node/158).
Thanks in advance,
S.

Redirection for project FOOD

---

food/.htaccess

Add the redirect to the real URL of the project.

Redirect to project home.

---

food/.htaccess

The redirect has been changed in a new server.

Change redirect to new server

---

mare/.htaccess

This fork is required for a EU project we are involved within the fishery domain

Mare project

---

als-telemonitoring/.htaccess

New redirect to data  upload app.

---

socomp/.htaccess

Creating a redirect from w3id.org/socomp/ to delrubio.inf.ed.ac.uk

Creating the redirect for the SoComp project

---

national-ocean-council/api/.htaccess

Reverts perma-id/w3id.org#135
pull request did not have the desired effects.  Please revert.  Thank you.

Revert "added NE and P flags to rewrite"

---

cmip6dr/ns/.htaccess
cmip6dr/variable/.htaccess

This is a simple addition of new links.

Adding some new redirects within the cmip6dr directory

---

.gitignore
smetzger/Metzger-et-al_2015_IRGA-GSS/.htaccess

Please pull new redirect for /smetzger/Metzger-et-al_2015_IRGA-GSS into main repo.
If there is anything else I should do to activate the redirect, please let me know.
Thanks for providing this great service! Stefan.

please pull new redirect for /smetzger into main repo

---

unit/README.md
unit/lro/.htaccess
unit/organizations/.htaccess

From Lepetit Florian's [email to perma-id](https://lists.w3.org/Archives/Public/public-perma-id/2015Oct/0000.html) on 2015-10-16
> We are a group of students from INSA Rouen (a French engineering school)
> working on linked data applications based on UNIT's ( http://www.unit.eu/ )
> meta-data of learning resources.

Adding /unit from Lepetit Florian

---

xapi/adl/.htaccess
xapi/adl/verbs/.htaccess

added directives to turn rewrite engine on and follow symlinks

.htaccess directives

---

xapi/ontology/.htaccess
xapi/ontology/README.md

Added redirect for the ontology
/xapi/ontology/.htaccess

/xapi/ontology

---

xapi/README.md
xapi/acrossx/.htaccess
xapi/acrossx/README.md
xapi/adb/.htaccess
xapi/adb/README.md
xapi/adl/.htaccess

Added new .htaccess files and rules.

Rewrite rules added for /xapi/adb and /xapi/adb

---

nidash/.htaccess
nidash/README.md

For http://nidm.nidash.org/ specs

add: nidash .htaccess

---

spar/.htaccess

Creation of a space for the SPAR Ontologies project (http://www.sparontologies.net).

New .htaccess for SPAR Ontologies website

---

xapi/acrossx/.htaccess

New .htaccess

---

xapi/.htaccess
xapi/adl/index.html

Updated and added index.html to address conflict with physical directory and variable name being the same.

udpate .htaccess

---

people/dgarijo/.htaccess

Rules for accessing dgarijo's description with content negotiation

Rules for accessing dgarijo's description

---

dgarijo/apps/.htaccess
dgarijo/apps/readme.md
dgarijo/readme.md
dgarijo/ro/.htaccess
dgarijo/ro/readme.md

8 redirections for Research Objects with content negotiation and 2 for applications.

redirections to dgarijo's resources

---

dgarijo/ro/.htaccess

I had left a comma after the last ID.

Fixed a typo in 1 redirection

---

class/.htaccess

See https://github.com/hbz/vocabs-edu/issues/5.

Add 302 redirect to ESC turtle on GitHub.

---

dgarijo/ro/.htaccess

The URL contained spaces and didn't resolve to the approapriate page. I have fixed it.

Fixed a problematic URL

---

games/.htaccess
games/readme.md

Added 3 permanent urls for three game applications.

permanent urls for games

---

vacseen/.htaccess

This pull request is for creating a redirect to the VacSeen application

A redirect to the VacSeen application

---

people/keski/.htaccess
people/keski/readme.md

Generated id for Robin Keskisarkka and added redirects in people/keski

Generated id in people/keski

---

xapi/profiles/.htaccess

added new .htaccess for profiles IRI

Added .htaccess

---

idafensp/.htaccess
idafensp/ro/.htaccess
idafensp/ro/htaccess

Folder structure updated and bugs fixed. Five more RO have been added.

Bugs fixed

---

pm/.htaccess

pm added for paul mckellar

---

people/fastflo/.htaccess

removed leading slashes from virtual subdirs,
changed redirect status code to 302

mind missing per-directory prefix in .htaccess files

---

xapi/acrossx/.htaccess

update the .htaccess to be more concise with wildcard rules...previous pull request accidentally targeted the revert base.

Update .htaccess - acrossx

---

xapi/adl/.htaccess

update .htaccess - testing NE flag for hash URI

---

dio/.htaccess

This pull request is to add a redirect to the DIO ontology

redirect for the DIO ontology added

---

xapi/adl/.htaccess

updated the comments in .htaccess and one mistyped URI

Update comments in .htaccess

---

dio/.htaccess

This pull request is to merge the changed redirection URI for the DIO ontology

changed redirection URI

---

diopp/.htaccess

This pull request is for enabling the redirection to the PoolParty extension to the DIO ontology.

redirection for the PoolParty extension to DIO

---

xapi/.htaccess
xapi/acrossx/.htaccess
xapi/adb/.htaccess
xapi/adl/.htaccess

updated redirects to send base URL to target server instead of directory index of w3id.org

Update .htaccess / base redirects

---

rdfbones/README.md

Corrected links to core ontology documentation and download.

---

cspdo/.htaccess

Links to ALIGNED repo. Experimental ontology extending prov to describe
DBpedia software and data engineering environment for ALIGNED tools

first version of cspdo added for ALIGNED project

---

cmip6dr/.htaccess

Changed the target for one URL, and added a new one.

redirected cmip6dr

---

ic/standards/.htaccess

Adding /ic/standards/OCT, /ic/standards/ERM, and /ic/standards/MIME

Adding 3 new links

---

ic/standards/.htaccess

Adding CATT, INTDIS, LIC, MN, NTK.ACES, PM, REVRECALL, and SRC.

Adding 8 new links

---

geolit/ontologies/.htaccess

Added OWL ontologies redirects
Thanks!
best regrds,
diego magro

Adding GEOLIT project

---

kpionto/.htaccess
kpionto/README.md

Hi there, this is the URL for a new ontology called KPIOnto.

welcome kpionto:)

---

sparql-generate/.htaccess
sparql-generate/README.md

Adding redirection to SPARQL-Generate project

added sparql-generate

---

BCI-ontology/.htaccess

As requested on:
http://lists.w3.org/Archives/Public/public-perma-id/2016Feb/0010.html

Request to add a permanent redirect for "BCI Ontology"

---

people/jennybc/.htaccess
people/jennybc/README.md

add a third url for another Google Sheet

add another url for jennybc

---

id-rules/.htaccess
id-rules/README.md

permanent identifiers for the individual rules of the 10 Simple Rules for Identifiers paper.

Add /id-rules/

---

mo/.htaccess
mo/README.md

Creating a persistent url for Mentions Ontology (MO).

Add /mo for Mentions Ontology

---

id-rules/.htaccess

.. adding `$` to the .htaccess rules is good.

id-rules/10 should be distinct from id-rules/1

---

RAND/.htaccess
RAND/OBD/.htaccess
RAND/OBD/README.md
RAND/README.md

Establish top-level directory for RAND Corporation, and
project-specific directory for the RAND OBD project. RAND is a
non-profit, non-partisan research firm (www.rand.org).

Set up for RAND project use.

---

RAND/.htaccess

CLE, DEN, NYC, PGC, PHI, PRV for OBD.

Site links for data collection

---

linkedEarth/.htaccess
linkedEarth/readme.md

Fixing the typos detected by davidlehn

Redirection for the Linked Earth ontology

---

clipc/meetings/.htaccess
cmip6dr/ranges/.htaccess

The "ranges" folder will hold a new set of links relating to data ranges

Minor updates ... adding  "ranges" folder

---

associations/.htaccess
associations/README.md

have a look at https://joernhees.github.io/associations

associations vocab and dataset added

---

associations/.htaccess

associations mapping dataset path corrected

---

pedigree/.htaccess
voic/.htaccess

Please could you pull these requests for redirect to two ontologies
Thanks,
Monika

new redirects for ontologies

---

ro/.htaccess
ro/README.md

Added /ro/bagit

---

eis/vocabs/.htaccess
eis/vocabs/readme.md

A vocabulary which represents the AutomationML Standard - IEC 62714

AutomationML Vocabulary

---

wdaqua/.htaccess
wdaqua/readme.md

Hi from France!
We have developed a new vocabulary called Qanary in the Framework of the WDAqua project: 
http://wdaqua.informatik.uni-bonn.de
Could you create for us a permanent uri?
Merci
Dennis

Adding the Qanary Vocabulary

---

SDEBM/.htaccess

Redirect to the Structured Data Exploration Benchmark at GitHub

Added entry for SDEBM

---

afo/.htaccess
afo/README.md

Redirects to be created:
http://w3id.org/afo/onto/1.1# -> http://sovarr.c4dm.eecs.qmul.ac.uk/af/ontology/1.1#
http://w3id.org/afo/vocab/1.1# -> http://sovarr.c4dm.eecs.qmul.ac.uk/af/vocabulary/1.1#

added the Audio Feature Ontology redirects

---

aufx/.htaccess

fixed main url

---

gerbil/.htaccess
gerbil/README.md

I added redirects (and the README) for the GERBIL project ( http://gerbil.aksw.org )

Added the readme and redirects for the GERBIL project.

---

mo-ld/.htaccess
mo-ld/README.md

Model Organism Linked Database project.
Signed-off-by: Maxime Déraspe <maximilien1er@gmail.com>

add MOLD project (mo-ld.org)

---

linkgen/.htaccess

create a new redirect for an open source project, LinkGen

create .htaccess redirect for LinkGen

---

disk/.htaccess

A page describing the extra materials used in a paper.

Created w3id for ACS2016 extra materials page

---

people/holger

Revert "Create w3id.org for personal homepage"

---

ctdl

Revert "Create ctdl"

---

s2rwro/.htaccess
s2rwro/README.md

I would like to create a new folder to the project: Converting Scripts into Reproducible Research Objects. 
I'm new to this process, so please let me know if there are issues.
Best wishes
Lucas Carvalho

Create w3id.org "s2rwro" for new project

---

people/holger
people/holger/.htaccess

Please revert my previous pull request because it creates a file "holger" in the directory "people" instead of creating a directory of that name (with a ".htaccess" that contains the contents of the current file "holger").

Correct "Create w3id.org for personal homepage"

---

ctdl/.htaccess

@CTITechPlanning This is how the .htaccess file should be created

Added fix redirection for ctdl

---

bibma/.htaccess

... so that I could obtain the expected w3id ("https://w3id.org/bibma")
thx @dgarijo (let me know if anything wrong again)

Fix mistake in rewrite rule

---

bmontology/.htaccess
bmontology/readme.md
people/prototypo/talks/UQ-DKE-20160601/.htaccess

Permanent identifier for ontology publication. 
Would you please create a persistent URL for this ontology?
Best Regards,
Matthias

 Publish an ontology - Permanent identifier

---

art/Readme.md
art/terms/1.0/.htaccess

Registering a permanent identifier for the primary ontology of the
Artivity project.

Added .htaccess and readme.md files.

---

function/.htaccess

add url parameters in redirect

---

aufx/.htaccess
aufx/README.md

this shouldn't  give any 404 errors anymore for e.g. 
http://w3id.org/aufx/ontology/1.0#Effect
this should also work for turtle and rdf/xml files:
curl -H "Accept: application/rdf+xml" -L http://w3id.org/aufx/ontology/1.0
curl -H "Accept: text/turtle" -L http://w3id.org/aufx/ontology/1.0
thanks

htaccess fix (hopefully)

---

sip/.htaccess
slo/.htaccess

Please could you accept this request as a matter of urgency. Many thanks!!

Added the redirections for slo and sip ontologies

---

voldemortkg/README.md

We have been asked to provide license info with this link directly in this this README.
Thanks.

Add license info to voldemortkg dataset

---

cbv/.htaccess
eem/.htaccess

please could you accept these two pull requests

Pull request for redirected ontologies

---

scholarlydata/.htaccess
stlab/.htaccess
stlab/etna/.htaccess
stlab/wit/.htaccess

Request to enable permanent URLs for stlab.

Update of .htaccess

---

nlp/semanticpackage/.htaccess
nlp/semanticpackage/README.md

Resolve conflicts to update assetDescription redirection

Resolve conflicts

---

clinga/.htaccess
clinga/README.md

adding Permanent Identifiers for Clinga (Chinese Linked GeoData).

adding Permanent Identifiers for Clinga.

---

w2share/.htaccess
w2share/README.md

Hi,
I would like a new w3id identifier for W2SHARE: a new workflow repository project
Best wishes,
Lucas Carvalho

Request for a new w3id.org: w2share

---

sdids/.htaccess
sdids/README.md
sdids/provdq/README.md

adding README file to provdq as well as a README and .access file at root sdids folder

README file with contact info added as requested

---

def/.htaccess
def/readme.md
vocabulary/.htaccess
vocabulary/readme.md

Adding permanent ids to OnToology

Permanent ids for OnToology

---

sw4ml-datasets/.htaccess
sw4ml-datasets/README.md

added sw4ml-datasets

---

truecred/.htaccess

Update for vocab redirect

---

truecred/.htaccess

Signed-off-by: erickorb <eric.korb@accreditrust.com>

Updated context file name.

---

daselab/onto/.htaccess
daselab/onto/readme.md

Pull request to enable redirection from 
http://w3id.org/daselab/onto/ontoname 
to 
http://krisnadhi.github.io/onto/ontoname.owl
where ontoname is currently event, spatiotemporalextent, trajectory

Pull request for http://w3id.org/daselab/onto/

---

nlp/semanticpackage/.htaccess
nlp/semanticpackage/README.md

Nlp update

---

BESDUI/.htaccess

Added entry for the permanent URL for the Benchmark for End-User Structured Data User Interfaces (BESDUI)

Added entry for BESDUI

---

bc/.htaccess
blockcerts/.htaccess
blockcerts/README.md

Create w3id of blockcerts for blockcerts.org with .htaccess rules.

Create w3id for blockcerts

---

blockcerts/.htaccess

@davidlehn thanks for the correction!
I'm working on the json ld context updates now

change redirect to http

---

skg/.htaccess
skg/README.md

Hereby I am requesting for a pull, to add skg ontology
that we are making for a scientific knowledge graph at the
University of Bonn.
Contact address: sadeghi@uni-bonn.de
Bests,
Afshin Sadeghi

Pull request for skg ontology

---

rdfp/.htaccess
rdfp/README.md

added rdfp,  which redirects to http://ci.emse.fr/rdfp/
RDF Presentation description and RDF Presentation Negociation

added rdfp, redirection to http://ci.emse.fr/rdfp/

---

OntoDocRel/.htaccess
OntoDocRel/README.md

.htaccess file for publishing OntoDocRel ontology in OntoDocRel folder at perma-id/w3id.org

Create .htaccess at perma-id/w3id.org in OntoDocRel folder

---

BCI-ontology/.htaccess
BCI-ontology/README.md

* Updates: {.htaccess, README.md}
* 2 commits.

BCI-ontology

---

ooxml/.htaccess
ooxml/README.md
ooxml/onlineInfomativeAnnexes/.htaccess

I am the convenor of ISO/IEC JTC1/SC34/WG4 (OOXML).  We have used PURLs, but will start to use Permanent Identifiers for the Web.

Request for a new directory for OOXML identifiers

---

pep/.htaccess
pep/README.md

Specification and demonstration of Process Execution Platform: A RESTful API to expose process executors that implement processes and generate process executions, whose input and output are RDF graphs.

added PEP -> http://ci.emse.fr/pep/

---

people/essepuntato/.htaccess

This .htaccess contains redirects to Silvio Peroni's personal stuff available online such as biography, papers, etc.

New .htaccess for Silvio Peroni

---

people/essepuntato/.htaccess

New .htaccess created with redirect to GitHub gh-pages instead of rawgit.

Create new .htaccess

---

blockcerts/.htaccess
blockcerts/README.md

Updating contact email and destination URL

update email and destination url

---

semmd/.htaccess
semmd/README.md

The w3id is required for a persistent URL associated with ontologies for materials.

Create .htaccess and README.md

---

cmip6dr/.htaccess
cmip6dr/README.md

Correcting issues raised in perma-id/w3id.org#535

Correction to mistyped URL and README.md

---

people/essepuntato/.htaccess

Added a new regex so as to match with both "papers" and "paper" directories.

Modified a regex for /paper

---

rsp/.htaccess

W3C RSP community group report

RSP add requirements and principles document

---

BCI-ontology/.htaccess
BCI-ontology/README.md

- Redirect to BCI_(plain).owl --> L.O.V. compatibility.
- README update --> L.O.V. registry.

Linked Open Vocabularies: update redirect and README

---

bot/.htaccess
bot/README.md

The Building Topology Ontology is a research attempt to create a simple common ontology for sharing building data on the web.
Thank you for your effort in making it easier to ensure permanent identifiers for ontologies!

Added the Building Topology Ontology (BOT)

---

clipc/meetings/.htaccess
clipc/pages/.htaccess
clipc/pages/README.md
cmip6dr/.htaccess
cmip6dr/README.md

Adding a single link, and updated README.

Adding link for data request 01.00.00

---

cmip6dr/.htaccess
cmip6dr/README.md

There was a spelling error in a link name in the last commit .. sorry for the inconvenience.

Corrected spelling

---

mo/.htaccess
mo/README.md

Changed redirection URL to https://alainperez.duckdns.org

Changed redirection URL

---

people/aperez/.htaccess
people/aperez/readme.md

Redirect to Alain Perez's profile and publication pages

Added aperez to people folder

---

mo/.htaccess
mo/README.md

The ontology has been moved to University's server.

Redirect to its University's server

---

tangpoem/.htaccess
tangpoem/README.md

This is a permanent identifier for Tang Poem LOD project developed at University of Tsukuba.

Permanent identifier for tangpoem

---

jp-textbook/.htaccess
jp-textbook/README.md

This is a permanent identifier for Japanese textbooks.

add new project: jp-textbook

---

quality/README.md
quality/qskos/.htaccess

Please merge this.
I' am adding URI redirection for qskos dimensions and metrics defined according to W3C-DQV.
Thanks, 
Riccardo

URI redirection for qskos dimensions and metrics

---

smetzger/Metzger-et-al_2015_IRGA-GSS/.htaccess

please consider this pull request

updated re-direct

---

akn/.htaccess

A mechanism for handling content negotiations has been added. Two ontologies (ALLOT and UNDO) have been linked.

Updated .htaccess with content negotiations

---

akn/.htaccess

The previous redirect didn't point to the akn directory.

Bugfix redirect

---

UN/.htaccess
UN/FAO/README.md
UN/README.md

w3id.org placeholder for UN system redirectors (subsequently ontology)

Adding base URL for UN URLs

---

version/.htaccess
version/README.md

This adds a redirect for http://w3id.org/version/ontology.

Add version ontology redirect

---

i40/sto/.htaccess

This reverts commit 950f949832d7e5a0d1caf4e0cab0e6860ab6d9e5.

Returning to 301 redirect

---

UN/.htaccess
un/.htaccess

Modified the htaccesses so as to handling the whole redirection from "un" and using "UN" as alias.

UN redirecting to un

---

ido/.htaccess

Changed again the htaccess, since the previous approach did not work as expected.

Another bug fix for the htaccess

---

ahso/.htaccess
ahso/readme.md

This pull request is for the creation of a folder/redirect for the AHSO project (animal health surveillance ontology) . The 2 commits refer to the creation of a readme and a .htaccess file (I apologise - I tried to squash but after repeated attempts to refork and restart, I always got an error that I had unstaged commits, and some unfamiliar changes kept showing to the .htaccess file inside the folder/project "UN". this was after using github desktop to access the files, and opening the shell to rebase).

AHSO project creation

---

valueflows/.htaccess

relates to https://github.com/valueflows/valueflows/issues/207
ping @elf-pavlik

update redirection to catch various content types

---

mica/ontology/.htaccess
mica/ontology/readme.md

We update our URLs.
We want to add these changes to our URLs.
Thanks

Add some change 

---

mica/ontology/.htaccess
mica/resource/.htaccess

Put redirect url for resource in resource folder

Put redirect for resource in resource folder

---

RAND/.htaccess

New unique urls for the spring 2017 OBD student surveys.

Update for OBD spring surveys.

---

mica/ontology/.htaccess
mica/resource/.htaccess

Modify the web negociation to take account all redirection

Add some changes to URIs

---

mica/ontology/.htaccess
mica/resource/.htaccess

Add rewrite rules for other formats( ttl; rdf etc)

Add some changes

---

openbadges/.htaccess

Sorry, but we need to request a further rollback of the recent changes.

Further rollback due to cyclical URLs

---

un/.htaccess

A new rewriterule for adding the redirect to the repository of UNDO has been added.

Added redirect to repository

---

akn/.htaccess

A new rewrite rule has been added for handling the URL of the repository of ALLOT.

Added redirect to repository of ALLOT

---

s2rwro/.htaccess
s2rwro/README.md
w2share/.htaccess
w2share/README.md

removing w3id.org/s2rwro. Moving it to w3id.org/w2share/s2rwro
updating .htaccess and README of w3id.org/w2share

updating w3id.org/w2share and removing w3id.org/s2wro

---

ido/.htaccess
medred/.htaccess
medred/README.md
s2rwro/.htaccess
s2rwro/README.md
w2share/.htaccess
w2share/README.md

The redirect for the versions of the various ontologies were wrong.

Bug fix redirect

---

seas/.htaccess

redirects to http://www.maxime-lefrancois.info/docs/SEAS-D2_2-SEAS-Knowledge-Model.pdf

Added redirection for SEAS Deliverable D2.2

---

illusnip/.htaccess
illusnip/README.md

illusnip is a online dataset snippet extrator.

add access to illusnip

---

people/jpcik/.htaccess

fixed redirections in different formats

Added jpci personal redirects

---

sociallink/.htaccess
sociallink/README.md

SocialLink is our resource linking knowledge bases to social media profiles. The proposed id links to our website.

Added SocialLink resource

---

usgs/.htaccess

Removed slash from beginning of pattern

Fixed content redirect

---

hero/.htaccess
hero/README.md

The first pull request didn't work (I got a "continuous-integration/travis-ci/pr — the travis ci build failed" error), sorry!
I've created a second pull request...
Thanks!
besr regards,
diego magro

Added HERO project redirections

---

blockcerts/.htaccess
blockcerts/README.md

- Add blockcerts v2 context
- Update contact email

Add blockcerts v2 context

---

people/paolo/.htaccess

Updated redirection website

---

un/.htaccess

Adding a redirector for sustainable development goals

un: Adding a redirect for SDG

---

un/.htaccess

Fixed redirector for guidelines to correct root

Updated redirector for guidelines

---

openbadges/.htaccess

Fixes https://github.com/openbadges/openbadges-specification/issues/154

Redirect broken TrueCred link to openbadgespec.org

---

rsp/.htaccess

Added a reference to the abstract syntax document

Update .htaccess on rsp/

---

wesp/.htaccess
wesp/README.md

Added wesp project redirections

Added wesp project redirections

---

dataset_900/.htaccess
dataset_900/README.md

I have created the dataset_900 folder. Please, could you pull my updated project?
Thanks!
Best regards,
diego magro (Computer Science Dept. , University of Turin)

dataset_900 project added

---

rdf-spreadsheet/.htaccess

Points to http://173.212.240.179:8268 which is for a demo paper

Add rdf-spreadsheet

---

bim4eepsa/.htaccess
measurements4eepsa/.htaccess

Update .htaccess for bim4eepsa & measurements4eepsa

---

cwl/.htaccess

@tetron, please review -- thanks!

Update redirects to use correct domain, version

---

xapi/.htaccess
xapi/profiles/.htaccess

Updated htaccess rules for new xapi profiles ontology and JSON-LD context docs

update to profiles 

---

people/ralbertoni/.htaccess
people/ralbertoni/README.md
quality/.htaccess
quality/README.md

Please consider adding my changes.
Thanks, 
Riccardo

Giving a shorten and stable URL to My web page

---

niw/.htaccess
niw/README.md

Project NiW: Notebooks into Workflows.

Request for a new w3id: niw

---

dataset_900/.htaccess

Dear all,
could you pull my updated project, please?
Thanks!
Best regards,
diego magro

Changed redirections

---

cwl/.htaccess

.. sorry @dgarijo, I got it wrong in #776!
(greedy regex..)

Reordered cwl-viewer rules

---

xapi/.htaccess

Added rule to handle 3 verbs that were accidentally left out (abandoned, satisfied, waived)

Rule Addition .htaccess

---

dataset_900/.htaccess

Could you please pull my revised project?
Thanks!
diego magro

mappings changed (updated to lodview)

---

lob/.htaccess
lob/README.md

Added README.md with contact details. Also, included content negotiation rules for redirection to a server with the thesaurus deployed as Linked Open Data

README and LOD rules

---

BCI-ontology/README.md

Update for usage on SSN/SOSA (new alignment).

BCI-ontology: README.md update

---

quality/.htaccess

Please consider merging my changes. 
Thanks, 
Riccardo

Fixing some issue in ../quality/ and adding new rewriting

---

people/essepuntato/.htaccess

Added a redirect to a new repository where to store HTML presentations (slides)

Added a redirect for HTML presentations

---

mapvowl/eval17/.htaccess
mapvowl/eval17/README.md
rml/editor/eval17/.htaccess
rml/editor/eval17/README.md
rml/editor/eval17/results/.htaccess

I added more links to different aspects of the MapVOWL and the RMLEditor.

Added more links for MapVOWL and the RMLEditor

---

smartenvironment/.htaccess
smartenvironment/README.md
smartenvironment/patterns/.htaccess

Used by http://ecareathome.se project. Aiding GitHub user @marycore to get this set up.

Request to add smartenvironment identifier

---

smartenvironment/.htaccess

one new line is added to the .htaccess under smartenvironment folder

added new redirect into d .htaccess

---

rash/.htaccess

This permanent ID space has been created for providing a way to permanently identify all the resources associated to the RASH Framework, i.e. a set of specifications and writing/conversion/extraction tools for writing academic articles in RASH, i.e., a markup language defined as a subset of HTML for writing scientific articles.
The responsible for this space is Silvio Peroni, who can be contacted by email (essepuntato@gmail.com) or twitter (@essepuntato).

Create new permanent id for RASH and its Framework

---

rash/README.md

Added the comment as README for the RASH permanent id space

Added readme for RASH id space

---

ontocity/.htaccess
ontocity/README.md
ontocity/patterns/.htaccess

The links to the OntoCity Ontology and its patterns are added under the name ontocity.

added description of ontocity

---

squap/.htaccess
squap/README.md

SQuAP project.

---

nellrdf/.htaccess
nellrdf/README.md

- Redirection changed to http://nell-ld.telecom-st-etienne.fr/
- Added Pierre Maret to the List of Contributors

Updated redirection and list of contributos

---

esbm/README.md

adding Permanent Identifiers for ESBM  (short for Entity Summarization BenchMark)

Create README.md for ESBM

---

bufalinis-notebook/.htaccess

modified htaccess

---

people/lucascarvalho/.htaccess

Updated redirection for w3id.org/people/lucascarvalho.
Thanks.

updated redirection for people lucascarvalho

---

ibp/.htaccess
ibp/README.md

Added additional path under w3id.org/ibp/ for FMUont ontology.
Update htaccess and readme.md

Adding additional path under w3id.org/ibp/

---

arco/.htaccess
arco/README.md

This pull request is for obtaining a permanent identifier for the ArCo project (cf. README).

Permanent identifier for the ArCo project.

---

dave/.htaccess
dave/README.md

We will upload the RDF file and the ontology documentation in the coming days, however, we would need the w3id in order to add it in a submitted paper.
Thanks,
Jeremy

Pull request for DaVe Ontology

---

minerva/.htaccess
minerva/README.md

request link to minerva ontology

minerva ontology

---

dts/.htaccess
dts/readme.md

The Distributed Text Services API is a specification under development at https://github.com/distributed-text-services.

Added README and redirects for DTS.

---

people/matt/.htaccess
people/matt/README.md

Please incorporate changes. Thank you.

Redirects to RDF and website for people/matt

---

stopp/.htaccess
stopp/README.md

Added SToPP. Contact: <sven.lieber@ugent.be>

Added SToPP. Contact: <sven.lieber@ugent.be>

---

.gitignore
cso/.htaccess
cso/readme.md

We are releasing a new resource:
- Computer Science Ontology
- Web portal for crowdsourcing it

added link to the Computer Science Ontology

---

coops-uk/2017/.htaccess
coops-uk/2017/README.md

This is for LOD for the Coops UK 2017 dataset
Contains 303 redirectios and README that has test URIs

Initial config for coops-uk/2017

---

adso/.htaccess

initial Mezcaloteca vocabulary rewrite

---

adso/.htaccess

fix, protege import failed previously

adso, add fallback to ttl in .htaccess

---

adso/.htaccess
adso/README.md

.htaccess: changed to github.io, edited README.md

---

arm/.htaccess
arm/README.md

First addition of https://w3id.org/arm for Art and Rare Materials Ontology Extensions to BIBFRAME

Add arm - Art and Rare Materials Ontology Extensions to BIBFRAME

---

sdpo/.htaccess
sdpo/readme.md

.htaccess redirects for SDPO ontology

Initial commit for redirects to sdpo ontology

---

moeebius/.htaccess
moeebius/README.md

Please merge our version update of the MOEEBIUS ontology.
Thanks
georg

Added version update of MOEEBIUS ontology

---

cso/.htaccess

Added a new line in the .htaccess file that allows to have access to the different resources of the ontology

added new rule that allows to directly access resources

---

arm/.htaccess

Redirects to https://ld4p.github.io/arm site

---

cocoon/.htaccess
cocoon/README.md

Asking permission to add
https://w3id.org/cocoon/def
which redirects to
https://miranda-zhang.github.io/cloud-computing-schema/

Adding /cocoon/def to w3id.org

---

semtk/.htaccess
semtk/README.md

added semtk - semantics toolkit

---

cc/.htaccess

Change location of webcredits

---

affectedBy/.htaccess
affectedBy/README.md

AffectedBy ODP

---

eep/.htaccess
eep/README.md

New Execution-Executor-Procedure (EEP) ODP

Execution-Executor-Procedure (EEP) ODP

---

mediatype/.htaccess
mediatype/README.md

Thanks to Daniel for picking up my initial mistake. Hope there aren't any more

/mediatype/

---

ontosoft-vff/.htaccess
ontosoft-vff/README.md

Creating redirection to: https://lucasaugustomcc.github.io/ontosoft-vff/

create ontosoft-vff w3id

---

cwl/.htaccess
cwl/README.md

Adds version permalinks to https://github.com/common-workflow-language/cwlprov/

Added CWLProv profiles

---

squirrel/.htaccess

Squirrel ontology moved into Squirrel Project

change or hosting domain

---

people/dylanvanassche/.htaccess
people/dylanvanassche/README.md

Add Dylan Van Assche to `./people` to create some semantic LD on my personal website.

Add Dylan Van Assche to people

---

biolink/.htaccess
biolink/README.md

I am requesting a w3id for biolink.
Fixes https://github.com/biolink/biolink-model/issues/112

Adding w3id request for biolink

---

ccso/.htaccess
ccso/README.md

I just need to add a 303 redirection from w3id.org/ccso to my Github repository

htaccess for perma-id redirection

---

tree/.htaccess
tree/README.md

I am working on some proof of concepts for describing tree relations between HTTP documents. Requesting a base URI here!

Added the Tree ontology

---

cocoon/.htaccess
cocoon/README.md

Update ontology to v1.0
Move old content to the v0.1 folder

add version number in url

---

dts/.htaccess

We just made our specifications website available. Here is the PR for the redirection. Thanks !

/dts : add website for documentation

---

reproduceme/.htaccess
reproduceme/README.md

Added redirection for REPRODUCE-ME repository and ontology (https://sheeba-samuel.github.io/REPRODUCE-ME/)

Redirection for REPRODUCE-ME repository

---

arco/.htaccess

Updating of rewrite rules for ontologies.

Updating of rewrite rules for ontologies.

---

ozcar-theia/.htaccess
ozcar-theia/readme.md

Repository created to store the redirections to the OZCAR-Theia thesaurus: **ozcar-theia** containing .htaccess and readme.md
Allowed contributors for further updates: 
* Véronique Chaffard <veronique.chaffard@ird.fr> @vchaffard
* Charly Coussot <charly.coussot@univ-grenoble-alpes.fr> @charlycou

ozcar-theia repository

---

ga4gh/.htaccess
ga4gh/README.md

GA4GH (Global Alliance for Genomics and Health) would like to set up a space for redirects.

Initial add of GA4GH space and redirects

---

idsa/.htaccess
idsa/README.md

Added new redirect to the permanent github location of the vocabulary release.

New redirect

---

cocoon/.htaccess
cocoon/README.md
cocoon/data/.htaccess

ldf-server is at http://35.227.26.187:5000/cocoon_v1.0

Adding redirect rules for new ldf-server

---

ibp/.htaccess

Added rules for 
-          Hex: https://w3id.org/ibp/hbc/hex 
-          Bim4Hex: https://w3id.org/ibp/hbc/bim4hex

Added rules for HEX and bim4hex ontologies

---

empathi/.htaccess
empathi/README.md

Dear admin
Could you please merge empathi ?
Thank you

adding empathi ontology

---

ga4gh/.htaccess

Links added for public access points to the Cloud Work Stream documentation

Update with Cloud Work Stream links

---

people/matt/.htaccess

Changes to support WebId `https://w3id.org/people/matt/profile#me`

Changes to support WebId

---

ga4gh/.htaccess

Large Scale Genomics public minute links added and URL updated for code for professional conduct

Large Scale Genomics items and URL updated

---

0x1/.htaccess
0x1/README.md

0x1.Academy is the project for Blockchain education, utilize Blockcert to issue certificate to participant. http://0x1.academy (construction)

Initiation of 0x1 Academy

---

ga4gh/.htaccess

RNASeq team added

---

dingo/.htaccess
dingo/README.md

I would like to obtain a permanent URL redirection service for the DINGO ontology, as specified in my .htaccess file.
Thank you very much for your great job.

Permanent URL for DINGO ontology.

---

affectedBy/.htaccess
eep/.htaccess
eepsa/exn4eepsa/.htaccess
eepsa/exn4eepsa/README.md
eepsa/exr4eepsa/.htaccess
eepsa/exr4eepsa/README.md
eepsa/foi4eepsa/.htaccess
eepsa/foi4eepsa/README.md
eepsa/p4eepsa/.htaccess
eepsa/p4eepsa/README.md
eepsa/q4eepsa/.htaccess
eepsa/q4eepsa/README.md

Added redirections for new modules of the EEPSA ontology

Update of EEPSA ontology and its modules

---

eepsa/q4eepsa/.htaccess

Q4EEPSA HTML Redirection fixed

Q4EEPSA HTML Redirection fixed

---

pnv/.htaccess
pnv/README.md

Hi, 
Thanks for reviewing my redirect file.
Best wishes,
Lodewijk

Pull request for redirect to new vocabulary

---

music-circle/.htaccess
music-circle/README.md

music circle ontology init

---

pfeepsa/exr4pfeepsa/.htaccess
pfeepsa/exr4pfeepsa/README.md
pfeepsa/foi4pfeepsa/.htaccess
pfeepsa/foi4pfeepsa/README.md
pfeepsa/q4pfeepsa/.htaccess
pfeepsa/q4pfeepsa/README.md

Added the redirection to Q4PFEEPSA, FoI4PFEEPSA and EXR4PFEEPSA ontology modules

PFEEPSA ontology modules

---

biolink/.htaccess

See: https://github.com/biolink/biolink-model/issues/165. for details

Short term redirect to make things resolve

---

phuse/.htaccess

MRG: Additional prefixes for cdisc terms

---

flashcards/README.md
flashcards/vocab/2018/.htaccess

htaccess for flash card vocabulary.

Flashcard vocabulary

---

biolink/README.md

Adding co-maintainer of biolink

---

arco/.htaccess

Add new rule for redirecting requests associated with ontology entities.

Rule for ontology entities.

---

OntoPBM/.htaccess
OntoPBM/README.md

.htcaccess file created
README.md created
Provided link to project home
Provided contact information for the maintainers of the project

Create a permanent URI for the OntoPBm ontology resource

---

ontopbm-aquatic/.htaccess
ontopbm/.htaccess

Reverts perma-id/w3id.org#1165

Revert "added SSL certificates in .htaccess"

---

vir/.htaccess

Just realised it was pointing to the wrong url. Thanks @davidlehn

updated .htaccess

---

special/.htaccess
special/README.md

I added a new permanent identifier for the vocabularies and ontologies developed under the SPECIAL (Scalable Policy-aware Linked Data Architecture For Privacy, Transparency and Compliance) project, a Research and Innovation Action funded under the H2020-ICT-2016-1 Big Data PPP call

add SPECIAL project

---

quality/.htaccess
quality/README.md

Please consider merging my request for a new permanent id, 
https://w3id.org/quality/DQV/examples
Cheers, 
Riccardo

request for https://w3id.org/quality/DQV/examples

---

wimuQ/.htaccess

I would like to create an w3id to my website from my PhD work.

Creation of wimuQ web site for the PhD

---

FOG/.htaccess
FOG/readme.md
OMG/.htaccess
OMG/readme.md

directing towards http://linkedbuildingdata.net/OMG/ resp. http://linkedbuildingdata.net/FOG/

Adding redirects for OMG and FOG ontology

---

nidash/.htaccess

Per https://github.com/perma-id/w3id.org/issues/394, use github's raw file endpoint not rawgit.

Drop rawgit

---

people/.htaccess

Adding my two github/online identifiers as redirects to my web profile page

Add people/alanbly and people/adammcormick

---

readi/.htaccess
readi/readme.md

Readi ontology 
Ontologies for representing requirements in OWL 2 as developed in the readi project

Project for ontology based requirements management.

---

yxl/.htaccess
yxl/readme.md

Please pull my changes to add my ontology uri on your repo

The redirection for yxl works and korkut ontology has been created

---

affectedBy/README.md
bim4eepsa/README.md
bim4pfeepsa/README.md
clinga/README.md
disk/readme.md
dm4eepsa/README.md
eep/README.md
esbm/README.md
fog/readme.md
illusnip/README.md
kpionto/README.md
measurements4eepsa/README.md
measurements4pfeepsa/README.md
mint/readme.md
omg/readme.md
ontosoft-vff/README.md
opm/README.md
poultryFarms4eepsa/README.md
rai/readme.md
rc/README.md
rdfbones/README.md
saref/README.md
saref4ee/README.md
saref4ener/README.md
sek4pfeepsa/README.md
vocab/_readme.md

Fix missing spaces in header markup in many repos.

Fix header markup.

---

express/.htaccess
ifc/IFC2X3_Final/.htaccess
ifc/IFC2X3_TC1/.htaccess
ifc/IFC4/.htaccess
ifc/IFC4_ADD1/.htaccess
list/.htaccess
omg/.htaccess

I have updated the accept headers and overall ontology locations for the OMG, IFC, EXPRESS, and LIST ontologies. Thank you for accepting the changes.

OMG, IFC, EXPRESS, and LIST ontology locations updated

---

yxl/.htaccess

The .htaccess has been updated.  The new link for wiki has been created.

Udate .htaccess

---

ga4gh/.htaccess

Minuting documents updated for 2019 locations, with Discovery groups added

2019 document link updates

---

sari/.htaccess

Added RewriteCond for disambiguate html and ttl

Added RewriteCond

---

sepses/.htaccess
sepses/README.md

We add an identifier for SEPSES project, http://sepses.ifs.tuwien.ac.at

sepses pull request

---

ln/.htaccess
ln/README.md

start if an ontology for lightning 
( mailto:solidpay0@gmail.com )

start of ontology for lightning

---

smetzger/Metzger-et-al_2019_NEON-BAMS/tutorial_data/.htaccess
smetzger/Metzger-et-al_2019_NEON-BAMS/tutorial_data/README.md

- Added .htaccess and readme for tutorial data under smetzger/Metzger-et-al_2019_NEON-BAMS folder

Adding tutorial data redirect

---

mint/instance/.htaccess

The project description and maintainers are the same

added a redirect for instances

---

sea-lod/.htaccess
sea-lod/README.md

By Solidarity Economy Association Ltd.

Redirects for the sea-lod project

---

express/.htaccess
ifc/IFC2X3_Final/.htaccess
ifc/IFC2X3_TC1/.htaccess
ifc/IFC4/.htaccess
ifc/IFC4_ADD1/.htaccess
list/.htaccess

I changed file locations for the IFC, List, and EXPRESS ontologies. All the rest has remained identical.

updated file locations for IFC, List, and EXPRESS ontologies

---

aho/.htaccess
aho/README.md
hso/.htaccess
hso/README.md

These are two ontologies to complement a previous framework that already had a permalink on w3id. Thanks in advance for considering if this is OK.

Creating two more ontologies

---

people/ralbertoni/.htaccess

Please accept such new PR, It adds content neg. for foaf served in my web site.
Thanks,

adding content negotiation for foaf profile in turtle

---

media/dma/.htaccess
media/dma/README.md

- The redirections have been updated: HTML content for browsers and XML content to APPs
- The license has been added to the readme file, as well as a brief description

Redirections and readme updated

---

rec/.htaccess

Redirect unversioned requests to latest release (v2.3).

Updated REC namespace for 2.3. release

---

FAIR_Evaluator/.htaccess

change to https

---

FAIR_Evaluator/.htaccess

added trailing slash

---

italia/data/.htaccess

Added rule fore redirecting data.

Rule for data

---

italia/data/.htaccess

Completed rules for data.

---

d1f9cd/.htaccess
d1f9cd/README.md

Article to be submitted early next week, repository will be populated by then.

Redirect to data/code referenced in scientific literature.

---

cowcerts/.htaccess

Provides URLs for:
- JSON LD context.jsons
- JSON Schema files
- Documentation in RTFD
Everything versioned using git tags

Added cowcerts rules for education

---

cocoon/.htaccess

Fix Regex Capture Group

---

ecsel-dr-sn-SSP/.htaccess
ecsel-dr-sn-SSP/README.md

Hi,
I want to create the URI `www.w3id.org/ecsel-dr-sn-SSP`.
Could you please squash the two commits into one?
Thank you very much

Creation of URI 

---

timebank/0.1/.htaccess

I just realized that I missed the [R=303,L] part in the first rule.

Missing [R=303,L] for first rule.

---

timebank/0.1/.htaccess

n-triples should have the .nt extension, not .n3

Wrong file extension for n-triples

---

webstreams/.htaccess
webstreams/README.md

I created the w3id for the repository that contains the code and the instruction to run the catalog for linked streams.

Created w3id for WebStreams

---

own-pt/.htaccess
own-pt/README.md

redirect the address to the new server

change direct from own-pt

---

timebank/.htaccess
timebank/0.1/.htaccess

Support for json format for the ontology and fixed a wrong type extension (n3 -> nt)

Added JSON support

---

AEOLUSsmartAPI/.htaccess
AEOLUSsmartAPI/README.md

The AEOLUS-SmartAPI is a smartapi to query the AEOLUS resources  serving the FDA FAERS data. We are publishing documentation for which we are requesting a permanent link for easy reference for users.

Added redirect entry

---

arco/.htaccess

The updates is about the change of a rule that allows to access the
ontologies and their associated entities.

Updates for accessing ontologies

---

mediatype/.htaccess

Sorry Daniel, should have done this in the last change. Just moving to HTTP for my server!

mediatypes changes to HTTPS

---

seo/readme.md

redirect to file in our servers

Update .htaccess 

---

ibp/.htaccess
ibp/README.md

added new files accordingly and revised htacces file

Started to integrate widoco based documentation

---

geoff/.htaccess
geoff/README.md

This vocabulary defines the geospatial information systems concepts of form and function that may be applied to any geospatial feature to classify it or to further describe its shape and use.
It extends the OGC geoSPARQL ontology by defining two new classes and two new properties that may be associated with a geoSPARQL geospatial Feature entity. Most forms and functions are highly relevant for the built environment but any geospatial entity may gain from having a form and/or a function associated with it.

Geospatial Form and Function Ontology

---

dc/.htaccess
dc/README.md
dcx/.htaccess
dcx/README.md

The commit history shows that I tried making these changes both as @dublincore and as @tombaker due to inexperience.  The changes made were the same.

Update contact addresses in README.md for DCMI (/dc and /dcx)

---

italia/controlled-vocabulary/.htaccess
italia/onto/.htaccess

This pull request fixes some issues associated with the resolution of
URIs for alignment ontologies and the following controlled vocabularies:
- classifications-for-public-services/life-business-event/life-event
- classifications-for-public-services/life-business-event/business-event
- territorial-classifications/countries/italy

Rule fixing

---

arco/.htaccess

The new configuration allows to redirect to the HTML documentation and
to the right location for ontology alignments.

New configuration for dealing with ontology documentation and alignments.

---

wimuq/.htaccess

Port changed, from 8081 to 8082
Thanks a lot

change the port

---

GDPRep/.htaccess

Added a link for /GDPRep/semantic-tests

added link for /GDPRep

---

meta-share/omtd-share/.htaccess
un/.htaccess
un/README.md
un/fao/README.md

Reverts perma-id/w3id.org#1366
Removed "un/" files by mistake.

Revert "Update rewriting tools ..."

---

ga4gh/.htaccess

Beacon API minutes URL added

---

okn/i/.htaccess
okn/o/.htaccess
okn/o/sd/.htaccess

Added redirection for vocabulary

---

occ/.htaccess
occ/readme.md
oop/.htaccess
oop/readme.md

Added links the rdf ontologies **OCC** and **OOP**. 
This request results from the conversation btw. Wendelin Sprenger and Nicholas Car.

created oop and occ

---

hclscg/.htaccess

We now have a final web location for the community report about a minimum information model for drug-drug interactions. Thank you for pulling this in.

final location for the DDI Minimum Information Community Report

---

arco/.htaccess

Added rule for resolving ontology patterns.

Added rule for resolving ontology patterns

---

airm-o/README.md
airm-o/airm-o/.htaccess
airm-o/atmonto2airm/.htaccess
airm-o/ontology/.htaccess

We updated the redirections to point towards more readable presentations.

Updated redirections

---

sepses/.htaccess

update .htaccess for rdf content negotiation

---

respond/README.md
respond/users4respond/.htaccess
respond/users4respond/README.md

Upload of the Users4RESPOND ontology belonging to the RESPOND project.

USERS4RESPOND ontology of the RESPOND project.

---

biolink/.htaccess

Issue documented in https://github.com/biolink/biolinkml/issues/8

Fixes for biolinkml redirect issue

---

vocabulary/.htaccess

Per @mariapoveda's request
Reverts perma-id/w3id.org#1393

Revert "Update .htaccess"

---

digitalconstruction/README.md
digitalconstruction/monitoring/.htaccess
digitalconstruction/objects/.htaccess
digitalconstruction/organization/.htaccess
digitalconstruction/planning/.htaccess

Redirects for digitalconstruction ontologies created in the DiCtion project. The ontologies have been specified by Aalto University, VTT and VisuaLynk Ltd (Finland).
DiCtion aims at the creation of shared situational awareness of construction projects. There are needs to represent information about the building objects (as well as information objects related to it), construction planning and workflows, construction organization, and monitoring data.
Contact: yuan.zheng@aalto.fi, seppo.torma@visualynk.com

Redirects for digitalconstruction ontologies

---

ic/standards/.htaccess

Should clean up all the bad empty redirects my xsl previously created.

Fix empty redirects,  Add file and repo redirects for 2018/2019

---

respond/.htaccess

RESPOND Ontology .htaccess

---

iomust/.htaccess
iomust/README.md

Please add this permanent redirection.
Thank you,
Francesco

Add redirection for iomust

---

swot/.htaccess
swot/README.md

Please add this redirection to swot ontology. Thanks.

Add swot folder for redirection

---

sw4ml-datasets/.htaccess

The landing page was moved to another location, so i had to update the link

updated redirect link

---

ga4gh/.htaccess

Additional meeting minute links added

links to case discovery, phenopackets, schema blocks

---

pnv/.htaccess
pnv/README.md

Thanks for (reviewing and) merging my updates into the perma-id/w3id.org master branch.

Small updates to pnv branch

---

ro/.htaccess

See https://researchobject.github.io/ro-curate/doc/terms (to be updated)

Add /ro/curate ontology

---

omg/.htaccess

Restructured RewriteRules to enable better redirects

Updated htaccess

---

italia/controlled-vocabulary/.htaccess

Those conditions were not set properly.

Fixed rewrite conditions for text/html.

---

tree/.htaccess

Moves the Tree Ontology from rawgit to jsdelivr

To do #1121 for pietercolpaert

---

engrd/.htaccess
engrd/Readme.md

Engineering RD Permanent Identifier Basic Rule

Engineering RD Permanent Identifier

---

lode/.htaccess

Author and maintainer: Silvio Peroni (essepuntato@gmail.com)
Description: to have a persistent identifier for the LODE service, so as to make it reachable in the most suitable server depending on the particular case.

Persistent URL for LODE

---

cybele/.htaccess
cybele/README.md

Adding space for CYBELE models. See: https://www.cybele-project.eu/

CYBELE model

---

arco/.htaccess
haps/.htaccess
haps/README.md

Added redirect directives for the HAPS ontology.

Added redirect directives for the HAPS ontology.

---

italia/controlled-vocabulary/.htaccess
italia/data/.htaccess
italia/onto/.htaccess

Set up of the new URLs associated with the services of w3id.org/italia.

Endpoint URLs update

---

italia/onto/.htaccess

Small fix to the rule associated with LODE fon ontology visualisation.

Small fix to the rule associated with LODE fon ontology visualisation.

---

so-ontology/.htaccess
so-ontology/README.md

The survey-ontology helps in publishing surveys and answers collected as linked data research objects.

Add so-ontology

---

class/.htaccess

We are finally moving away from /raw.githubusercontent.com. ;-)

Redirect ESC to SkoHub

---

2791/.htaccess
2791/README.md
biocompute/.htaccess
biocompute/readme.md

Init 2791 redirect

---

vcb/el/.htaccess
vcb/el/README.md

Hi!
I'm adding here a redirection to my ontology, so that I can reach <https://users.dcc.uchile.cl/~hrosales/el.ttl> from <https://w3id.org/vcb/el>
Thank you!!
Cheers

adding redirect to ontology 'el'

---

amlo/.htaccess
amlo/readme.md

We are in the process to write a new project publishing a public ontology, so we need a permanent namespace. Please add my new permanent id. Thank you.

Added amlo namepace

---

netbeheer/def/EPrimaireComponenten/.htaccess
netbeheer/def/EVerbinding/.htaccess
netbeheer/def/GPrimaireComponenten/.htaccess
netbeheer/def/GStationcomplex/.htaccess
netbeheer/def/GVerbinding/.htaccess

EVerbinding
EPrimaireComponenten
GVerbinding
GStationcomplex
GPrimaireComponenten

new ontology redirects

---

skgo/.htaccess

redirects rules for two more ontologies have been added.

adding ChemSci and DentSci redirects

---

skgo/.htaccess

ModSci is a reference ontology for modelling different branches of modern science.

adding modsci vocabulary

---

g0v/it/mef/.htaccess
g0v/it/mef/readme.md
g0v/it/readme.md
g0v/readme.md

Please, could you add g0v namespace to w3id?

Added g0v namespace

---

gizmo/readme.md

Improved the readability of the abstract

updated ReadMe file

---

vcb/fel/.htaccess

Hi!
Redirecting "application/rdf+xml" to https://users.dcc.uchile.cl/~hrosales/fel.rdf 
Cheers!
Henry

change xml to rdf

---

ga4gh/.htaccess

Document location altered for Cloud Work Stream

Update cloud minutes to new document

---

ga4gh/.htaccess

Cloud meeting points to the correct new minutes document

cloud document correction update

---

stn/.htaccess
stn/README.md

Update URI for STN ontology

---

sora/.htaccess
sora/README.md

Updated the SoRa Project redirect to the new server hosted at gesis.

Update sora project

---

mediatype/.htaccess

This is being used to demonstrate new elements for DCAT in v2

added redirect for Dataset

---

mediatype/.htaccess

Apologies for the multiple PRs but I couldn't make conneg patterns until the first match was in place for testing!

/mediatype/ conneg for DCAT 2 dataset match

---

ozcar-theia/.htaccess

For https://w3id/ozcar-theia/variables/* URI to be properly redirected.

change redirection rules

---

oebDatasets/.htaccess
oebDatasets/README.md

we want to connect json and ontologies with a permanent id. This is for the project obenebench.
https://openebench.bsc.es/html/dashboard

adding ontology for OEB datasets

---

fair/plex/.htaccess

Hi @dgarijo ,
Thanks for all the support.
I wonder if this way is a good practice for PIDs of ontology versions or do you recommend another approach? 
Gracias!
Joao

Adding version 0.1.2

---

netbeheer/IECCIM/.htaccess
netbeheer/IECCIM/readme.md

Added subdomain for publication of the IEC CIM model in OWL

added subdomain for IECCIM OWL publications

---

netbeheer/IECCIM/.htaccess

subdomain rediercts didnt work, this should fix it

fixed redirect issues

---

g0v/it/mef/.htaccess

a missing space prevent rdf response

typo in RewriteRule

---

requirement-ontology/.htaccess

Cahnge is needed as the target server layout has changed.

Changes to server layout 

---

d2s/.htaccess
d2s/README.md
data2services/README.md

* add d2s folder with .htaccess and README.md for the data2services graph at the Institute of Data Science at Maastricht University
* Edit `data2services` readme to update docs URL and contact

Add d2s folder for data2services graphs at Maastricht University

---

tern/.htaccess

Using 303 redirects instead of 302 as per https://www.w3.org/TR/swbp-vocab-pub/#recipe3

Using 303 redirects instead of 302

---

CBGP_SEEK/.htaccess
CBGP_SEEK/README.md
FAIR_Training_LDP/.htaccess
orca-x/.htaccess

server moved to a more permanent location at CBGP UPM-INIA

changed redirect to new server

---

cpr/.gitignore
cpr/.htaccess
cpr/README

Creating an id for a new ontology.

Documentation new ontology

---

JazzOntology/.htaccess

Hi! Please add the Jazz Ontology

created .htaccess

---

transmodel/.htaccess

changed rewrite rule to proper URI:
```
RewriteRule ^.*$ https://oeg-upm.github.io/snap-docs [R=303,L]
```

transmodeling

---

gas/.htaccess
gas/readme.md

 added directory for gas model

---

wimuq/.htaccess

Please, update the IP address.

Update IP address

---

digitalconstruction/Agents/.htaccess
digitalconstruction/BuildingAcoustics/.htaccess
digitalconstruction/BuildingMaterials/.htaccess
digitalconstruction/Contexts/.htaccess
digitalconstruction/EnergySystems/.htaccess
digitalconstruction/Entities/.htaccess
digitalconstruction/IndoorAirQuality/.htaccess
digitalconstruction/Information/.htaccess
digitalconstruction/OccupantBehavior/.htaccess
digitalconstruction/Processes/.htaccess

Hi, 
Sorry for bothering you still but I needed to make a small fix to the XML redirect. 
Best regards,
Seppo

Small fixes to XML redirect

---

amlo/.htaccess

added rdf xml format support and changed project base url. Now is public.

added rdf xml format support

---

ga4gh/.htaccess

Updates made to the location of minuting documents for GA4GH meetings in 2020

GA4GH 2020 Document locations

---

CONSIDER/.htaccess
CONSIDER/README.md

Hi. Please add the CONSIDER statement

created readme and htaccess

---

digitalconstruction/Activities/.htaccess
digitalconstruction/Variables/.htaccess

Added new redirects to additional ontologies: 
1. Digital Construction - Variables
2. Digital Construction - Activities
Best, 
Seppo

Added Variables and Activities

---

ga4gh/.htaccess

Added standard links for support documents for GA4GH specifications

Product Approval elements added

---

ga4gh/.htaccess

htsget link correction (extra chars were on the URL)

htsget link correction

---

ga4gh/.htaccess

TASC Force links added

---

citizenship/.htaccess

@msporny I assume that extra slash is a typo?

Fix citizenship.

---

dini-ag-kim/.htaccess

Adds another rewrite rule to "dini-ag-kim" for publishing a specification for Service Cards for Open Educational Resources.

Add ^oer-service-card/(.*) rewrite rule

---

alkis/.htaccess

Do I always have to open a pull request when I change something?

One target link was wrong

---

moeebius/.htaccess
moeebius/README.md

revision of htaccess and readme to new version and usage of github.io page

revision of htaccess and readme - new version, github.io

---

relod/README.md

First version of the readme file

first readme file

---

relod/.htaccess

Please, create this file, it's part of my PhD work. The contact is Andre Valdestilhas, email: firmao@gmail.com

First version of RELOD: The LOD dataset matching

---

atomgraph/linkeddatahub/apps/.htaccess

https://w3id.org/atomgraph/linkeddatahub/apps/hierarchy

Added apps/hierarchy redirect

---

interactions/.htaccess
interactions/README.md
interactions/www2020/.htaccess

Create directory for Interactions-HSG videos https://interactions.ics.unisg.ch/ . Add demo video for WWW 2020.

Create directory for Interactions-HSG videos

---

kim/.htaccess

Sorry, I forgot one thing in the last PR. This should be it for now.

Update redirect for hcrt at (DINI AG) KIM

---

examode/.htaccess
examode/readme.md

New redirect for EXAMODE ontology

---

ga4gh/.htaccess

Removed extra character at end of link

Encrypted format minutes link correction

---

reward-ontology/.htaccess
reward-ontology/README.md

reward ontology folder added

---

demeter/.htaccess
demeter/README.md

This repository will have all DEMETER project related models - https://h2020-demeter.eu/

DEMETER Agriculture Information Model

---

openeduhub/.htaccess
openeduhub/README.md

Hello there,
please add OpenEduHub. We are a German project defining vocabulary for learning objects and want to make them referenced with permanent IDs.

OpenEduHub

---

poseidon/.htaccess
poseidon/README.md

Create w3id redirection for [poseidon framework](https://poseidon-framework.github.io)

Poseidon - standardized framework for archeogenetics data

---

learner-record/.htaccess
learner-record/readme.md

A profile of Verifiable Credentials for lifelong, interoperable learner records

Initial learner-record files for w3id.org

---

omop/.htaccess
omop/README.md

A vocabulary of standard clinical concepts (see https://www.ohdsi.org/data-standardization/the-common-data-model/)

Add namespace for the OMOP Common Data Model

---

ipsoeu/.htaccess
ipsoeu/README.md

Added redirection to the URI space of the Innovative Public Services Observatory (IPSO).

Added /ipsoeu/

---

http/.htaccess
http/README.md

Hello,
I would like to register the **http://w3id.org/http** namespace for an OWL ontology of HTTP interactions. Please let me know if you need more information.
Thanks

HTTP ontology

---

spice/README.md

Added the README file introducing the w3id.org space for SPACE

w3id.org README for SPICE

---

hdgi/.htaccess
hdgi/README.md

- Create hdgi directory
- Add configured .htaccess file
- Add README.md

Add human device gesture interaction(hdgi) ontology re-direction details

---

GISOntology4Renovation/.htaccess
GISOntology4Renovation/README.md

A GIS-based ontology to support building renovation.
Contact and more info is provided in README.md

Project name: GISOntology4Renovation

---

bmat/.htaccess
bmat/readme.md
brcomp/.htaccess
brcomp/readme.md
bridge/.htaccess
bridge/readme.md
brot/.htaccess
brot/readme.md
brstr/.htaccess
brstr/readme.md

added multiple bridge ontologies that were created in the research project wiSIB (https://www.wisib.de/).

Bridge Ontologies

---

costumeCore/ontology/.htaccess
costumeCore/ontology/readme.md

update to version 0.4.1 with HTML page from LODE

---

waterSmart/.htaccess
waterSmart/readme.md

we are still developing the ontology

init pull for our ontology 

---

ifcp/.htaccess
ifcp/README.md

This is a permanent identifier for Japanese intangible folk cultural properties.

new ifcp project

---

glosis/.htaccess
glosis/README.md

A new semantic information model for SOIL

new repository GloSIS

---

dcso/.htaccess
dcso/readme.md

Updated the .htaccess file for the dcso ontology.

Updated DCSO .htaccess file

---

cerrotti/323t98501/.htaccess
cerrotti/README.md

Addingnewperson

---

ga4gh/.htaccess

Added link to new Sequence Annotation minutes

Sequence Annotation minutes added

---

tern/.htaccess
tern/README.md

/tern/ updates

---

bundle/.htaccess
ro/.htaccess

..which is still GitHub pages https://github.com/ResearchObject/ResearchObject.github.io/

RO-Crate now on https://researchobject.org/

---

EVI/.htaccess
EVI/README.md

Requesting inclusion of  EVI ontology

Re-direct entry with README added for EVI ontology

---

biocompute/.htaccess
biocompute/readme.md

- Add redirect for raw extension domain schemas
- Update IEEE-2791-2020

Add Extension Domains

---

openeduhub/.htaccess

Hello there,
I added a rewrite rule to point to our overview page of available vocabulary.

added rewrite rule to point to overview page of available vocabulary

---

demeter/.htaccess

content negotiation didnt work with 302, I am trying with 303 as in other examples

try 303 instead of 302

---

demeter/.htaccess

content negotiation is still not working, i put the entries in order following other examples

still trying to make redirection work

---

hdgi/.htaccess

Add a redirection to https://w3id.org/hdgi/gesture-interaction-pattern

Add an additional redirections to w3id.org/hdgi

---

spoi/.htaccess
spoi/README.md

This endpoint is for Smart Points of Interest dataset: * https://sdi4apps.eu/spoi/
Contacts: 
* Raul Palma <rpalma@man.poznan.pl> (https://github.com/rapw3k/)
* Otakar Cerba <cerba@kgm.zcu.cz>
* Karel Charvat <charvat@plan4all.eu>
* Jan Macura <macurajan@gmail.com>

new endpoint

---

ga4gh/.htaccess

Update cloud, fasp on interplenary life cycle

---

00/.htaccess
00/README.md

– The name is explained in detail in 00/README.md.

Dictionary 00

---

ga4gh/.htaccess

Fix for FASP minutes URL

---

enyr/.htaccess

This first version of the file use the same server as LODE

First version of Enyr perma-id

---

biocompute/.htaccess
biocompute/readme.md

Changes to be committed:
modified:   .htaccess
modified:   readme.md

Add redirect for portal.aws.biochemistry.gwu.edu

---

codata/.htaccess
codata/README.md
env/README.md

Planning to segment CODATA services

New ID space for CODATA

---

openeduhub/.htaccess

Updated .htaccess to redirect to https

---

italia/controlled-vocabulary/.htaccess
italia/data/.htaccess
italia/metadata/.htaccess
italia/metadata/catalog/.htaccess
italia/onto/.htaccess

Changed all htaccess files in 'italia' in order to redirect to a new infrastructure

Italia - redirect to a new infrastructure

---

eeo/.htaccess

Remove AddType information now available in .htaccess on server.

Change redirect

---

profile/.htaccess

Yes, I keep finding errors in my patterns from use over time... Such is life!

one pattern error fixed, more examples of use

---

oho/.htaccess
oho/README.md

Please kindly accept this merge for redirecting the OHO ontology  to <https://w3id.org/oho#>
Regards,
Edlira Vakaj
edlira.vakaj@bcu.ac.uk
BCU

OHO Ontology

---

testalod/.htaccess

The target endpoint has been relocated to a different server.

Service relocation

---

FDS_VocBench3/.htaccess

new server for our vocbench deployment

migration to new server

---

urban-iot/.htaccess

Fix content-negotiation for urban-iot modules
Repo ref: https://github.com/Comune-Milano/ontologie-iot-urbani
cc @Comune-Milano

Update urban-iot .htaccess

---

xmal/.htaccess
xmal/README.md

The domain for the Xmalesia project has changed. Please accept this pull request. Thanks.

Updated redirect for /xmal

---

idsa/.htaccess

This PR reflects the lessons learned from our work on integrating the IDSA namespace ontology into the Linked Open Data Vocabularies.

Improved redirects to the correct ontology files

---

afarcloud/.htaccess
afarcloud/README.md

AFarCloud ontology

---

rg-mpg-de/.htaccess
rg-mpg-de/README.md

This will provide access to Vocabularies and other data from the [Max Planck Institute for European Legal History](https://www.rg.mpg.de/en). For now, there is only one SKOS concept scheme.

Add rg-mpg-de redirection

---

datascope/.htaccess
datascope/README.md

Updated the ontology location (created with LODE/widoco). Now with actual content negotiation.

new location for ontology

---

haf-dev/.htaccess
haf-dev/README.md
haf/.htaccess
haf/README.md

Would like to add W3ID entries for HAF and HAF Dev environments.

HMML Authority File - W3ID additions

---

ga4gh/.htaccess

logo and professional conduct links updated

logo and professional conduct links updated

---

sbeo/.htaccess
sbeo/README.md

Hi Sir/Madam, 
Would you be so kind as to add a permanent identifier to my ontology website? 
Thanks in advance.

Smart Building Evacuation Ontology (SBEO)

---

index.html

I've had to explain to a few people how to create new W3ID identifiers so I'm improving the index page of the site:
- Table of Content
- Headings
- More description on technical Git operations
If these changes are accepted, I will improve the repo's README.md also.

improved website index content

---

index.html

I think this now says what was intended...

(editorial) minor rewording in index.html

---

sao/.htaccess
sao/readme.md

Redirects to Github repository with documentation created using Widoco

Adding redirects to SAO ontology

---

biocompute/.htaccess
biocompute/readme.md

Changes to be committed:
modified:   .htaccess
modified:   readme.md

Add redirect for BCOo registry

---

cdc/.htaccess
cdc/readme.md
cto/.htaccess
cto/readme.md

Hi, 
I added two folders with redirects to two new ontologies I'm responsible for.
Best regards,
Mathias Bonduel

added CDC and CTO (ontology repositories)

---

rsp4j/.htaccess
rsp4j/README.md

W3id for RSP4J

---

devops-infra/.htaccess
devops-infra/readme.md

We will be adding the corresponding .htaccess file soon as well

Repository for a DevOps infrastructure ontology network

---

iot/fd/.htaccess
iot/fd/readme.md

Reserving URL for a new fault detection/recovery ontology

added htaccess file for a new fault detection/recovery ontology

---

smetzger/Metzger-et-al_2021_OSSE-LES-ERF/data-commons/.htaccess

Updating data repository URL for manuscript by Stefan Metzger and David Durden

smetzger/Metzger-et-al_2021_OSSE-LES-ERF data-commons update

---

digitalconstruction/Agents/.htaccess
digitalconstruction/BuildingAcoustics/.htaccess
digitalconstruction/BuildingMaterials/.htaccess
digitalconstruction/Contexts/.htaccess
digitalconstruction/EnergySystems/.htaccess
digitalconstruction/Entities/.htaccess
digitalconstruction/IndoorAirQuality/.htaccess
digitalconstruction/Information/.htaccess
digitalconstruction/Lifecycle/.htaccess
digitalconstruction/OccupantBehavior/.htaccess
digitalconstruction/Processes/.htaccess
digitalconstruction/Variables/.htaccess

Fixing minor bugs in the rules

digitalconstruction - rules fixed

---

openeduhub/.htaccess

Added a redirect so some additional vocabulary repository

Add redirect to OpenEduHub additional vocabulary repository

---

leo/controlled-vocabulary/.htaccess
leo/data/.htaccess
leo/onto/.htaccess
leo/readme.md

adding folder leo for permanent URIs for LEO project

redirection rules for new open data project LEO

---

sssom/.htaccess

Change sssom fallthrough

---

reproduceme/README.md
reproduceme/computational/.htaccess
reproduceme/computational/README.md
reproduceme/core/.htaccess
reproduceme/core/README.md
reproduceme/microscopy/.htaccess
reproduceme/microscopy/README.md
reproduceme/ml/.htaccess
reproduceme/ml/README.md

core, computational, microscopy, and ml are the new subfolders.

reproduceme: created subfolders and .htaccess.

---

bot/.htaccess

Address [bot #80](https://github.com/w3c-lbd-cg/bot/issues/80).
This change adds a rule redirecting requests to a specific ontology version. It also fixes the jsonld and n-triples redirections.
A live environment has been setup for review at http://bot.mischung.net (live for the next 1-2 weeks). Here's a test suite that exercises the redirection rules (requires `curl`):
```bash
#!/bin/bash
set -euo pipefail
function get_url() {
local url=$1
local accept_header=$2
curl -s -i -H "Accept: $accept_header" -o /dev/null -D - $url \
| grep 'Location:' \
| cut -d ' ' -f2 \
| tr -d '\r'
}
function assert_location_equals() {
local actual=$1
local expected=$2
if [ $actual == $expected ]; then
echo ✅
else
echo ❌
fi
}
function test_case() {
local request_url=$1
local expected_location=$2
local …
```

[bot] Add a redirection rule for particular ontology versions.

---

kdsf-ffk/.htaccess

This PR fixes an error in the RewriteRule

Update RewriteRule for KDSF-FFK

---

kdsf-ffk/.htaccess

This pr fixes the RewriteRule. Thanks @acka47

Fixing RewriteRule for KDSF-FFK

---

reproduceme/.htaccess
reproduceme/computational/.htaccess
reproduceme/core/.htaccess
reproduceme/microscopy/.htaccess
reproduceme/ml/.htaccess

Replaced the RewriteCond which was resulting in the html file being returned for the owl file (based on the feedback received from https://github.com/perma-id/w3id.org/issues/2014)

Update .htacess: Remove the RewriteCond that was matching the HTML line.

---

didcomm/.htaccess
didcomm/README.md

added didcomm

---

credentials/.htaccess
vaccination/.htaccess

Adds Vaccine Certificate Vocabulary for usage with Verifiable Credentials

feat: add vaccine credentials vocab

---

ontosenticnet/.htaccess
ontosenticnet/README.md

Added the permanent link to the SenticNet Ontology

Add OntoSenticNet

---

ieee/.htaccess

Adding redirects for the IEEE Draft Std. 1752 as part of comment resolution from the first round of balloting

adds IEEE 1752 schema perma id redirects

---

ldes/.htaccess
ldes/README.md

LDES specification by the European SEMIC programme

Linked Data Event Streams specification

---

amlo/.htaccess

Improved text/html and text/plain negotiation rules

Update amlo .htaccess

---

gaia-x/README.md

Improve the readme for GAIA-X by properly naming the respective group.

Improve GAIA-X Readme

---

digitalconstruction/.htaccess

Fixed the root of the rewrite rules. 
Seppo

Digital Construction Ontologies - Redirect root

---

digitalconstruction/.htaccess

It works mostly fine now. The problem was indeed the incorrect root of the rewrite rules. 
However, a couple of versioning related rules needs to be added.
Seppo

Digital Construction Ontologies - Minor redirect tweaks

---

digitalconstruction/.htaccess

Digital Construction Ontologies - Version redirect adjustments

---

hlac/.htaccess
hlac/README.md

I am requesting the addition of an entry "hlac" for a project called "Highly Abstract"

Add hlac entry

---

bop/.htaccess
bop/README.md

Dear maintainer, 
Could you please create a permanent identifier for the bop ontology?
I hope I provided you with the correct documents via this way. 
Project: Building Performance Ontology
Prefix: bop
Namespace: https://w3id.org/bop
Best, Alex
a.j.a.donkers@tue.nl

Creating a permanent identifier for the bop ontology

---

ckgg/.htaccess
ckgg/README.md

I want to add a new endpoint to release a new public dataset, thank you.

add CKGG: A Chinese Knowledge Graph for High-School Geography

---

people/bogo/.htaccess
people/bogo/README.md

I have created a new folder to store the .htaccess for Bogomil Shopov - Bogo

Repository created to store the redirections of the resources 

---

faircookbook/.htaccess
faircookbook/README.md

Dear all, hope everything is fine like this. First commit. Happy to correct if necessary! Thanks! 💯

create new project faircookbook

---

citedcat-ap/.htaccess
citedcat-ap/README.md

Add redirection to the URI space of the CiteDCAT-AP specification and tools.

Add /citedcat-ap/

---

exatag/.htaccess
exatag/readme.md

ExaTag is a Web-based publicly available semantic annotation tool for clinical reports. It is designed to support physicians during the manual annotation of clinical reports and speed up the overall process. 
First entry point configuration added.

ExaTag: A Web-based Semantic Annotation Tool for Clinical Reports

---

ereefs/.htaccess
ereefs/README.md

with the URI https://w3id.org/ereefs/def/{term}

Basic redirects for ereefs definitions 

---

security/.htaccess

Adds redirects for:
* `https://w3id.org/security/suites/ed25519-2018/v1`
* `https://w3id.org/security/suites/ed25519-2020/v1`
* `https://w3id.org/security/suites/x25519-2020/v1`

Add redirects for /security/suites contexts.

---

devops-infra/.htaccess
devops-infra/def/core/.htaccess

So as to see whether it works nicely with editing tools. And if it does, I will change the rest. Thanks!

Changing to 303 redirections for one ontology module

---

blockcerts/README.md

@lparkerlm @lemoustachiste 
I've added myself in the maintainers list.

doc(Readme): updated blockcerts maintainers list

---

ckgg/.htaccess

Add linked data access point for ckgg

---

security/.htaccess

As discussed here: https://github.com/w3c-ccg/security-vocab/pull/95

Add /security/suites/secp256k1recovery-2020

---

unterrichtsvideos.net/.htaccess
unterrichtsvideos.net/README.md

Manage permanent identifiers related to "meta-videoportal"

added claim of namespace "unterrichtsvideos.net"

---

kg-construct/.htaccess
kg-construct/README.MD

Adding redirects for the W3C CG in Knowledge Graph Construction

KG Construction websites

---

faircookbook/.htaccess

updating the "faircookbook" project .htaccess
sorry to have forgot the project name
link to project readme:  https://github.com/perma-id/w3id.org/blob/master/faircookbook/README.md

Update .htaccess for "faircookbook"

---

biocompute/.htaccess
biocompute/readme.md

Changes to be committed:
modified:   .htaccess
modified:   readme.md

Add redirects for GlyGen and OncoMX

---

security/.htaccess

This PR fixes the registration style for some already registered suite to match the IRIs added to did core test suite, and also registers some new suites.

Add additional suites

---

did/.htaccess
did/README.md

Update DID Spec links

---

duchenne-fdp/.htaccess

Configuration added to resolve root app URLs

root config

---

faircookbook/.htaccess

sorry to send another PR so quickly... I couldn't test the error document redirection properly. :( Now it should work.
link to project readme incl. list of maintainers: https://github.com/perma-id/w3id.org/blob/master/faircookbook/README.md

faircookbook: introduces custom error documents

---

security/.htaccess

This adds x25519 2019 terms for LD Proofs

Add security/suites/x25519-2019

---

codata/.htaccess
env/.htaccess

@nicholascar maybe look at this one for me?

PUV ontology

---

twins/f7012e2b-d1f8-4e50-b97b-8a93bc97a218/.htaccess
twins/f7012e2b-d1f8-4e50-b97b-8a93bc97a218/README.md
twins/readme.md

Added another twin to the twins folder. This one will be used in measurements for an article.
Also added mention to the twins folder readme that others are welcome this folder for twin identifiers as well. This is why I also added readme to the new subfolder.

Add another twin

---

env/.htaccess

See https://github.com/perma-id/w3id.org/pull/2179#pullrequestreview-666832070

Remove #fragments from pattern

---

rd-fairness-tests/.htaccess
rd-fairness-tests/README.md

Hello,
I have added new redirect rules for `rd fairness test` service. These service tests data `FAIRness` of rare disease specific resources.
Thanks for providing this redirecting service

RD fairness service

---

twins/01a88415-d484-479a-a232-1e6443728e51/.htaccess
twins/01a88415-d484-479a-a232-1e6443728e51/README.md
twins/2c649807-ac61-4b6c-8d20-e820cd48323d/.htaccess
twins/2c649807-ac61-4b6c-8d20-e820cd48323d/README.md
twins/775b1b0d-1083-44f2-8c77-ee5782ee5842/.htaccess
twins/775b1b0d-1083-44f2-8c77-ee5782ee5842/README.md
twins/97dd6ce5-143c-4454-8423-82d1b93490ec/.htaccess
twins/97dd6ce5-143c-4454-8423-82d1b93490ec/README.md
twins/a2bf8f8f-e625-4b5f-9533-2659f46e9732/.htaccess
twins/a2bf8f8f-e625-4b5f-9533-2659f46e9732/README.md
twins/c0b88d23-0616-49fe-8587-59163b9bbc0f/.htaccess
twins/c0b88d23-0616-49fe-8587-59163b9bbc0f/README.md

Add six networked twins that will be used in tests for an article.

Add six networked twins

---

faircookbook/.htaccess

thanks in advance!
link to project readme incl. list of maintainers: https://github.com/perma-id/w3id.org/blob/master/faircookbook/README.md

faircookbook: new identifier for new recipe

---

orphadata/.htaccess
orphadata/README.md

Hello,
I have created redirecting config for ordodata. This configuration redirect call for `FAIR Data Point` of ordodata.
Thanks for the help

ordodata FDP

---

gaia-x/.htaccess

Add "Contract" ontology module redirect

---

comein/.htaccess
comein/README.md

maintainer: https://github.com/ComeIn-NRW

added namespace claim

---

comein/.htaccess
comein/README.md

Fixes from reviews of  last pull request #2196, thx!

Added maintainer, fixed static route

---

security/.htaccess

Previously https://github.com/perma-id/w3id.org/pull/2175

Move deprecated security suites to the bottom of the file

---

gbo/.htaccess

Thanks for the info. I updated accordingly.

changed it to temporary uri instead of permanent

---

arm/.htaccess

(apologies for not getting it right first time ;-)

arm: tweaks a couple of 1.0 redirects and add old 0.1 fix

---

303/.htaccess
303/README.md

Hi,
I would like to host my new vocabulary here.

Would like to host new vocabulary

---

uh-linked-data/.htaccess
uh-linked-data/README.md

Adding a `.htaccess` file and `README.md` file for redirection of url to the letterlocking.org website where a vocabulary of terms is being shared.

Adding uh-linked-data

---

profile/.htaccess

Just a change to the back-end system catching these PIDs

/profile/ PID handling system update

---

uh-linked-data/.htaccess

Apologies, a minor issue with the redirection should now be corrected.

Corrected rewrite rule

---

fraunhofer/mappo/.htaccess
fraunhofer/mappo/Readme.md

currently in development by Fraunhofer IPT in Germany;

Add Ontology for manufacturing process plannning 

---

date/.htaccess
date/readme.md

readme.md and .htaccess file are provided under date

Linked Open Date Entities

---

idsa/.htaccess
idsa/README.md

Update idsa redirects to include versioning

---

nsd/.htaccess
nsd/readme.md

I added a redirection to my developed ontology NSD and its documentation.

Added Natural Stone Damage Ontology (NSD)

---

ejp-rd/.htaccess

Hello,
We have added new EJP RD project specific services.
Thanks for the help

New EJP RD services

---

mojo-ac/.htaccess
mojo-ac/readme.md

First try to add the perma-id mojo-ac to w3id.org

First addition of mojo-ac

---

activityanchors/.htaccess
activityanchors/README.md

Adds the `activityanchors` vocabulary.

Add Activity Anchors context

---

aoi/.htaccess
aoi/readme.md

added redirection to the ontology for describing areas of interest (AOI) (https://alhakam.github.io/aoi/).

Areas of Interest (AOI) added

---

ejp-rd/.htaccess

Hello,
We added redirect for new service. This service will create drawing for a given RDF file.

new service added

---

yarrrml/.htaccess
yarrrml/README.MD

- Fix redirect for original screencast
- Add redirect for target screencast
- Add myself as maintainer

yarrrml: add target screencast redirect

---

iadopt/.htaccess
iadopt/ReadMe.md
iadopt/ont/.htaccess

I added redirects for the I-Adopt framework ontology ( https://i-adopt.github.io/ ).
please let me know, if there is something else you need.

iadopt: add redirections

---

lumc/.htaccess
lumc/README.md

Hello,
We added redirect to services provided by LUMC. LUMC is the university hospital based on the Netherlands. In this PR we are exposing FAIR data related services from LUMC via w3id.
Thank you,
Rajaram

LUMC services added

---

ioc/.htaccess
ioc/README.md

Added Readme and redirect for a permanent id space for the internet of construction Ontology

Added IoC Ontology

---

yarrrml/.htaccess
yarrrml/README.MD

Add YARRRML tutorial (https://w3id.org/yarrrml/tutorial/getting-started/) which redirects to https://rml.io/yarrrml/tutorial/getting-started/

yarrrml: add tutorial

---

conjectures/.htaccess
conjectures/README.md

First submission
Created .htaccess and README.md
Updated README.md

First submission for Conjectures

---

exanet/.htaccess
exanet/readme.md
exatag/.htaccess

ExaNet is a Web-based publicly available tool for the interactive visualization and exploration of ExaMode clinical reports. It is designed to support physicians consulting and comparing clinical reports.
First entry point configuration added.

ExaNet public web app for the interactive visualization and exploration of ExaMode clinical reports.

---

react/.htaccess
react/README.md

REACT Ontology redirection

---

biosemantics-lumc/.htaccess
biosemantics-lumc/README.md

Hello,
We added redirect to services provided by the Biosemantics group at the Leiden University Medical Center (LUMC). LUMC is a university hospital based in the Netherlands. In this PR we are exposing FAIR data related services from the Biosemantics group via w3id.
Thank you,
Núria

Biosemantics-LUMC services added

---

nsdra/.htaccess
nsdra/README.md

Dear maintainers of the w3id.org repository,
I would like to kindly ask you to review my pull request and add the "nsdra" entry to w3id.org.
Thank you.

Add 'nsdra' entry

---

srmo/.htaccess
srmo/readme.md

added the Stone Renovation Measures Ontology (SRMO), which should be accessible through https://w3id.org/srmo#.

Added the SRMO ontology

---

related-to/.htaccess
related-to/doi.org/10.5281/zenodo.3978439/.htaccess

sorry for the short time until need-a-fix. :(

related-to: corrects .htaccess rules

---

related-to/doi.org/10.5281/zenodo.5494490/.htaccess
related-to/doi.org/10.5281/zenodo.5494490/README.md

https://github.com/perma-id/w3id.org/blob/master/related-to/README.md

related-to: adds new subdirectory, changes another

---

besocial/.htaccess
besocial/README.MD

added links to social media archiving resources for BESOCIAL

added besocial links

---

sssom/.htaccess

adding a redirect for spec and making sure legacy purl still works

Update SSSOM .htaccess

---

kobl/.htaccess
kobl/README.md

Adding new README.md and .htaccess file with redirects to the 5 current ontologies that is KOBL

Add new KOBL space to the repository

---

people/hatter/.htaccess
people/hatter/readme.md

add readme.md and .htaccess file to w3id.org/people/hatter/

add w3id.org/people/hatter/

---

mgkb/.htaccess
mgkb/README.md

Please merge the pull request for creating a permanent ID for MGKB.
Thank you :)

Permanent ID for MGKB

---

mgkb/.htaccess
mgkb/README.md

Hello,
please help to merge the pull request.
thank you very much!

New Rewrite Rules for MGKB

---

comein/.htaccess

avoid github conflicts, temp redirect

temp redirect

---

ro/.htaccess
ro/crate/.htaccess
ro/doi/.htaccess

Also split into subfolders for `/ro/crate` and `/ro/terms`

Add RO-Crate DOI redirects

---

iSeeOnto/.htaccess
iSeeOnto/readme.md

Redirects for ontology files being developed by the iSee project.

redirects for iSeeOnto files

---

concrete/.htaccess
concrete/readme.md

this is a work in progress Ontology for concrete

add concrete ontology

---

jp-cos/.htaccess
jp-cos/README.md

This is a permanent identifier for Course of Studies of Japanese education system.

add jp-cos permalink

---

EVENTSKG-Dataset/.htaccess
SemSur/.htaccess
seo/.htaccess

due to server updates, all links of these ontologies are updated.

update links of semsur, seo and eventskg

---

midas-catalog/.htaccess
midas-catalog/README.md

initial creation for midas-catalog redirect

Creation of midas-catalog rewrite rule

---

roh/.htaccess

Two new ontologies have been mirrored at the ROH repository.

Adding new ontologies mirrored at ROH repository

---

faircookbook/.htaccess

Thanks again!
link to project readme incl. list of maintainers: https://github.com/perma-id/w3id.org/blob/master/faircookbook/README.md

faircookbook: adds FCB055

---

requirement-ontology/.htaccess
requirement-ontology/readme.md

Changed the name of the server hosting the content.

changed from demo server to data.dnv.com

---

iadopt/.htaccess
iadopt/ont/.htaccess

added some more redirects to make versionIRIs work
(and fixed some minor stuff on the way)

iadopt: adding support for versionIRIs

---

tinyml-schema/.htaccess
tinyml-schema/Readme.md

Hi there,
We want to add a permanent link to our tinyml ontology. Could you please grant our pull request? Thank you very much.
Cheers,

add tinyml schema link to w3id

---

cwl/.htaccess

Added a new link for the 2022 CWL weekly meetings.

Update link to CWL meeting minutes

---

isample/.htaccess
isample/README.md
isample/vocabulary/.htaccess
isample/vocabulary/material/.htaccess
isample/vocabulary/material/0.9/.htaccess
isample/vocabulary/material/0.9/README.md

New set of redirects for the iSamples project. URIs for sample registration, metadata schema,and vocabularies. This is initial test for one vocabulary

set up test redirects for material vocabulary using w3id

---

isample/vocabulary/material/.htaccess

add redirects for pylode view and turtle download

redirects for pylode view and turtle download

---

isample/vocabulary/sampledfeature/0.9/.htaccess
isample/vocabulary/sampledfeature/0.9/README.md
isample/vocabulary/specimentype/0.9/.htaccess
isample/vocabulary/specimentype/0.9/README.md

the version number is getting rewritten twice, so copy what's in material vocabulary,which is working

add folders for version number

---

iddo/.htaccess
iddo/readme.md

Added entry for iddo

---

td/README.md

@noelmcloughlin -- Please approve.

fix punctuation and typo in README

---

mdo/.htaccess
mdo/readme.md

We migrate the repository to our organization account.

Update MDO pages repository

---

fip/.htaccess
fip/README.md

For FAIR Implementation Profiles and linking to projects in FIP Wizard.

Add entry for FIP

---

locolligo/.htaccess
locolligo/CAMPOP-Places/.htaccess
locolligo/CAMPOP-Places/README.md
locolligo/README.md

I'm not sure that I have the .htaccess redirects properly configured - please check!
Thank you for this invaluable service.

Create locolligo and locolligo/CAMPOP-Places identifiers.

---

rd-fairmetrics/.htaccess

Hello,
We added new FAIR metrics and in this PR we added redirect rules for those metrics.
Thank you.

New metrics are added

---

rd-fairness-tests/.htaccess

Hello,
We added new API to check FAIRness of a resource for F4. In this PR we created redirect rule for this new API.
Thank you

New metric test api added

---

fdt/.htaccess
fdt/README.MD

Creation of the FDT (FAIR Data Train) prefix

Create fdt prefix

---

ga4gh/.htaccess

Adding new link for refget minutes for 2022

Update GA4GH .htaccess for 2022

---

rd-fairness-tests/.htaccess
rd-fairness-tests/README.md

Hello,
I added redirect for new RD tests.
Thank you,
Rajaram.

New RD tests added
