ontolink/.htaccess

Previously, only the exact match was forwarding and the capture group
was not getting passed to the 302 URL.
Apologies for the second PR. I thought this was working last time, but I obviously didn't check it properly. I still don't understand why it wasn't working last time!

Now correctly forwards the capture.

---

openbadges/.htaccess

The change to the ./v1 redirect here incorporates the previous version and has been tested by @dlongley . These updates should be ready to go. We'll follow up shortly to update these to HTTPS.

Add Open Badges spec and context, incorporating legacy v1 context

---

env/.htaccess

We are publishing some environmental vocabularies, currently hosted at environment.data.gov.au 
We expecting to spin off some of the more widely used vocabularies to a separate service, so would like to reserve the /env/ project for these. 
In the short-term the redirect is to environment.data.gov.au/def but this is likely to change in the medium term.

Initial commit - redirect from w3id.org/env to environment.data.gov.au/def

---

verb/.htaccess

To my understanding this will require using
```ttl
@prefix verb: <https://w3id.org/verb/#> .
```
```json
{
"@context": {
"verb": "https://w3id.org/verb/#"
}
}
```
And one can **NOT** use it without *slash* just before *hash* (fragment) - `https://w3id.org/verb#`

adding verb (related to ActivityStreams and xAPI)

---

lob/.htaccess

This is meant to redirect with code 303 from e.g. w3id.org/lob/concept/1234 to www.ligatus.org.uk/lob/concept/1234

Add lob, Language of Bindings Thesaurus

---

lob/.htaccess

Apologies, the redirection needs to be to www.ligatus.org.uk/lob and not www.ligatus.org.uk .

Corrected redirection to lob

---

clipc/.htaccess
clipc/README.md
clipc/meetings/.htaccess

Hello,
I would like to add a CLIPC domain. CLIPC is a collaborative project building a climate information platform. Further details are on www.clipc.eu. Our project web site will evolve during the project, we need the permanent URLs to provide durable references to reference documents (reports etc).

Adding CLIPC domain

---

.travis.yml

`> &2` didn't work, but `>&2` does.. Bash is fun.

fix bash-syntax in travis.yml error output

---

valueflows/.htaccess

hey folks. :cat:
for context, [Value Flows](https://github.com/valueflows/valueflows) is a *work in progress* vocab for "resource planning and accounting within fractal networks of people and groups", [we're keen for a permanent identifier with w3id.org](https://github.com/valueflows/agent/issues/23).
thanks!

add initial .htaccess for Value Flows vocab

---

lio/.htaccess
lio/README.md

Our old namespace was http://purl.org/net/lio#. We do not trust purl.org any more.
Here is the version of the owl file that will be used after the switch: http://www.imagesnippets.com/lio/lio_new.owl
Michael Brunnbauer on behalf of Margaret Warren and Pat Hayes.

Requesting a namespace for the Lightweight Image Ontology (LIO)

---

oc/.htaccess

This space should be used for guaranteeing the persistence of the entities of the Open Citations Corpus -- see:
- http://www.nature.com/news/publishing-open-citations-1.13937
- http://www.emeraldinsight.com/doi/abs/10.1108/JD-12-2013-0166

New space for OCC

---

people/r/.htaccess

Reverts perma-id/w3id.org#203.
This wasn't the correct way to do a single person redirect. They want to add an entry to people/.htaccess instead.

Revert "Redirects for Pierre Reimertz"

---

vsat/.htaccess
vsat/README.md

Please consider merging this into w3id.org and giving my linked data vocabularies a permanent place to call home on the web. 
There is not much to see now, but I will be to adding vocabularies for network management. The destination domain is hosted by godaddy and should respond to a get request at <http://asdfghjkl1234567.com/linked/index.html> (I know, not a catchy domain but it was available and I can remember it)
An actual test vocabulary (not my vocabulary, but a placeholder) can be downloaded from <http://asdfghjkl1234567.com/linked/vocab/aggregate/0/aggregate.ttl> and if I get my wish also from http(s)://w3id/vocab/aggregate/0/aggregate.ttl soon as well though I'll probably refactor the URLS later to make them less clunky.
Many thanks
Alan

redirect for linked data vocabularies

---

lindt/.htaccess
lindt/README.md
multidimensional-quantity/.htaccess
multidimensional-quantity/README.md
sparql-generate/.htaccess
sparql-generate/README.md

Short description of the changes:
**lindt** - The Linked Datatypes Specification and Library. 
Redirects to http://ci.emse.fr/lindt/
website for paper that will be presented at ESWC 2016:
Maxime Lefrançois, Antoine Zimmermann, [Supporting Arbitrary Custom Datatypes in RDF and SPARQL](http://ci.emse.fr/lindt/LefrancoisZimmermann-ESWC2016-Supporting.pdf), In Proc. Extended Semantic Web Conference, ESWC, May 2016, Heraklion, Crete, Greece
**sparql-generate** - SPARQL-Generate.
Redirects to http://thesmartenergy.github.io/sparql-generate-jena/
Consists of:
- An extension of SPARQL 1.1 - that enables to interpret RDF Literals as RDF Graphs. 
- A protocol - that enables a server (resp. client) to tell the client (resp. server) how the content+mime it sends (= a RDF Literal) may be interpreted …

adding redirections to ontologies and projects from the thesmartenergy organization 

---

voldemortkg/.htaccess
voldemortkg/README.md

This PR adds a permanent URL to a new knowledge graph and its dataset. Using a permanent URL is a requirement of ISWC 2016 call for papers.
We will expand the content of the homepage ASAP, the submission deadline being tomorrow.

Add voldemort knowledge graph

---

actionizekb/.htaccess
actionizekb/README.md

This PR adds a permanent URL to a new knowledge base and its dataset. Using a permanent URL is a requirement of ISWC 2016 call for papers.
We will expand the content of the homepage ASAP, the submission deadline being tomorrow.

Add actionize knowledge base

---

la/.htaccess
la/readme.md

This second attempt at a PR is in a single commit. It adds a basic redirect of permanent IRIs of the form
https://w3id.org/la/jisc/extensions/courseArea
https://w3id.org/la/jisc/extensions/applicationType
to
https://github.com/jiscdev/xapi-vle/blob/master/vocabulary.md#courseArea
https://github.com/jiscdev/xapi-vle/blob/master/vocabulary.md#applicationType
These IRIs are used for an xAPI based vocabulary used in learning analytics JSON statements used by a consortium of vendors and universities.

Single commit

---

la/.htaccess

Current rule rewrites "#" as "%20". Adding the NE flag should fix that.

Update htaccess to preserve fragment identifier

---

oc/.htaccess

The redirect action has been extended so as to handle all the URLs having base w3id.org/oc.

Updated the redirect with more URLs

---

eis/vocabs/.htaccess

To allow content negotiation of the vocabulary, we need to redirect the w3id URI to the online documentation of FuhSen.

Link to FuhSen ontology online documentation

---

aufx/.htaccess

otherwise you get 404 Not Found (e.g. with wget)

aufx: Add fall-through if Accept is missing

---

chainpoint/.htaccess
chainpoint/README.md

I had used the 'v1' term in error in my previous commit. The context we will be publishing is actually the second version of our specification, and thus needs to be represented as 'v2' throughout.

Updated 'chainpoint' to use proper version number

---

sfs-ontology/.htaccess

Need a redirect persistant uri for my ontology. 
I have created html description of my ontology on http://semantic-file-system-ontology.sf.net/index.htm . My owl ontology is uploaded to http://semantic-file-system-ontology.sf.net/sfs-ontology.owl. 
I want to redirect "text/html" requests to index.htm  and "application/rdf+xml" requests to sfs-ontology.owl.

Need a redirect persistant uri for my ontology

---

ontop/.htaccess
ontop/README.md

added ONTOP - Ontology Platform redirecting to http://ci.emse.fr/ontop/
Project ONTOP includes:
- a STTL aka SPARQL-Template transformation that enables to automatically generate an HTML documentation for any ontology;
- a Maven plugin that automatically controls the quality of the ontologies to be published;
- a Maven project that serves the ontologies and other resources following the Web architecture design principles.

added ONTOP - Ontology Platform redirecting to http://ci.emse.fr/ontop/

---

blockcerts/.htaccess
blockcerts/README.md

Changed 'context' rewrite to 'v1': I want blockchain certificates to be explicit about which version they are using, because the  normalization (and hash) changes with JSON LD changes.
Also include wildcard match.
w3id.org team: This should be all my changes for a while. Thanks for all your help!

Improve context references

---

cmip6dr/.htaccess
cmip6dr/README.md

Corrected one URL (the initial www had been omitted, which worked in the past and is now failing). Also corrected README.md

Correct faulty URL for www.earthsystemcog.org

---

openbadges/.htaccess

Open Badges has released a new context file as part of our [specification](https://github.com/openbadges/openbadges-specification/pull/99). This will add `https://w3id.org/openbadges/v2` as a redirect to the file once it is published. Thanks!
Nate Otto
Director of Technology, Badge Alliance
badgealliance.org

Add new openbadges context path

---

akn/.htaccess
akn/README.md
ido/.htaccess
ido/README.md

This pull request would add in the main repository two permanent ID spaces for two distinct projects, i.e.:
- /akn: it is the space dedicated to the entities related to the AkomaNtoso project;
- /ido: it is the space dedicated to a specific ontology, i.e. the Imperial Data Ontology, that is used for describing the selling data related to the fast-fashion domain.

Request of permanent id spaces for AkomaNtoso and Imperial Data Ontology

---

laas-iot/.htaccess
laas-iot/README.md

Dear w3id.org administrators, 
I would like to issue this pull request in order to give the LAAS open data project a permanent ID, that also covers the vocabulary used to annotate the distributed data. Redirections and content negociation is performed on our side.
Best regards, 
Nicolas Seydoux

Addition of a new redirection entry to serve the LAAS open data project

---

isil/.htaccess

there is now a permalink on italian catalog of libraries
http://anagrafe.iccu.sbn.it/opencms/opencms/eventi-e-news/Da-oggi-sono-disponibili-i-permalink-alle-schede-di-dettaglio-delle-biblioteche./

update rewrite /isil for IT- now permalink available

---

UN/.htaccess
UN/README.md

The .htaccess file has been changed so as to serve the appropriate representation for ontologies according to the particular request sent by a client. In addition, the redirection for UNDO has been added.

Added handling of redirect for ontologies

---

openbadges/.htaccess
openbadges/README.md

Since January 2017, the Open Badges spec is maintained by IMS Global
Learning Consortium. The spec & context URLs are therefore changed as
we turn the openbadgespec.org site into a redirect to imsglobal.org.

Update to new imsglobal.org location, add README

---

openbadges/.htaccess

Due to unforeseen CORS policy issues on the new site, we need to revert
some of the redirects.

Revert v1 and v2 URLs

---

ibp/.htaccess
ibp/README.md

Dear all
it would be great to add the identifier https://w3id.org/ibp/ .
We will to publish a couple of OWL ontologies related to building automation systems and control logic. We followed the guidlines as expressed in https://github.com/perma-id/w3id.org/blob/master/README.md to file a pull request.
Instead of filing an ID for every ontology we rather file https://w3id.org/ibp/  and have submodule ontologies reference below that similar to [seas](https://github.com/perma-id/w3id.org/blob/master/seas/README.md). The project will continue in the next couple of years and  will align with work of W3C Linked Building Data Community Group [link](https://github.com/w3c-lbd-cg).
We are happy to adjust our files if required.
Best
Georg

Add permanent identifier w3id.org/ibp/

---

datafabric.cc/README.md
datafabric.cc/ontologies/.htaccess

+ Root folder for PURLs related to DataFabric.cc projects,
+ PURL for the FTS ontology.

DataFabric.cc's root folder. FTS ontology PURL

---

cwl/.htaccess
cwl/README.md

Note that these are not live yet on https://view.commonwl.org/
See common-workflow-language/cwlviewer#146 and https://github.com/common-workflow-language/cwlviewer/wiki/Permalinks

Added CWL permalinks

---

un/.htaccess

The .htaccess has been modified so as to provide a correct mechanism for the content negotiation. 
When accessed by means of a browser (i.e. requesting HTML as format), the current version of UNDO redirects to the official UN document describing the ontology, available at https://unsceb-hlcm.github.io/onto-undo/index.html. Any other request (i.e. different formats and version IRI of the ontology) will be redirected to the specific file contained in the repository.

Fixed .htaccess for versions and sources

---

afo/.htaccess

The Audio Feature ontology framework has been relocated to Github pages 
https://w3id.org/afo/onto/1.1# -> https://semantic-audio.github.io/afo/
https://w3id.org/afo/vocab/1.1# -> https://semantic-audio.github.io/afv/

The Audio Feature Ontology relocation to github pages

---

cedar/.htaccess
cedar/README.md

We are adding the ability to cite scientific data from the CEDAR Madrigal database, and would like to allow those citations to have the option of changing the server hostname.  Thanks - Bill Rideout (brideout@mit.edu)

redirects to go from w3id to cedar.openmadrigal.org

---

mapvowl/eval17/.htaccess
mapvowl/eval17/README.md
rml/editor/eval17/.htaccess
rml/editor/eval17/README.md

For the evaluation of MapVOWL and the RMLEditor we would like to use w3id.org URLs. This in order to have stable URLs as part of our research publication.

add URLs for MapVOWL and the RMLEditor

---

ldpdl/.htaccess
ldpdl/README.md

Added identifier for LDP-DL (http://opensensingcity.emse.fr/ldpdl/), which is a language for the description of Linked Data Platforms following the LDP W3C Recommendation (https://www.w3.org/TR/ldp/)

LDP-DL added

---

ibp/.htaccess
ibp/README.md

We revised the rewrite rules of w3id.org/ibp
Added now rewrite rules dependend on the content type (ttl/html)
Also added rules for each hosted ontology

Revision of w3id.org/ibp

---

spar/.htaccess

The htaccess has been changed in order to handle properly SPAR Ontologies in the new GitHub repository.

Handling of SPAR Ontologies in GitHub

---

spar/.htaccess

No regex grouping was enabled in the redir block, and it does not work properly. As a future work, one should consider to handle also the redirection in a smoother way - i.e. without so many 303 redir, but it is something that should be tested in advance.

Corrected mistake in htaccess in redir block

---

ac-ontology/.htaccess
ac-ontology/README.md

This add redirection from https://w3id.org/ac-ontology/aco to
http://www.audiocommons.org/ac-ontology/aco performing content
negotiation.
That’s the ontology we designed in the context of the European project
Audio Commons (audiocommons.org).

Add redirection to Audio Commons ontology

---

ftm/.htaccess
ftm/readme.md

This is the RDF version of the schema used in [aleph](https://github.com/alephdata/aleph) and by [OCCRP](https://occrp.org) for modeling entities of interest in money laundering investigations and other investigative journalism projects.

Follow The Money ontology

---

.travis.yml

- Many URLs fail to check, causing confusion for PRs.
- This omits many of those URLs that failed during local testing.
- Additionally, the apache setup on travis is broken.  It gets a SIGTERM.  Just disabling it all for now until fixed.

Disable broken linkchecker.

---

ibp/.htaccess

Revision of htaccess to improve the redirect to the HTML code by adding https://htmlpreview.github.io/?

Adding improved visualiation of HTML Ontology documentation

---

moeebius/.htaccess
moeebius/README.md

Dear w3id.org-team,
we would like to register a new permanent identifier under the w3id.org service for ontologies developed under the MOEEBIUS H2020 project.
> https://w3id.org/moeebius/
The identifier will be used in the ontologies developed with this project. The identifier needs to be permanent as the ontologies developed are supposed to be available and accessible forever.
Best
Georg

Establishing a permanent namespace for ontologies developed in the MOEEBIUS H2020 project

---

lsd/.htaccess

PR #988 seemed to contain a mistake in the redirect definition, this fixes that.

Fix LSD redirect failing

---

DockerPedia/.htaccess
DockerPedia/README.md

added DockerPedia persistent URI: https://dockerpedia.inf.utfsm.cl

added DockerPedia persistent URI

---

people/matt/.htaccess

Example: before this change, this URL produces 404:
```
https://w3id.org/people/matt/Dorset2017-08/
```
After the change, a document is found.

Now redirects full path, so longer URLs can go deep into the website

---

arm/.htaccess

Update to `htaccess` for https://w3id.org/arm to change documentation paths

arm: change path for lode docs

---

arm/.htaccess

Apologies for a second change in a few days but we want to rationalize the namespace for activity ontology as we wrap up the first phase of this project. Changes in targets _are_ already live, e.g. https://w3id.org/arm/activity/ontology/ will redirect (in browser) to  https://ld4p.github.io/arm/activity/ontology/0.1/activity.html
(re. https://github.com/LD4P/arm/issues/125#issuecomment-400024986)

arm: move activity ontology

---

sdc/.htaccess
sdc/readme.md

https://w3id.org/sdc/ontology is the namespace for the ontology based on La Syntaxe du Codex for the syntactic description of manuscripts.
The Ontology is under development at https://github.com/BetaMasaheft/SyntaxeDuCodex.

Added Readme and redirect for Syntaxe du Codex Ontology

---

squirrel/.htaccess

redirection has been updated to dice group squirrel repository
vocabulary redirection changed to old location at github.com/varunmaitreya/squirrelontology/

redirection for dice group repository

---

disk/.htaccess

The Neuro Ontology was renamed to the ENIGMA Hypothesis Ontology in the GitHub repository for DISK Ontologies

neuro to enigma_hypothesis

---

tree/.htaccess

Apparently the CDN version of rawgit will never update the file, even if it changed on git. Updated the rawgit to the development version. Will re-locate to my own  server once the ontology is in a more advanced state (working on implementations atm).

Updated temporary URI for tree ontology

---

jp-textbook/.htaccess

This adds a content negotiation rule for "text/turtle".
raw data example:
https://jp-textbook.github.io/%E5%B0%8F%E5%AD%A6%E6%A0%A1/2010/%E7%AE%97%E6%95%B0/201.ttl

add redirect rule for text/turtle on jp-textbook

---

cwl/.htaccess

.. after which https://w3id.org/cwl/prov/0.3.0 should redirect to https://github.com/common-workflow-language/cwlprov/tree/0.3.0

Generalize CWLProv redirect for semantic versioning

---

loupe/readme.md
loupe/vocab/.htaccess

w3id IRIs for publishing the Loupe vocabulary.
The raw vocabulary files are stored in a Github repo.
[loupe-ontology](https://github.com/nandana/loupe-ontology)
This commit includes the .htaccess files for content negotiation and redirection.

w3id IRIs for publishing the Loupe vocabulary.

---

lindt/.htaccess

https certificate for our server only applies to ci.mines-stetienne.fr , not to the alias ci.emse.fr

change http to https for certificate reasons

---

cityspin/.htaccess
cityspin/README.md

We added a permanent identifier for CitySPIN, http://cityspin.net/, an Austrian research project.

Add permanent identifier for the CitySPIN project, http://cityspin.net/

---

fair/.htaccess
fair/README.md

For the FAIR Guiding Principles (https://doi.org/10.1038/sdata.2016.18), linking to GO-FAIR (https://www.go-fair.org/). Links to vocabularies will follow later.

Add 'fair' entry

---

pc/.htaccess
pc/README.md

To be used as an XML namespace for the additions to the RSS podcast spec used by podchaser.com

Added Podchaser redirect (pc namespace)

---

GDPRov/.htaccess
GDPRtEXT/.htaccess

Silly mistakes - the previous commit had incorrect URIs which were detected only after the commit was pushed (live).

fixed incorrect URI links in previous update

---

data2services/.htaccess
data2services/README.md

Add data2services folder with .htaccess and README.md
Used to resolve URI used in the Data2Services project (http://github.com/MaastrichtU-IDS/data2services-pipeline). It redirects https://w3id.org/data2services to http://graphdb.dumontierlab.com (a GraphDB triplestore)

Add data2services namespace

---

data2services/.htaccess

Redirect to https://w3id.org instead of http://w3id.org

Fix URL redirect in data2services htaccess

---

dot/.htaccess
dot/readme.md

Pull request for adding a permanent identifier for the Damage Topology Ontology (dot) to w3id.org. 
The Damage Topology Ontology (DOT) allows the definition of damage representations and their relations with other damages and affected construction components.

Adding permanent identifier for Damage Topology Ontology (dot)

---

arco/.htaccess

The modified rules reflect the change occurred to the namespace used
for identifying the ontologies of the ArCo project.

Namespace change.

---

arco/.htaccess

The redirect rule allows to access the test cases defined for
validating the ontology modules available within the ArCo ontology
network.

Added rule for test cases

---

gicentre/.htaccess
gicentre/readme.md

Am working on disaster ontologies and ontology patterns created by the GICentre members .this service will allow repository redirecting. will be glad if you can help

Re: Direction service for ontologies designed for hazard assessment

---

idsa/.htaccess

It seems like the context-dev.jsonld redirect link is processed in a way that breaks encoding. Replacing '%2F' with native slashes should fix it. Sorry for the inconvenience.

fix broken redirect

---

hclscg/.htaccess
hclscg/README.md

I did my best to check the links locally but had trouble getting linkchecker to work. Hopefully, these resolve. The community group not link will move from my pitt server to to the W3C community group page once it the final version is published at which case, I will do another pull request. Thanks for your help.

added w3id config for the HCLSCG and its first community group report

---

rec/.htaccess

Note -- this is not an actual live API (that would be stupid and probably wasteful), just a redirect to API documentation.

RealEstateCore: added graph API 2.3

---

ga4gh/.htaccess

Previous link not translated to Google Doc link correctly

Correct for Beacon API URL

---

saro/.htaccess
saro/README.md

The namespace of the ontology (available at the rewrite rule URI) will be changed to:
w3id.org/saro#

SARO Ontology permanent namespace

---

transmodel/.htaccess
transmodel/README.md

This Pull Request is a result of CEN TC278WG3 meeting at 2019-06-19. This group decided to make an official base URI for the Transmodel ontology at W3ID. I was given the task to create the URI.

Added the transmodel ontology base URI as a placeholder

---

bot/.htaccess

updated htaccess according to https://w3id.org/mint/modelCatalog and https://w3id.org/omg to enable users to import BOT on the fly from Protégé (see issue https://github.com/perma-id/w3id.org/pull/1384)

updated htaccess of BPO

---

lode/.htaccess

Hi @davidlehn 
As discussed in https://github.com/perma-id/w3id.org/pull/1460, I've tested new rules again in a proper Apache testing space (i.e. http://earmark.sourceforge.net), and now it seems that everything works correctly. For instance, if you try
http://earmark.sourceforge.net/lang=it/imported/http://purl.org/spar/fabio
it will redirect to the correct service and generate the right HTML page. Thus, merging this request in w3id.org should work fine as well - once merged try
https://w3id.org/lode/lang=it/imported/http://purl.org/spar/fabio
that should behave like the previous call.

Handling of all the LODE calls via w3id.org URL

---

executionTechnique/.htaccess
executionTechnique/readme.md

This is a redirect for a w3id url we would like to use for our execution technique ontology, which is part of the efforts towards a general modelling of epigraphic documents.

new redirect for execution technique ontology

---

profileresourcerole/.htaccess
profileresourcerole/README.md

A URI for SKOS vocabulary Concepts for the roles that items within Profiles play with both `Resource Role` and `Profile` being defined within the [Profiles Vocabulary](https://w3c.github.io/dxwg/prof/).

/profileresourcerole/ README & redirects

---

gom/.htaccess
gom/readme.md

Hi!
This redirect contains a proposal for the registration of https://w3id.org/gom for the GOM or Geometry Metadata Ontology. Additional references can be found in the readme.
Best regards,
Mathias Bonduel

redirects for GOM ontology

---

fog/.htaccess
gom/.htaccess

Hi, I just updated the rules of two .htaccess files pointing to my repositories from 302 to 303 according to the recommendations in https://github.com/perma-id/w3id.org/pull/1514
Best regards,
Mathias

Updated .htaccess for GOM and FOG

---

cri/.htaccess
cri/README.md

CRI is an independant research association, and part of its activity will resort to the publication of vocabularies, hence the need of a permanent namespace.

Added CRI association namespace

---

obelisk/.htaccess
obelisk/README.md

This namespace is used for a simple vocabulary describing obelisks. This vocabulary is used as an example for a tutorial on https://solidproject.org/, and its publication under a permanent IRI is consistent with the good practices identified in said tutorial.

Added obelisk namespace

---

obelisk/.htaccess

The obelisk vocabulary uses a / namespace (as opposed to a # namespace, which is not sent to the server), so it is necessary to accept extended paths.

Updated the .htaccess to accomodate with the / namespace

---

ic/standards/.htaccess

Fix the IC-Docbook URL and add convenience package urls for PUPS 2019-SEP.

Update ic-Docbook and PUBS

---

digitalconstruction/.htaccess
digitalconstruction/Agents/.htaccess
digitalconstruction/BuildingAcoustics/.htaccess
digitalconstruction/BuildingMaterials/.htaccess
digitalconstruction/Contexts/.htaccess
digitalconstruction/EnergySystems/.htaccess
digitalconstruction/Entities/.htaccess
digitalconstruction/IndoorAirQuality/.htaccess
digitalconstruction/Information/.htaccess
digitalconstruction/OccupantBehavior/.htaccess
digitalconstruction/Processes/.htaccess
digitalconstruction/README.md

Hi, 
We are preparing a large ontology suite for digital construction, both for new construction and renovation projects. Since there are going to be a lot of internal imports between ontologies and our development is decentralized, it would be easier if we could import ontologies from permanent addresses at w3id.org/digitalconstruction.  
Currently there are only couple of ontologies published in the redirected addresses at digitalconstruction.github.io (Entities and Agents). Three others will be before the next week (Information, Processes and Contexts) and the rest five ontologies by mid January. All ontologies have been designed and initially formalized in OWL.
We are currently also discussing future research efforts that would utilize these ontologies. 
Best regards,
Seppo Törmä

Digital Construction Ontologies - Reorganization

---

irnerio/.htaccess
irnerio/README.md

**Name of the project:** Progetto Irnerio
**Description:** The core part of this project consists of digitizing and classifying the vast collection of legal and theological-philosophical codices making up the rare-books collection of the Reale Collegio di Spagna in Bologna: with this digital catalogue, built under the guidance of Professors Domenico Maffei and Andrea Padovani, not only can the fragile codices be readily accessed and studied, but their preservation for future use is guaranteed, too. The project - named for the primus illuminator of legal science studies in Bologna, the Italian jurist Irnerius - have been possible by the Collegio di Spagna that made its rare-books collection available. Funding for the project comes from the Fondazione Cassa di Risparmio in Bologna, and also …

New htaccess for Progetto Irnerio (Irnerio Project)

---

atomgraph/README.md
atomgraph/core/.htaccess
atomgraph/linkeddatahub/.htaccess
atomgraph/linkeddatahub/admin/.htaccess
atomgraph/linkeddatahub/admin/acl/.htaccess
atomgraph/linkeddatahub/admin/sitemap/.htaccess
atomgraph/linkeddatahub/apps/.htaccess
atomgraph/web-client/.htaccess

Under the `/atomgraph` namespace

Added redirects to AtomGraph's open-source project ontologies

---

dini-ag-kim/.htaccess
dini-ag-kim/README.md

As the old URIs were actually in use in some docs, I am adding redirects from the deprecated to the new namespace.

Add redirects from deprecated to new KIM namespace

---

kim/.htaccess

- Add generic redirect to GitHub pages as last rule
- Remove specific rules which are obsolete now
@acka47 please have a look at this. (It would allow for new DINI specs on GitHub without having to add a new w3id rule.)

KIM: Add default as last rule

---

trek/.htaccess
trek/README.md

Add the trek namespace. Used by a clinical data KG for the NIH NCATS Translator project
Redirect to https://trek.semanticscience.org

Add the trek namespace

---

d2s/.htaccess
d2s/README.md

Change the redirect in d2s/.htaccess to point to http://trek.semanticscience.org. A web UI to browse SPARQL endpoints for the Data2Services project
And edit README to add short description of the namespace

Change redirect in d2s/.htaccess

---

fraunhofer/Readme.md
fraunhofer/lighthouse-projects/evolopro/.htaccess
fraunhofer/lighthouse-projects/evolopro/Readme.md

I would like to add a namespace for ontologies of Fraunhofer institutes.
A first use for this namespace are our ontologies for the lighthouse project EVOLOPRO.

Add namespace for Fraunhofer

---

security/.htaccess

Stop redirecting to web-payments and use: https://w3c-ccg.github.io/security-vocab/ to define security vocabulary

Fix w3id.org/security context links

---

fraunhofer/lighthouse-projects/evolopro/.htaccess

I didn't think it through when I based my `.htaccess` on other examples. I would always like to redirect the request, not just when the client sends the correct `Accept` header.

Redirect for any accept header

---

dcso/.htaccess
dcso/readme.md

Hi.
I'm a relative newbie to this. I was told to resort to the w3id to get a persistent identifier for the ontology that I've been working on.
I've changed the namespace in the ontology to https://w3id.org/dcso#
I've tried to do my best to create a .htaccess file that points to the github location of the latest .owl file.
I've also added the version of the ontology as an annotation to the .owl file.
Any help spoting potential errors is much appreciated. As well as an approval of the pull request :)
Best,
JC

Adding a w3id pid to the dcso ontology

---

mdo/.htaccess
mdo/readme.md

This is for redirecting w3id urls to Materials Design Ontology.

Add redirection for Materials Design Ontology

---

spice/.htaccess

The htaccess file to handling all the IRIs of the terms included in the ontologies developed during the SPICE H2020 project (https://cordis.europa.eu/project/id/870811), started 1 May 2020.

Creation of htaccess for SPICE H2020

---

amlo/.htaccess

Now redirects to gitlab pages to allow better serving of mime types and better perrformances

Updated .htaccess

---

digitalconstruction/Activities/.htaccess
digitalconstruction/EnergyEfficiency/.htaccess
digitalconstruction/Lifecycle/.htaccess
digitalconstruction/Variables/.htaccess

As a result of refactoring and refinements on digital construction ontologies, we would need to create redirects to modules Activities, EnergyEfficiency, Lifecycle, and Variables. 
- Seppo

Digitalconstruction: redirects to new ontology modules

---

urban-iot/.htaccess
urban-iot/README.md

Urban IoT Ontologies designed to support the integration and pubblication of data from different service providers operating IoT devices in an urban area. The ontologies were developed for the Municipality of Milano (Italy), but they are generic and can be applied to any other city.

Add urban-iot ontologies

---

ecsel-dr-sn-SSP/README.md
ecsel-dr/README.md

Our ontology, the Digital Reference moved from the Fraunhofer server https://vocol.iais.fraunhofer.de/ecsel-dr/ to a new server hosted by TIB http://ontology.tib.eu/dr/.
The following changes were therefore made:
- Update the rewrite rule to point to the new location in the .htaccess file
- Update the readme to include the new location
- Updated the responsible person and github as the old responsible left the company

Update dr information

---

hdgi/.htaccess

This will add the following URL redirections to https://w3id.org/hdgi
1. https://w3id.org/hdgi/v0.1 ->  https://w3id.org/hdgi
2. https://w3id.org/hdgi/mappings-apis -> GitHub repo
3. https://w3id.org/hdgi/mappings-docs -> GitHub repo

Add three additional redirections to w3id.org/hdgi

---

demeter/.htaccess

I logged the requests from Protege (Mac). It tries multiple times using two different requests, with the headers below. So, no turtle is even considered, and it seems text/html has higher weight than text/turtle. see issue: https://github.com/protegeproject/protege/issues/973 . In meantime, adding rdf+xml sending to ttl to try make it Protege to load.
accept: 'application/rdf+xml, application/xml; q=0.7, text/xml; q=0.6, text/plain; q=0.1, /; q=0.09', 'accept-encoding': 'xz,gzip,deflate', 'user-agent': 'Java/1.8.0_121'
accept: 'text/html, image/gif, image/jpeg, *; q=.2, /; q=.2',

add rdf+xml request rule

---

security/.htaccess

@dlongley @tplooker @davidlehn @msporny This will allow us to start using security/v3 with "default" document loaders.
It will also help with automated linting / documentation tooling for properties that are not not in sec-v2.

Add redirect for security/v3

---

profile/.htaccess
profile/README.md

An update for the PID URI https://w3id.org/profile/* due to a new back-end system change.

update to point to ProfCat

---

fraunhofer/Readme.md
fraunhofer/lighthouse-projects/evolopro/.htaccess
fraunhofer/lighthouse-projects/evolopro/Readme.md

Hi,
I will unfortunately leave the Fraunhofer organization at the end of September. Therefore, I will also delete my Fraunhofer-specific GitHub account.
I improved our CI pipeline to directly publish the ontology files to GitLab pages, so that I can change the redirect from GitHub pages to GitLab pages.
Furthermore, I replaced my contact information with that of my colleague who will continue this work.

Update redirects of ontologies in the Evolopro project

---

traceability/.htaccess
traceability/README.md

This PR adds support for the W3C CCG Traceability Vocabulary: https://w3c-ccg.github.io/traceability-vocab/
This work item is a collaboration among companies working with Decentralized Identifiers, Verifiable Credentials and JSON-LD as they relate to global supply chain traceability.

Add traceability vocab

---

openeduhub/.htaccess

I added a redirect to point to our rdf definitions of used terms in openeduhub project.

added redirect to term specification

---

nanoweb/.htaccess
nanoweb/readme.md

NanoWeb is a free public web application for accessing nanopublications. To this aim, w3id permalinks are the best fit for a stable and reliable access.

Pull request for NanoWeb web application

---

urban-iot/.htaccess

Fix rewrite rules for urban-iot modules.
Repo ref: https://github.com/Comune-Milano/ontologie-iot-urbani
cc @Comune-Milano
@dgarijo my apologies, now it should work. Updates PR previously merged https://github.com/perma-id/w3id.org/pull/1915.

Fix urban-iot rewrite rules

---

um/.htaccess
um/README.md

Add `um` folder for Maastricht University ontologies and knowledge graphs redirections (Cross border mobility legal ontology redirection added)
* [**CBCM ontology**](https://github.com/MaastrichtU-IDS/cbcm-ontology/) redirection added at https://w3id.org/um/cbcm/eu-cm-ontology
* An OWL ontology to define terms from EU company law that are relevant for cross-border mobility of EU companies. 
* Knowledge graphs for the **Institute of Data Science**
* [SHACL Shapes registry](https://github.com/MaastrichtU-IDS/shapes-of-you) at https://w3id.org/um/ids/shapes
* [IDS Projects](https://github.com/MaastrichtU-IDS/projects) at https://w3id.org/um/ids/projects
* Default redirection to https://maastrichtuniversity.nl

Add um folder for Maastricht University ontologies

---

um/.htaccess

Fix Maastricht University .htaccess redirection to CBCM ontologies (was overwritten by the default redirect)

Fix Maastricht University .htaccess redirection

---

con-tax/.htaccess
con-tax/components/aat-arch/.htaccess
con-tax/components/aat-furn/.htaccess
con-tax/components/aat-mep/.htaccess
con-tax/damages/mwv/.htaccess
con-tax/materials/aat-mat/.htaccess
con-tax/properties/bhp/.htaccess
con-tax/properties/cp/.htaccess
con-tax/readme.md
con-tax/tasks/mwv/.htaccess
con-tax/zones/aat-buildingSites/.htaccess
con-tax/zones/aat-buildings/.htaccess
con-tax/zones/aat-spaces/.htaccess
con-tax/zones/aat-storeys/.htaccess
con-tax/zones/et-buildings/.htaccess

Hi,
I've added a series of redirects, incl. content negotation, to a set of new OWL ontologies and their HTML documentation from Widoco. 
I assumed that it's correct to add a single working .htaccess file in subfolders to arrange redirects per subpath. I reused one of my older .htaccess files from https://w3id.org/gom and adapted it per new ontology. Unfortunatly, I'm currently unable to test this on Apache, so please inform me if I'm doing anything wrong! Here is an overview of what I try to accomplish:
con-tax => https://mathib.github.io/ConTax-ontology OR https://mathib.github.io/ConTax-ontology/ontology.ttl  OR ...
con-tax/components/aat-arch => https://mathib.github.io/aat-arch-taxonomy OR https://mathib.github.io/aat-arch-taxonomy/ontology.ttl  OR ...
con-tax/components/aat-furn => …

added con-tax ontology and related taxonomies

---

README.md
index.html

Apologies for destroying the linebreaks in the README - I auto-generated the Markdown from the recently updated index.html, while preserving the travis build note etc.

Align README and web index, add joining info

---

idsa/.htaccess
idsa/README.md

* (Haydar Akyuerek](https://github.com/HaydarAk) is a responsible maintainer of the IDSA subnamespace, which is now also reflected in the contact list.
* The ./idsa/metamodel path is used in the ids ontology, now also added to the redirection links for LOV combatibility.

IDSA: Adding new Contact and new Path Segment

---

csolink/.htaccess
csolink/README.md
csolink/biolinkml/.htaccess

Could you add w3id for csolink?
* `README`
* `.htaccess`
* `biolinkml/.htacces`s (because this is a common modeling language. Csolink is a fork of Biolink. , already hosted here).

feat(csolink): request w3id for csolink ontology

---

pgp/.htaccess
pgp/README.md

The purpose of this is to provide a template for context splitting associated with https://w3id.org/security vocab.
In the future, we would prefer to programmatically build security vocab, from smaller contexts like this one.

Add pgp vocabulary

---

security/.htaccess

This PR implements context splitting for https://w3id.org/security 
If this PR is merged, we should remove:
- https://w3id.org/pgp/v1
- https://w3id.org/jws/v1
- https://w3id.org/bbs/v1
And instead use:
- https://w3id.org/security/pgp/v1
- https://w3id.org/security/jws/v1
- https://w3id.org/security/bbs/v1
If this PR is not merged, the above will continue to work :)

Add subcontext splitting redirects

---

sssom/.htaccess
sssom/README.md

Hey all,
adding an idspace for https://github.com/OBOFoundry/SSSOM, a Simple Standard for Sharing Ontology Mappings (SSSOM) and its associated vocabs.
Thank you for considering!

Add SSSOM id space

---

dcc/.htaccess
dcc/README.md

This adds a perma-id `dcc` for the [Digital Credentials Consortium](https://github.com/digitalcredentials) to support stable URLs for our json-ld contexts, etc.
Please let me know if you have any questions/comments. Thanks for your help!

Add perma-id for dcc

---

twins/57fc5123-41af-4539-9d43-6403d6c3ab29/.htaccess
twins/57fc5123-41af-4539-9d43-6403d6c3ab29/readme.md
twins/readme.md

Created an identifier for the digital twin of an overhead crane, along with a folder "twins" which can be used for more twin IDs.
This is relates to an ongoing development of a digital twin framework that needs an external ID provider.

ID for the digital twin of a crane

---

tso/.htaccess
tso/README.md

We are developing a new ontology within the W3C linked building data community group ecosystem. The initial concept hast been published at <https://doi.org/10.1002/bapi.202000027> - now we would like to have a permanent identifier to reference in linked data applications.
If there are any questions, feel free to contact me: schluetter@e3d.rwth-aachen.de.

new redirect for TUBES system ontology (tso)

---

tso/.htaccess

unfortunately I was missing a slash to escape the "+" ...

TUBES system ontology (tso): fixed typo for content type redirection on application/ld+json 

---

um/.htaccess

Update redirection for https://w3id.org/um/cbcm/eu-cm-ontology to the OWL ontology file on GitHub

Update redirection for /um namespace

---

ga4gh/.htaccess

A number of URLs had a trailing slash in their rewritten form. This was being interpreted by the rewrite code as an extra slash. We have also moved the capture to a 0 or many wildcard to allow for URLs without an extension to be used. All `B` directives have been removed as they were causing the redirected strings to become broken and unresolvable. Redirects have been tested on a local `httpd 2.4` docker image and were working

Fix trailing slashes in /ga4gh .htaccess

---

carsa-loci/.htaccess
carsa-loci/README.md

A simple PID for a Linked Data system - CaRSA LocI.
These PIDs will be used to ensure that references to the CaRSA LocI system in papers and in catalogues don't break as the system gets handed from the builder (my company) to the operator (government department).

carsa-loci

---

linkml/.htaccess
linkml/README.md

Refactoring the biolink modeling language into linkml.  These links will serve both as reference and imports

Add LinkML -- the successor to biolinkml

---

gso/.htaccess
gso/README.md

test .htaccess to redirect ontology namespace URIs to turtle represenations or html generated by pyLODE and cached in the [Loop3d repository](https://github.com/Loop3D/GKM).  This will be updated to link to a release tag after testing

Create .htaccess and readme

---

gensc/.htaccess
gensc/README.md

We are requesting a new w3id redirect that will be used to redirect term and package URIs for the Genomics Standards Consortium.

add new directory for Genomic Standards Consortium

---

madmp/.htaccess
madmp/README.md

This namespace covers the documentation for the [Machine Actionable Data Managment Plans (maDMP) Common Standard](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard) developed by the [RDA DMP Common Standard WG](https://www.rd-alliance.org/groups/dmp-common-standards-wg)
This project is managed by the co-Chairs of the RDA DMP Common Standard WG:
* Tomasz Miksa (tomasz.miksa@tuwien.ac.at)
* Paul Walk (paul@paulwalk.net)
* Peter Neish (peter.neish@unimelb.edu.au)

added identifier space for /madmp/

---

gso/.htaccess
gso/1.0/.htaccess
gso/1.0/README.md

make sub folder for version 1, minor .0.  
Will update redirects for bug fixes. gso/1.0 uris redirected here; URI w/0 version number will go to github master for ttl and https://loop3d.github.io/GKM/ for html.

add redirects for version 1.0

---

gaia-x/.htaccess
gaia-x/README.md

Fix a bad sytax of regex capture group referencing (i.e., `$1` instead of `\g1`).

Fix redirects for Gaia-X

---

security/.htaccess

This PR is sadly necessary to handle cases where there is no JSON-LD support for standard NIST curves like P256.
I did my best not to trigger you @msporny but we can't possible support did:key without this, hopefully its acceptable.
My sense is that the LD Sec WG Suite imp guide will have a large section on best practices in this regard, and we can elaborate on the pro's and con's of `type` there.

Add multikey 2021

---

rail/topo/.htaccess

Github pages (where we redirect to) needs the "correct" file extensions to serve the ontologies with the correct MIME-Type.
This PR fixes redirects for the JSON-LD and RDF/XML versions of the ontology.

fix file extensions for JSON-LD and RDF/XML

---

vc-http-api/.htaccess

The route added in #2211 for `/vc-http-api/test-suite` is not working:
```
$ curl https://w3id.org/vc-http-api/test-suite/testResults.json
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.29 (Ubuntu) Server at w3id.org Port 443</address>
</body></html>
```
I expected instead a redirect to <https://w3c-ccg.github.io/vc-http-api/test-suite/testResults.json>.
I think this change (removing the leading slash) should fix it.
cc @OR13 @davidlehn

Fix /vc-http-api/test-suite/

---

67375/.htaccess

Right now https://w3id.org/67375/TSO/B4WKXG50-6 is redirecting on https://skohub.io/raphlap/test_so/heads/main/w3id.org/67375/B4WKXG50-6 (which gives a 404) instead of https://skohub.io/raphlap/test_so/heads/main/w3id.org/67375/TSO/B4WKXG50-6 (which works properly). Hopefully this commit should fix it ?
It seems that I hadn't completely understood how the redirection is working.

fixed another problem with landing URL

---

bot/.htaccess
bot/README.md

Dear w3id maintainers,
I just uploaded a new, tested version of the .htaccess file:
* added N3 serialization redirects
* versioned IRIs of BOT - tested to work with Protégé
The readme file is also updated, listing the new chairs of the [W3C Linked Building Data Community Group](https://www.w3.org/community/lbd/), including myself
Kind regards,
Mathias Bonduel

update BOT redirects and readme 

---

security/.htaccess

The target context file is being added in https://github.com/w3c-ccg/ethereum-eip712-signature-2021-spec/pull/22

Add EthereumEip712Signature2021 to security

---

yarrrml/.htaccess
yarrrml/README.MD

YARRRML's Matey is now publicly available on Github, created a w3id.org perma-id for it.

yarrrml: add repository link

---

wrfy/.htaccess
wrfy/README.md

The wrfy namespace it used for permalinks to digital receipts created by [warrify](https://warrify.com).

add wrfy namespace

---

hydra/.htaccess
hydra/README.md
hydra/extension/.htaccess

Draft until we're ready with the redirect targets (hydracg/extensions#7)

hydra: added rewrites for subpath extension/

---

uom/.htaccess
uom/README.md

Add entries for <https://units-of-measurement.org/> under `/uom/`.

Add 'uom' entry

---

arm/.htaccess

Update to `.htaccess` for https://w3id.org/arm to add redirects to HTML documentation that as missing for the 1.0 ontology and vocabularies. E.g. from https://w3id.org/arm/ontology/1.0/ to https://art-and-rare-materials-bf-ext.github.io/arm/v1.0/ontology/arm_1_0.html or https://art-and-rare-materials-bf-ext.github.io/arm/v1.0/ontology/arm_1_0.rdf depending on `Accept`. Also adds new vocab: https://art-and-rare-materials-bf-ext.github.io/arm/v1.0/vocabularies/relator.rdf

arm: add redirects for 1.0 HTML and relator vocab

---

csolink/.htaccess
csolink/README.md

This PR is required to update csolink because the github organisation was renamed (from csolink to linkmodel).
See https://linkmodel.github.io/csolink-model/

chore(csolink): gh-pages renamed to linkmodel.github.io

---

hospex/.htaccess
hospex/README.md

This namespace will represent a **vocabulary for hospitality exchange communities**.
It's created as a part of efforts of [Open Hospitality Network](https://openhospitality.network), which aims to decentralize/federate hospitality exchange.
The vocabulary is currently used e.g. in https://github.com/OpenHospitalityNetwork/ohn-solid

Add /hospex/ namespace - a vocabulary for Hospitality Exchange

---

workflowhub/.htaccess

Also `303 See Other` for latest version for any `#vocabulary` stuff
(Tip: Use a symlink to have both `*.json` and `*.jsonld` in GitHub Pages)

workflowhub/ Use .jsonld so GitHub Pages give right Content-Type

---

security/.htaccess

Add redirect for new context file being added here: https://github.com/decentralized-identity/EcdsaSecp256k1RecoverySignature2020/pull/24.
The previous (v1) context file redirect for this suite was added in https://github.com/perma-id/w3id.org/pull/2108 with some discussion. The proposed new context file (v2) aims to address feedback and follow best practices as much as possible for this existing signature suite.
Requesting review from namespace maintainers: @dlongley, @davidlehn, @msporny, @OR13

Add /security/suites/secp256k1recovery-2020/v2

---

traceability/.htaccess

Addresses https://github.com/w3c-ccg/traceability-vocab/issues/246

Update traceability vocab redirects

---

security/.htaccess

This PR reserves the `merkle-disclosure-2021` path under the security vocab.

Add Merkle Disclosure to Security

---

td/.htaccess
td/README.md

This PR add `td` namespace to `w3id.org`  for Toronto-Dominion (TD).

feat(id): add w3id.org/td namespace

---

hydra/extension/.htaccess

@alien-mcl, we don't have a dedicated "spec" page for the extensions in general so might actually go to GH instead and expand on the readme

hydra/extension redirect to GitHub

---

hydra/extension/.htaccess

https://hydracg.github.io/extensions.ttl and other do not exist, needed a proper path

hydra: incorrect redirect to RDF representation

---

fair-enough/.htaccess
fair-enough/README.md

Hi, I added the `fair-enough` namespace, to redirect to a service to evaluate how much a resource is FAIR (Findable, Accessible, Interoperable, Reusable) and provide persistent identifiers for the objects published in this service:  https://fair-enough.semanticscience.org
Thanks a lot!

Adding the fair-enough namespace

---

fair-genomes/.htaccess

FAIR Genomes resource files are now linked via the fairgenomes.org domain and renamed their extension from RDF to XML to fix browser MIME type issues.

Update fair-genomes .htaccess with new resource location

---

biocompute/.htaccess

Update .htaccess to remove `portal.aws.biochemistry.gwu.edu` links

Remove portal.aws.biochemistry.gwu.edu links

---

rail/topo/.htaccess

- redirect from generic to most recent version, currently v1.0
- fix redirects for ontology version URIs

rail/topo: add redirect to version ontology

---

tern/.htaccess

Fixes https://github.com/ternaustralia/ontology_tern/issues/116
- Update redirects to linkeddata.tern.org.au to prod version.
- Change links from raw.githack.com to GH pages.
- Add redirects for TERN Ontology's SHACL shapes.
Contact information: https://github.com/perma-id/w3id.org/tree/master/tern

/tern - update config

---

dpv/.htaccess

Added conditions to rewrite/redirect based on content type requested for
semantic web (rdf, etc.) files. Default rule is to serve HTML.
See w3c/dpv#32

dpv: content negotiation for rdf, ttl, n3, jsonld

---

dpv/.htaccess

Earlier commit incorrectly specified redirect path (i.e. /dpv instead of
/dpv/dpv). This has been fixed.
Addresses w3c/dpv#32

dpv: fix incorrect redirect path

---

rhonda/.htaccess
rhonda/README.md

This will provide access to Vocabularies and other data from the [Research in Historical legal Ordinances and Normatice DAta (RHONDA) Consortium](https://github.com/rhonda-org/PoliceOrdinances/wiki). For now, there is only one SKOS concept scheme.

Add rhonda redirection.

---

xapi/.htaccess

The base URLs and even rule structures changed and are currently not functioning.  These changes will restore basic functionality to our Profile Server application https://profiles.adlnet.gov replaces http://xapi.vocab.pub.  Not all are replaced yet as some functions are not yet working.

Necessary Changes for xAPI Profile Server

---

examode/.htaccess

added a new rule in the Horizon2020 ExaMode project ontology webpage to redirect to specific parts of the page exploiting URL fragments

added new rule for fragments

---

mpilhlt/.htaccess
mpilhlt/README.md
rg-mpg-de/.htaccess

After our institute's name has changed, I have opened a new top-level directory and made the old one (301-)redirect to it. The new one contains (302) redirections to the actual data (vocabularies).

Redirect to new institute URIs.

---

steel/.htaccess

Paths were redirected to the old personal repository instead of the new repository governed by the organisation.

Fix redirect from old personal repository to new org. repository

---

rg-mpg-de/.htaccess

Apparently there was a forward slash too many in the RewriteRule. Hopefully this fixes it. I cannot test it due to the project name being somehow automatically injected on the w3id.org instance, but I think this is how it should look like.

Hopefully fix redirection for former institute's name.

---

noria/.htaccess
noria/README.md

First release of the *noria* namespace with `README.md` and `.htaccess` files.
Redirect rules tested with the https://htaccess.madewithlove.com/ tool

Adding the noria namespace

---

obo/.htaccess
obo/readme.md
obpd/.htaccess
obpd/readme.md

Adding folders and access files to point to projects for Ontology for Building Objects and Ontology for Building Performance Data to the perma-id project.

Add OBPD and OBO to perma-id

---

mixs/.htaccess
mixs/README.md

Based on the requirement on https://github.com/GenomicsStandardsConsortium/mixs/issues/390 we want to add a folder for the genomic standards consortium MIxS community.
We want to deprecate the [gensc](https://github.com/perma-id/w3id.org/tree/master/gensc) folder we already have registered with w3id.
CC: @ramonawalls @turbomam

Add folder for GSC MIxS

---

mpilhlt/.htaccess

Sorry for the many PRs. I could not test locally how much of my problems was caused by the redirection status code and how much was caused by a wrong path matching regex. Turned out it was all the status code, and all the regex "improvements" needed to be reverted.
(I am redirecting to a Web API that accepts POST requests. But most clients - incorrectly - change the request method to GET when they run into a 302-redirect. 307 explicitly addresses this but I've only learnt about it during this debugging session.)
A big thank you for all your efforts!!

Fix 307 redirections for good (I've tested it now)

---

inrupt/.htaccess
inrupt/README.md

This is the initial request for an Inrupt namespace, intended to provide PURL services for a number of Inrupt resources (including vocabularies, example datasets, documentation, JSON-LD contexts, etc.).

New namespace for Inrupt resources

---

metadocencia/.htaccess
metadocencia/README.md

Requesting a namespace for the MetaDocencia project. See more at [https://www.metadocencia.org/en/](https://www.metadocencia.org/en/)

Add /metadocencia for the MetaDocencia project

---

nen2660/.htaccess
nen2660/README.md

This update adds a SPARQL endpoint queriable via w3id.org/nen2660/sparql
It also updates the norm reference, as it was published in 2022.
Thanks!

update(nen2660): add sparql endpoint, v2022

---

drone/.htaccess
drone/ont/.htaccess
drone/readme.md
drone/shapes/shacl/.htaccess

Adding support for [LANDRS](https://www.landrs.org) Drone Ontology/Shapes W3ID Redirects.

Adding LANDRS drone ontology w3id 

---

gensc/.htaccess
mixs/.htaccess

In the most recent MIxS standards technical meeting it was decided that we would not deprecate gensc as was presumed on PR #2697.
See the files changed for the new route mappings.
CC: @turbomam @ramonawalls

add route mappings for `gensc/mixs`

---

security/.htaccess

This PR changes the redirects for Json Web Signature 2020 from the W3C CCG to the W3C!

Change redirect target for sec/jws-2020

---

mpilhlt/.htaccess

Trying to get redirection of requests where the path contains urlencoded URLs to work. Presumably, the problem occurs when encountering encoded forward slashes, as curl -I https://w3id.org/mpilhlt/reconcile/https%3A is working correctly (gives a 307-redirection), whereas curl -I https://w3id.org/mpilhlt/reconcile/https%3A%2F does not (gives a 404).

AllowEncodedSlashes conf, NoEscape rewrite flag.

---

rhonda/.htaccess

As in #2845, trying to get redirection of requests where the path contains urlencoded URLs to work. Presumably, the problem occurs when encountering encoded forward slashes, as curl -I https://w3id.org/rhonda/reconcile/https%3A is working correctly (gives a 307-redirection), whereas curl -I https://w3id.org/rhonda/reconcile/https%3A%2F does not (gives a 404).

AllowEncodedSlashes conf, NoEscape rewrite flag

---

mpilhlt/.htaccess

Apparently, setting the AllowEncodedSlashes option is illegal in htaccess context. My redirections with this option enabled have resulted in 500 Server errors, probably because it has been a bad htaccess file. I will try something without the option, but if they still won't work I will open an issue...

Remove AllowEncodedSlashes option

---

diga/.htaccess

Our university library has changed the SKOSMOS URLs for our vocabularies (creating a separate subdomain for each project), so we need to update the redirects. Thanks!

Update SKOSMOS redirect target URLs for DiGA

---

credit/.htaccess
credit/README.md

NISO took over maintenance of CRediT from CASRAI this year, which means there are new URLs to redirect to.

Update to reflect new NISO URLs

---

MoRe-SFB1475/.htaccess
MoRe-SFB1475/README.md

Namespace for website and conceptual thesaurus of the collaborative research center "Metaphors of Religion" (https://sfb1475.ruhr-uni-bochum.de/en/). We would love to simply use "MoRe" but deemed it too generic, hence the "SFB1475" suffix.

Add namespace MoRe-SFB1475

---

research-technology-readiness-levels/.htaccess
research-technology-readiness-levels/readme.md

This permanent w3id is meant to formalize as a SKOS vocabulary a taxonomy of Technology Readiness Levels for academia (such as for research software). These are formulated by the [CLARIAH](https://clariah.nl) project and are inspired on the TRL scale as used in the EU, reference:
* Mihaly, Heder (September 2017). "From NASA to EU: the evolution of the TRL scale in Public Sector Innovation" ([PDF](https://web.archive.org/web/20171011071816/https://www.innovation.cc/discussion-papers/22_2_3_heder_nasa-to-eu-trl-scale.pdf)). The Innovation Journal. 22: 1–23. Archived from the original (PDF) on October 11, 2017.

added research technology readiness levels

---

permafrost/.htaccess

use generic rules in root-level .htaccess instead of subfolders (for vocabularies)

use more generic ruleset in root-level  .htaccess

---

icddl/.htaccess
icddl/readme.md

Add icddl ontology  to [perma-id](https://github.com/perma-id) / [w3id.org](https://github.com/perma-id/w3id.org)

[ICDDL] added to perma-id/w3id.org

---

idsa/.htaccess
idsa/README.md

We moved the hosting of a set of resources from jira to gitlab and would like to update the paths accordingly.

Update idsa context paths from jira to gitlab.

---

whow/controlled-vocabulary/.htaccess
whow/data/.htaccess
whow/onto/.htaccess
whow/readme.md

we'd like to add the whow directory for the persistent URIs of the ontologies and linked open data of the WHOW project. Info in the readme.md file

persistent URIs for the WHOW project

---

orcidio/.htaccess
orcidio/README.md

ORCID in OWL is an ontology that wraps notable ORCID identifiers as named individuals so they can be more easily included in other ontologies (e.g., OBO Ontologies) and empower Protege to show rich label information for `dc:contributor` annotations.
The goal of having an entry in w3id.org is to endow this ontology with a PURL as its ontology IRI.

Add redirect `orcidio` for ORCID in OWL

---

cpld/.htaccess
cpld/README.md

This W3ID provides a persistent URI namespace for the Content Profiles / Linked Documents (CP/LD) standard. CP/LD is intended to be a new National Information Standards Organization(NISO) standard for representing scholarly publications as HTML and JSON-LD.
The CP/LD namespace is <https://w3id.org/cpld/> and redirects to <https://github.com/niso-standards/cpld/raw/main/schema/cpld.schema.jsonld>, which hosts the CP/LD JSON-LD context and ontology.
Note that this is currently a private GitHub repository which will be opened for read access once the standard has been approved. It is expected that this namespace will be expanded to cover more finegrained redirects to additional resources.

Content Profiles / Linked Documents (NISO)

---

uri4uri/.htaccess
uri4uri/README.md

Contains a workaround for `MergeSlashes On`, but due to `AllowEncodedSlashes Off`, `%2F` cannot be used in an identifier (see #2934). This is a potential issue only for `/uri/`, but the normalized identifiers never use `%2F` in path anyway (it's either `/` or doubly-encoded `%252F`) so it's not an issue if the URI is produced accordingly.

uri4uri namespace

---

legalhtml/.htaccess
legalhtml/README.md

This namespace will host the resources of LegalHTML, an extension of HTML designed for representing legal acts.

Add legalhtml namespace

---

STREAM/MSLE/.htaccess
STREAM/MSLE/README.md

This is a subsequent PR of https://github.com/perma-id/w3id.org/pull/2947
With this PR I want to create a permanent identifier for the MSLE RDF vocabulary, originated in the STREAM project.

Add of STREAM/MSLE subfolder

---

vair/.htaccess
vair/README.md

The change has made to make the ontology's name clearer.

renamed airiv to vair

---

tib/README.md
tib/oais/README.md
tib/oais/ip/.htaccess
tib/oais/ip/EC1/.htaccess
tib/oais/ip/EC1/AIP1/.htaccess
tib/oais/ip/EC1/AIP1/README.md
tib/oais/ip/EC1/AIP2/.htaccess
tib/oais/ip/EC1/AIP2/README.md
tib/oais/ip/EC1/README.md
tib/oais/ip/README.md

URI namespace for [https://github.com/fengel/OAIS-IP](https://github.com/fengel/OAIS-IP) and example ontology files: [https://git.tib.eu/terminology/sandbox/oais-ip-ontology-collection/-/tree/master/dev/abox](https://git.tib.eu/terminology/sandbox/oais-ip-ontology-collection/-/tree/master/dev/abox).

Adding rules to OAIS-IP

---

n2t/.htaccess
n2t/README.md

New permanent identifier request for `n2t` to provide persistent locator for the N2T resolution service.

Rules for N2T service redirection

---

ecfo/.htaccess
ecfo/readme.md

adding redirect for ecfo ontology hosted in https://eats-uoa.github.io/ECFO-Emission-conversion-Factor-Ontology/

adding redirect for ecfo ontology

---

vdl/.htaccess

- Updating the redirect to the target since it had an extension added
here: https://github.com/w3c-ccg/vdl-vocab/pull/5

Fix /vdl/v1 target.

---

hsu-aut/cask/.htaccess
hsu-aut/caskman/.htaccess
hsu-aut/css/.htaccess
hsu-aut/readme.md

Adds a new parent folder for ontologies created by the Institute of Automation of Helmut Schmidt University in Hamburg `hsu-aut`. 
This parent folder contains a directory structure with redirects for three ontologies. Every directory contains an .htaccess file that takes care of redirecting requests to that particular ontology.

Adds Readme, directory structure and and redirects for hsu-aut ontologies

---

simulation/.htaccess
simulation/README.md

Changed the readme with the new link and the .htaccess file with the new redirect

Addition of a new /contexts/ sublink that redirects to a taxonomy of cultural contexts related to the simulation project

---

icon/.htaccess
icon/README.md

A new URI (https://w3id.org/icon/data/) has been added to the "Icon" folder. Therefore, both the .htaccess and the permanent URI document were modified.

Icon added new URI

---

ixo/.htaccess

Replaces the (.*) old route `https://protocol.ixo.foundation/` with `https://github.com/ixofoundation/`

Update default top-level domain

---

lmodel/.htaccess

This PR redirects to raw.githubcontent.com/xx instead of github.com/xx.  Tested locally on Ubuntu.

chore(linkml): use raw github content instead

---

hsu-aut/ieee1872.2/.htaccess
hsu-aut/readme.md

Adds a new folder for one ontology to parent folder for ontologies created by the Institute of Automation of Helmut Schmidt University in Hamburg hsu-aut. New directory contains an .htaccess file that takes care of redirecting requests to that particular ontology.

Adds redirection to new hsu-aut ontology 

---

dstv/.htaccess
dstv/README.md

Added a redirect for the DSTV Ontology, which represents an owl extension of the existing DSTV standard for steel construction.
The ontology is part of the project Internet of Construction (see readme) and a future extension which is called BAUFEST 4.0.
Sorry for misforming the .htaccess. TBH, I wildly copy&pasted it around without having a look at the actual rewrite conditions. Hope it works better like this.
thanks for the help :)

DSTV Ontology round#2

---

biopragmatics/.htaccess
biopragmatics/README.md

This PR adds a new namespace `biopragmatics` that provides a persistent URI namespace for artifacts in the [Biopragmatics project](https://biopragmatics.github.io/).
Initially, the redirect configuration supports redirecting towards artifacts in the https://github.com/biopragmatics/obo-db-ingest, which constitute ontology files in the OBO and OWL formats that have been produced by converting biomedical databases such as the [HUGO Gene Nomenclature Committee (HGNC)](https://www.genenames.org/) and the [Universal Protein Resource (UniProt)](https://www.uniprot.org/) that are not natively ontologies. The ontology community expects ontologies to be referenced via PURLs, so W3ID is a natural fit.

Add biopragmatics namespace

---

biopragmatics/.htaccess
biopragmatics/README.md

After suggestion from @matentzn, it makes more sense to have a generic redirect subspace "resources" instead of "obo" to show that things appearing in this path might not have anything to do with the OBO Foundry nor OBO flat file format

Update path for Biopragmatics resources

---

italia/controlled-vocabulary/.htaccess
italia/data/.htaccess
italia/metadata/.htaccess
italia/onto/.htaccess
italia/readme.md

Please accept the new changes we applied to the readme of the project italia in w3id.org and the new rules to redirect to a brand-new Itailan National Digital Platform named schema.gov.it

Update of readme information and redirect rules for w3id.org/italia

---

bbs/.htaccess
bbs/README.md
security/.htaccess

Updating the url re-write rule to reflect the new repository name for the vc-di-bbs suite.

fix: bbs context repo rename

---

docmaps/.htaccess
docmaps/readme.md

This Github repository was re-homed in a new org: https://github.com/Docmaps-Project/docmaps .

Fix: Update link to Docmaps-project github organization

---

cpont/.htaccess
cpont/README.md

Updated `/cpont/.htaccess` and `/cpont/README.md`.
Added redirects for `/cpont/mappings/` to the CPONT mapping commons repo.

add /cpont/mappings/ to CPONT

---

italia/env/README.md
italia/env/ld/.htaccess
italia/env/onto/.htaccess
italia/env/vocab/.htaccess

We intend to use w3id.org in order to obtain persistent URIs for the network of ontologies and data of the Italian Institute for Environmental Protection and Research (ISPRA)

Introduce env/ path under italia/ for Italian environmental information

---

rorio/.htaccess
rorio/README.md

ROR in OWL is an ontology that wraps [Research Organization Registry (ROR)](https://ror.org/) identifiers as named individuals so they can be more easily included in other ontologies (e.g., OBO Ontologies) and empower the [Protégé](https://protege.stanford.edu/) ontology editor to show rich label information for `dc:contributor` annotations.
The goal of having an entry in w3id.org is to endow this ontology with a PURL as its ontology IRI.
This PR is similar in concept to https://github.com/perma-id/w3id.org/pull/3006 but for a different resource (i.e., ROR instead of ORCID)

Add redirect `rorio` for ROR in OWL

---

riverbench/.htaccess
riverbench/README.md

RiverBench is a suite of curated and well-described datasets for benchmarking RDF systems, especially in streaming applications.
The .htaccess file turned out quite long, but I tested it extensively on a local Apache instance. It should work fine.
There are so many rules due to the modular nature of RiverBench – many datasets in stored different repos. Everything is either stored on GitHub Pages (docs) or in GitHub releases (metadata and data files).

Add /riverbench

---

riverbench/.htaccess
riverbench/README.md

This PR fixes the ordering of rewrites in RiverBench's htaccess file. I didn't catch this in testing, because the error only becomes apparent on clients requesting HTML in the Accept header, and I was testing with Postman.
I've also added some test links, so that the CI can help catch any similar errors in the future.

RiverBench: fix rewrite ordering

---

unified-engineering/.htaccess
unified-engineering/README.md

The first version redirects to a demo ontology. This will be later extended with redirect paths to individual ontologies.

Adding redirect to the unified engineering ontology

---

exe-kg-lib/.htaccess
exe-kg-lib/README.md

This PR adds a redirect entry (`/exe-kg-lib`) for [ExeKGLib's website](https://boschresearch.github.io/ExeKGLib/).

Add redirect entry for ExeKGLib's website

---

riverbench/.htaccess

In #3258 I forgot to move the rules for profile metadata :disappointed:
This pull request fixes the order rules so that profile metadata in RDF is served correctly for browser users.

RiverBench: Fix ordering of rules for profile metadata

---

riverbench/.htaccess

- Redirections to the main page did not work at all for browser users, I had to move them above the "just serve HTML" rule.
- I added redirections to the latest version of schema docs from the main IRI. This is basically a redirect from ontology IRI to its latest version IRI.
I've tested this locally, should be good.

RiverBench: fix a few routing bugs

---

kgraphx/.htaccess
kgraphx/readme.md

Dear Author,
I have created a new tool called kgraphx which is a tool to make  knowledge graph creation and management easy.
and I would like to have a persistent URI namespace for it.
I wanted to publish it online using your permanent id. Thus I forked your repository (w3id.org), I added files (.htaccess, README) in the subdirectory (kgraphx).
Please let me know if you approve that and what will be the following steps.
Thanks!

New Persistent URI for kgraphx

---

geochem/.htaccess
geochem/1.0/.htaccess
geochem/1.0/README.md
geochem/README.md

This is a new base url scheme for geochemistry related vocabularies.  Initial test-- redirect points to demo location in vocabulary server, will update when the final version is loaded.

set up testing for geochem vocabulary redirects to ARDC RVA

---

saqi/.htaccess

This is continuation of the closed PR for /saqi/ -  [Link ](https://github.com/perma-id/w3id.org/pull/3325)
Apologies for 2 quick PRs, we wanted to allow subfolders to redirect as well.
Changes done - 
Replaced redirect file to - 
```
Options +FollowSymLinks
RewriteEngine on
RewriteRule ^(.*) https://kracr.iiitd.edu.in/ontology/saqi/$1 [R=307,L]
```

edited /saqi/ to allow subfolders

---

risk/.htaccess
risk/README.md
sense/.htaccess
sense/README.md

Hello,
I need 2 perma-id URLs for my newly added folders ./risk and ./sense.
README.md and .htaccess files are ready in both folders.
I hope everything works
Thank you in advance
BR
Hervé Pruvost

added /risk and /sense paths in order to redirect to corresponding ontology web sites. Author: Hervé Pruvost from Fraunhofer IIS/EAS

---

inmevo/.htaccess
inmevo/README.md

A request for a permanent link for the International Meteorological Vocabulary (https://public.wmo.int/fr/ressources/meteoterm).

Added inmevo redirect.

---

inmevo/.htaccess

the w3id added was: https://w3id.org/inmevo/inmevo. Replacing ^inmevo$ with ^$ achieved the desired path.

remove duplicate path as suggested by @dgarijo

---

ooxml/README.md
ooxml/onlineInfomativeAnnexes/.htaccess

When OOXML URLs are changed, I forgot to update this permanent identifier.

Fixing a broken URL for https://w3id.org/ooxml/onlineInfomativeAnnexes/

---

APD/glossary/.htaccess
APD/traits/.htaccess

Apologies for the extra PR. We noticed that a `#` is getting converted into `%23`, the NE flag in rewrite rule should prevent this.

modify APD redirect (Add NE to prvent hash being escaped)

---

baf/.htaccess
baf/README.md

Hello,
I need one perma-id URL for my newly added folder ./baf.
README.md and .htaccess files are ready in both folders.
Everything seems valid.
Thank you in advance
BR
Hervé Pruvost
(Fraunhofer IIS/EAS)
P.S.: This is a new pull request that corrects and replaces the closed PR #3403

added /baf path for providing perma URL to the BAF ontology

---

ro/doi/.htaccess

Adds redirect for https://w3id.org/ro/doi/10.5281/zenodo.8075229 to RO-Crate at https://s11.no/2023/phd/evaluating-fdo/ro-crate-preview.html etc corresponding to https://doi.org/10.5281/zenodo.8075229 (to be minted)

RO-Crate for https://doi.org/10.5281/zenodo.8075229

---

rdfqar/.htaccess
rdfqar/README.md

Dear maintainers, 
I am applying for a w3id for my project and hope that every URI starting with `https://w3id.org/rdfqar/` can be redirected to `https://raw.githubusercontent.com/sxzhang1201/assess-rdf-resource/master/output/report.ttl'.
I am not familiar with the `.htaccess` file so unsure if I write it correctly. Could you please help me check it out?
Much thanks in advance!
Regards,
Shuxin Zhang

Add project - rdfqar

---

iadopt/ont/.htaccess

this adds a redirect to fragment identifiers of the IAdopt ontology.
fixes #3444

iadopt: redirect ontology to fragment identifiers

---

303/.htaccess

Apparently there seems to be sth off with `text/html` requests from Firefox (Chrome just did fine)...

setting default to html

---

dataspaces-policies/.htaccess
dataspaces-policies/README.md

Addition of the dataspaces-policies namespace.
Based on https://github.com/perma-id/w3id.org/blob/master/survey-ontology/.htaccess

Addition of the dataspaces-policies namespace for the data spaces policies ontology

---

icon/.htaccess
icon/README.md

The .htaccess files has been modified to include permanent uris for the different versions of the ontology. The readme file has been updated to include this new option

Adding versioning to the permanent URI of icon ontology

---

mixs-6-2-rc/.htaccess
mixs-6-2-rc/README.md

NMDC is proposing a redesign of the MIxS standard at the governing body's (GSC) annual meeting in August 2023
We're requesting a namespace from w3id that is distinct from NMDC or MIxS during the evaluation period
- Mark A. Miller, MAM@lbl.gov
- Chris Mungall: CJMungall@lbl.gov

Initial mixs 6 2 rc req fixed

---

biopragmatics/.htaccess

Redo of #3508
This PR adds a rewrite rule to expose files in https://github.com/biopragmatics/biomappings (this is a repository I own) through the biopragmatics namespace (which I also own)
For example, we want https://w3id.org/biopragmatics/biomappings/biomappings.sssom.tsv to redirect to https://raw.githubusercontent.com/biopragmatics/biomappings/master/docs/_data/sssom/biomappings.sssom.tsv

Add new rewrite rule for biopragmatics

---

busy/.htaccess
busy/README.md

Add new `/busy/` namespace for Building Systems Ontology.
Simple `.htaccess` modeled after the one from [OPM](https://github.com/perma-id/w3id.org/blob/128e7e51ad6f277608e3c16ffd0b1446d51872d8/opm/.htaccess).

Add /busy/ for Building Systems Ontology

---

GVTPDOntology/.htaccess
GVTPDOntology/README.md

Please, I need a permanent URL that is (https://w3id.org/GVTPDOntology) that points to the Ontology Documentation page(https://gvt2023.github.io/GVTPDOnto/Documentation/index-en.html) , noting that I have created a new account. with respect.

permanent URL

---

nfdi4cat/.htaccess
nfdi4cat/README.md
nfdi4cat/voc4cat/.htaccess
nfdi4cat/voc4cat/README.md

This adds redirects for a SKOS vocabulary for terms used in catalysis that we are developing within [NFDI4Cat](https://nfdi4cat.org).
The IRIs are following the [OBO policy for identifiers](https://obofoundry.org/id-policy.html) except that version-strings may have an optional "v" at the start.

nfdi4cat: Add redirects for voc4cat

---

nfdi4cat/voc4cat/.htaccess
nfdi4cat/voc4cat/README.md

After testing the first live version, we found that one pattern missed an escape.
Thanks a lot for merging #3541 so quickly. We highly appreciate your work.

nfdi4cat: fix match pattern; fix examples in README

---

esim/.htaccess
esim/README.md

Hello,
I would like to register a new perma-id URL for my newly added folder ./esim.
README.md and .htaccess files are ready and included in the esim folder.
Everything seems valid.
Thank you in advance
BR
Hervé Pruvost
(Fraunhofer IIS/EAS)

New perma-id for new ontology "ESIM"

---

sssom/.htaccess

The previous PR created some havoc with the generic fall thru in the end.

Add L flag to SSSOM redirects.

---

zpid/.htaccess
zpid/README.md

This updates the redirects to point to our now openly accessible vocabulary browser at `https://vocabs.leibniz-psychology.org`. Some uris will still redirect to our private instance for licensing reasons.

Update zpid redirects and Readme

---

5s-crate/.htaccess
5s-crate/README.md
trusted-wfrun-crate/.htaccess
trusted-wfrun-crate/README.md

Old https://w3id.org/trusted-wfrun-crate/0.3 will remain, new PIDs will be under https://w3id.org/5s-crate

trusted-wfrun-crate deprecated, now using 5s-crate

---

riverbench/.htaccess

Issue: https://github.com/RiverBench/RiverBench/issues/49
This change introduces support for content negotiation and downloading of RiverBench's metadata in the Jelly format. 
[Jelly](https://github.com/Jelly-RDF) is a high-performance binary serialization of RDF using Protobuf, that can currently be read by Apache Jena and RDF4J, using a [third-party library](https://github.com/Jelly-RDF/jelly-jvm).

RiverBench: Add support for the Jelly RDF serialization

---

nfdi4ing/metadata4ing/README.md

- adds a description of the content negotiation used, replacing the misleading and incorrect documentation of getting different serializations of the metadata4ing ontology
- adds a description of the direct link to the JSON-LD context file

Updates README for nfdi4ing/metadata4ing

---

music-annotation/.htaccess
music-annotation/README.md

The Music Annotation Ontology has been defined and described as part of the [Beethoven in the House project](https://domestic-beethoven.eu) and now needs a persistent URL. 
This PR proposes https://w3id.org/music-annotation

Add Music Annotation ontology in /music-annotation

---

italia/work-accident/README.md
italia/work-accident/controlled-vocabulary/.htaccess
italia/work-accident/data/.htaccess
italia/work-accident/onto/.htaccess

Add work-accident to w3id.org/italia for redirecting to ontologies and open data of INAIL (the National Institute for Insurance against Accidents at Work)

Add work-accident to w3id.org/italia

---

music-annotation/.htaccess

`/v1/` in URL path should have been `/1.0/`. (Not sure what I was thinking)

Fix wrong URIs in music-annotation-ontology

---

bmat/.htaccess
bmat/readme.md
brcomp/.htaccess
brcomp/readme.md
bridge/.htaccess
bridge/readme.md
brot/.htaccess
brot/readme.md
brstr/.htaccess
brstr/readme.md

Updated the urls of the following ontologies (all of them were part of the research project "wiSIB"):
- brot
- bridge
- brcomp
- brstr
- bmat 
the original url https://wisib.de/ontologie under which the ontologies were stored does not exist anymore.

Update of brot, bridge, brcomp, brstr and bmat

---

examples/.htaccess
examples/README.md
examples/simple/.htaccess
examples/simple/README.md

* Add Example 5: Version-aware URIs of ontologies
* Add Example 6: Redirection based on a file extension in the URL
* Add .htaccess file for /examples/, redirecting it to https://github.com/perma-id/w3id.org/tree/master/examples
* In README.md, states that having a maintainer info and GitHub username are requested, per reasons gave in #1673

examples: Add Examples 5 & 6 and maintainer info request

---

mpilhlt/.htaccess

The main purpose of our redirections is to host vocabularies. The repository itself now has a "homepage" that hadn't been accessible using the old redirections. And I have added versioned purls (and "latest") to redirect to (GitHub's tagged copy of) older vocabularies.
I've also added some comments for readability.

Add redirections for versioning and vocab "homepages".

---

vdl/.htaccess

This corresponds to the existing context here: https://github.com/w3c-ccg/vdl-vocab/tree/main/context/aamva.
@msporny @tplooker @clehner: Can one of you please approve.  Thanks.

Add `vdl/aamva/v1` redirect.

---

README.md

* <s>Give two examples of .htaccess:
1. One minimal: I chose one from [/mircat/](https://github.com/perma-id/w3id.org/blob/master/mircat/.htaccess), as they do only simple redirection (w3id.org/mircat/ANYTHING -> fairsharing.github.io/mircat/ANYTHING) in 3 lines of code. No other fancy options.
2. One content type-sensitive: I chose one from [/ppop/](https://github.com/perma-id/w3id.org/blob/master/ppop/.htaccess), as it demonstrates how to handle two content types (HTML and Turtle) using `RewriteCond %{HTTP_ACCEPT}`. User can get some idea here and understand other more complex examples.</s>
* <s>Mention w3id.org/example showcase - #1639</s>
* <s>Add link to .htaccess rules test tool</s>
* Update links to HTTPS where appropriate
* Add link to …

README.md: Give examples of .htaccess and w3id.org/example

---

riverbench/.htaccess
riverbench/README.md

This change adds support for downloading full metadata dumps of RiverBench. The change was tested locally with an Apache instance. Additional links for testing in CI were also added to the README.
Issue: https://github.com/RiverBench/RiverBench/issues/42

RiverBench: Add support for metadata dumps

---

catenax/.htaccess

apache removes the first slash after the virtual dir folder w3id.org, so most specific rules did not fire.
this has been resolved and tested using a local apache (see https://github.com/perma-id/w3id.org/issues/2258)
sorry for the inconvenience.

fix(catenax): specific rules did not fire because of a leading slash in the pattern

---

catenax/.htaccess

extensions to rules which capture for explicit turtle file suffixes
there are quite some references to the previous file rules themselves.
Thx very much for your help!

fix(catenax): cater for explicit turtle file suffixes.

---

README.md
index.html

The checking [was disabled some time ago](https://github.com/perma-id/w3id.org/commit/7636d95dff670b178ef2b4ac17196af64c2f4bf1) so it's probably best to remove references to that in the documentation.

Remove documentation of link checking

---

inrupt/.htaccess

This is used by our tooling so we want to make it public. It's not endorsed by https://opentelemetry.io/

Inrupt: Add opentelemetry vocab

---

sri/.htaccess
sri/README.md

Please add the new namespace `sri` to the w3id repository.
It will contain semantic resources (an ontology and reference datasets) for the smart readiness indicator.
A local test of the `.htaccess` file worked.

feat: add new `sri` namespace

---

np/.htaccess

This PR improve the redirection of the `/np/` namespace  (used for nanopublications)
* Fix redirection status from 302 to 307 for the np namespace to enable passing POST requests
* Enable redirection for URLs ending with `.trig`
@tkuhn please confirm you agree to integrate these changes since you are the owner of the namespace

Fix redirection for the np namespace (nanopublications)

---

stax/.htaccess
stax/README.md

This PR adds support for downloading nanopublication dumps from the RDF-STaX website. See more details here: https://rdf-stax.github.io/dev/nanopubs/
The changes were tested with a local Apache instance. I have also added test URLs to the README.

RDF-STaX: add support for nanopub dumps

---

oseg/.htaccess
oseg/README.md

For now, only RDF ontologies:
- OKH
- OTRL
- TsDC
- TsDC requirements
- OSH Ontology

Adds `/oseg/` - Open Source Ecology Germany e.V.

---

ksa/.htaccess
ksa/README.md

Add `/ksa/` as the base path for ontology and vocabulary identifiers for the Kingdom of Saudi Arabia, developed by the Open Geospatial Consortium.
For now, only a Feature Type Catalog is available.

Add `/ksa/` - Kingdom of Saudi Arabia ontologies by the OGC

---

ksa/.htaccess

`^/feature-types/?$` path in remote no longer exists, so we need to remap it.

Redirect /ksa/feature-types to homepage

---

sri/.htaccess

widoco/ontoology changed the file extension for the RDF/XML output from .rdf to .owl. This commit fixes the corresponding redirection rules.

fix: fix file extension for RDF/XML

---

ogc/.htaccess
ogc/README.md

Identifiers for OGC hosted and development resources.

Add `/ogc/` - Open Geospatial Consortium

---

catenax/.htaccess
catenax/README.md

Catena-X just published its new release https://eclipse-tractusx.github.io/blog/new-release-2312
these are the adaptions of the namespace to introduce the version and to move the "current" redirections.

chore: introduce new Catena-X release and move current pointer.

---

nfdi4cat/voc4cat/.htaccess
nfdi4cat/voc4cat/README.md

Add redirects for content types for xml/rdf in addition to existing ones for turtle.
Closes: https://github.com/nfdi4cat/voc4cat/issues/26

nfdi4cat/voc4cat - Add redirects for xml/rdf

---

cro/.htaccess
cro/README.md

The CRO was developed within the ioc project .htacces works in same fashion than for the main ioc ontology which is also redirected here.
I wish whoever manages this a Merry Christmas and a Happy New Year :)
**Lukas Kirner**
*Researcher*  
Individualized Production, RWTH Aachen, Germany.  
https://github.com/kirner-ip
<kirner@ip.rwth-aachen.de>  
ORCID: [0000-0001-9753-2422](https://orcid.org/0000-0001-9753-2422)

Added redirect for the /cro (construction resource ontology) 

---

iaam/i40fd/.htaccess

Fixed access for text/html due to a typo and acess to json version of the ontology.
In addition added a 406 response in case the format is not acceptable.

Minor typos and default rule if not found 406 for iaam/i40fd

---

iaam/i40fd/.htaccess

When importing the ontology from iaam/i40fd in Protege 5.6.3 the error invalid domain appears due to
underscores. See https://stackoverflow.com/a/48444910 Removed underscore from domain to make domain
compatible with Protege.

New redirection domain for iaam/i40fd

---

iaam/i40fd/.htaccess
iaam/i40fd/protocol/iolink/.htaccess
iaam/i40fd/protocol/iolink/README.md

Expanded iaam/i40fd to include protocol/iolink which describes the IO-Link protocol
in the context of the i40fd ontology.

Added secondary ontology to iaam/i40fd

---

semioe/.htaccess
semioe/README.md

The SemIoE ontology is a recent project hosted on GitHub, developed within the HOMEY project, dedicated to develop a vocabulary for an Internet-of-Everything scenario. I am the maintainer of this URI.

SemIoE ontology added

---

isample/biology/biosampledfeature/.htaccess
isample/biology/biosampledfeature/1.0/.htaccess
isample/earthenv/esmaterialsample/1.0/.htaccess
isample/earthenv/esmaterialsample/1.0/README.md
isample/earthenv/essampledfeatrole/1.0/.htaccess
isample/earthenv/mingroup/1.0/.htaccess
isample/earthenv/rocksediment/1.0/.htaccess
isample/opencontext/material/0.1/.htaccess
isample/opencontext/specimentype/0.1/.htaccess
isample/opencontext/specimentype/0.1/README.md
isample/vocabulary/material/.htaccess
isample/vocabulary/material/0.9/.htaccess
isample/vocabulary/material/1.0/.htaccess
isample/vocabulary/sampledfeature/.htaccess
isample/vocabulary/sampledfeature/1.0/.htaccess
isample/vocabulary/specimentype/.htaccess
isample/vocabulary/specimentype/0.9/.htaccess
isample/vocabulary/specimentype/1.0/.htaccess
isample/vocabulary/specimentype/1.0/README.md

escaping :// in url query parameters seems to cause problems, remove escape sequences. Fix some redirect targets and remove leading '/' in rules.

remove escape sequences, fixes to rules

---

iaam/i40fd/protocol/canopen/.htaccess
iaam/i40fd/protocol/canopen/README.md
iaam/i40fd/vocab/device/.htaccess
iaam/i40fd/vocab/device/README.md

In namespace iaam/i40fd new paths have been added to integrate the canopen protocol ontology and the
generic device vocabulary.

iaam/i40fd: Added canopen and device vocab paths

---

iaw/.htaccess
iaw/README.md

Create the identifier for Image Annotation Workbench (IAW) to provide persistent URLs for IIIF images, publications, and IIIF manifests.

Create the identifier for Image Annotation Workbench (IAW)

---

fep/.htaccess
fep/README.md

A [Fediverse Enhancement Proposal](https://codeberg.org/fediverse/fep/src/branch/main/feps/fep-a4ed.md) (FEP) is a document that provides information to the Fediverse community. The goal of a FEP is to improve interoperability and well-being of diverse services, applications and communities that form the Fediverse.
FEP community links:
- [SocialHub forum category](https://socialhub.activitypub.rocks/c/standards/fep/54)
- [Current Codeberg repository](https://codeberg.org/fediverse/fep)
FEP-888d is the proposal covering this usage of W3ID:
- [SocialHub forum thread](https://socialhub.activitypub.rocks/t/fep-888d-using-w3id-org-fep-as-a-namespace-for-extension-terms-and-for-fep-documents/3098)
- [The proposal as currently hosted on …

Add FEP prefix

---

fep/.htaccess

Noticed I copy-pasted an outdated set of redirects in the last PR

FEP: Fix old redirects and remove unnecessary rules

---

zpid/.htaccess

So `vocabs/psycharchives-types` will be forwarded to `[skosmus-url]/patypes`

Add htaccess rewrite for special case vocab "patypes"

---

ioc/.htaccess

Hi dear folks at w3id,
I was able to finally move the Internet of Construction (IoC) Process Ontology to its new home.
Therefore changed the URLs.
Greetings,
Lukas

Moved the redirect from University GitLab to a public Github

---

nfdi4cat/voc4cat/.htaccess

Some rules were not prioritizing text/html oder application/xml.
Related https://github.com/nfdi4cat/voc4cat/issues/44

Fix order of redirect rules to get html (not xml)

---

iliad/.htaccess

Use `https://defs-dev.opengis.net/...` URIs instead of `http://...` ones.
@rapw3k, as the official maintainer for `/iliad`, are you ok with this change?

Use HTTPS for ILIAD JF property redirects

---

locolligo/.htaccess
locolligo/CAMPOP-Places/README.md
locolligo/README.md
locolligo/iiif/.htaccess
locolligo/iiif/README.md

Sorry, in the previous two Pull Requests I hadn't appreciated that my /iiif references require a subspace in order for the redirections to work properly.

Move /iiif to subspace; update contact details

---

signposting-tutorial/.htaccess
signposting-tutorial/README.md

This namespace is meant to be used for the [Signposting tutorial](https://github.com/stain/signposting-tutorial) as example persistent identifiers for `cite-as` link relations. The tutorial involves cloning to a user's GitHub repository, so the username is part of the (example) PID.

Add signposting-tutorial namespace

---

awslabs/neptune/SPARQL-CDTs/.htaccess
awslabs/neptune/SPARQL-CDTs/README.md

In the Amazon Neptune team at AWS we are working on a spec and corresponding artifacts (e.g., test suites) for an approach to capture and to query composite datatypes (lists and maps) as RDF literals. Our Github repo for this work is https://github.com/awslabs/SPARQL-CDTs
With this PR we want to introduce permanent identifiers for the new datatype IRIs and for the IRIs of the SPARQL functions defined in our spec, as well as for the spec document itself.
We are planning to publicly announce our proposal within the next couple of weeks. Until then, we would appreciate if pointers to it are not yet shared on mailing lists, etc.

Redirects for SPARQL-CDT spec

---

awslabs/neptune/SPARQL-CDTs/.htaccess

As per https://github.com/perma-id/w3id.org/pull/3928#issuecomment-1976296199, I have created Github pages for https://github.com/awslabs/SPARQL-CDTs and modified the redirects to point to these pages.

Change awslabs/neptune/SPARQL-CDTs redirects to point to Github pages

---

awslabs/neptune/SPARQL-CDTs/.htaccess

Daniel, I am terribly sorry that I have to bother you again. I just noticed that the target URLs that contain a hash character (`#`) are URL encoded, which turns them into the from URLs. The change in this PR should fix this issue (I hope!)

Fixes encoding of hash URLs in redirects for SPARQL-CDTs

---

CA-ODE4HERA/BiblioOnto/.htaccess
CA-ODE4HERA/BiblioOnto/README.md

In the Clean Aviation project ODE4HERA, we build several linked models concerning the development for hybrid-electric aircraft. We are looking at different methods to share the models. This is the first step towards sharing the entire set of models, for the moment the redirection only involves the bibliography ontology.
My starting point was the blog [post](https://linkingresearch.wordpress.com/2016/01/17/permanent-identifiers-and-vocabulary-publication-purl-org-and-w3id/) by [Daniel Garijo](http://www.dgarijo.com/). The html documentation for the ontology is generated with [pyLODE](https://github.com/RDFLib/pyLODE).

Clean Aviation ODE4HERA project (2024-2026): added readme and htaccess file to redirect the biblio ontology

---

phydit/.htaccess
phydit/README.md

Redirects to the Physics-infused Digital Twin ontology (PhyDiT ) and its documentation. Thank you!

Added redirect for the PhyDit ontology

---

dpv/.htaccess
dpv/README.md

- suffixes and prefixes are changed e.g. /dpv-pd --> /pd
- serialisation are changed e.g. /dpv-owl/dpv-pd --> /pd/owl
- deprecated IRIs are redirected e.g. /dpv-owl/dpv-pd --> /pd/owl

/dpv update IRIs to new repo structure

---

ad4gd/.htaccess

Add mappings for `https://w3id.org/ad4gd/properties/...` to hosted RAINBOW instance.
Please, @rapw3k confirm that the changes are ok.
Thank you.

[ad4gd] Add mappings for custom ad4gd properties

---

dpv/.htaccess

Fixes changes merged in PR perma-id/w3id#3958 (thanks to Daniel for pointing out breaking of older w3id links)
See w3c/dpv#133 for context

/dpv fix breaking older links with redirects

---

APD/.htaccess
APD/README.md

Hi Team,
I recently update the .htaccess file for the APD namespace (https://github.com/perma-id/w3id.org/pull/3963). Unfortunately I made an error (should have used `^ ` instead of `^(.+)$` as general catch-all rule, breaking many redirects. This PR corrects the issue. Apologies for the extra load. 
Thanks,
Daniel

Bugfix in redirect for APD namespace

---

cmd/.htaccess
cmd/readme.md

Add new folder with redirection rules to the Compound Measure Description vocabulary.

Introduce w3id.org/cmd for measure description

---

biopragmatics/.htaccess
biopragmatics/README.md

This adds two new rewrite rules for the Biopragmatics namespace. These are specifically for artifacts in the Bioregistry project, which is a part of the Biopragmatics organization on GitHub. I'm the maintainer of both the projects and this redirect configuration on w3id

Add two additional rewrite rules for Biopragmatics

---

neural-electronic-interface-ontology/.htaccess

I added the rewrite rule:
```
RewriteRule ^neio_([a-zA-Z0-9]+)$ https://bioportal.bioontology.org/ontologies/NEIO/?p=classes&conceptid=https\%3A\%2F\%2Fw3id.org\%2Fneural-electronic-interface-ontology\%2FNEIO_$1 [R=302,NC,NE,L]
```
This works on my local server.
It can be tested using https://w3id.org/neural-electronic-interface-ontology/NEIO_0000101.

NEIO redirect to bioportal (attempt 1)

---

dpv/.htaccess

Fixes cases where
path: /legal/eu/gdpr/owl
should resolve to: /legal/eu/gdpr/eu-gdpr-owl
instead goes to: /legal/eu/gdpr/owl
Because the generic rule /legal/{2}/.* is matched before the /owl (the .* swallows /owl with the separator)

/dpv fix rule order for matching /owl first

---

mpilhlt/.htaccess

Language selection in managed resources is now done diffrently.
(With Javascript and browser language instead of via filenames.)

Remove language filename components in redirect targets

---

usgs/README.md
usgs/sb/.htaccess

I added a new "sub-namespace" for the /usgs/ identifier space to handle cases where we are using ScienceBase as a long-term archive and need an abstraction to safeguard URLs proliferated onto third party infrastructure for the eventual move of the archive items onto a ScienceBase successor.

Added /usgs/sb/ rewrite rules and usgs namespace readme changes

---

digibatt/.htaccess
digibatt/readme.md

This pull request creates basic redirect rules to be used for the Horizon Europe research project DigiBatt. It is intended to support the creation of RDF linked data and knowledge graphs in the project. 
The .htaccess file contains two re-direct rules:
1. Point the base purl `https://w3id.org/digibatt` to the project documentation index file `https://battmoteam.github.io/digibatt/index.html`
2. Point sub-category purls to the respective html files in the project documentation, e.g. `https://w3id.org/digibatt/deliverable/public#D1` to `https://battmoteam.github.io/digibatt/deliverable.html#D1`
Project Website: [DigiBatt](https://digibattproject.eu/)
Cordis Entry: [DigiBatt on Cordis](https://cordis.europa.eu/project/id/101103997)
Contacts: [Simon Clark](mailto:simon.clark@sintef.no), …

Redirects for HEU research project DigiBatt

---

gensc/.htaccess

Sorry @dgarijo, I didn't notice this when I reviewed the patch.  The directory name should not be repeated in the .htaccess file.
(Fix for #4003.)

Remove superfluous directory name from .htaccess.

---

tractusx/.htaccess
tractusx/README.md

Tractus-X is one of the most active projects in the Eclipse Foundation [1]. In different repositories, there's structures that are identified in the `https://w3id.org/tractusx` namespace. Reference implementations like tractusx-edc [2] use properties from this namespace. The spec can be found in tractusx-profiles [3]
[1]https://projects.eclipse.org/projects/automotive.tractusx
[2] https://github.com/eclipse-tractusx/tractusx-edc
[3] https://github.com/eclipse-tractusx/tractusx-profiles

feat(tractusx): register tractusx namespace

---

tractusx/.htaccess

The behavior was such that `https://w3id.org/tractusx/policy/v1.0.0` didn't resolve correctly while `https://w3id.org/tractusx/policy/v1.0.0/` did. The fix should resolve this.

fix(tractusx): match from 0 additional chars instead one

---

digibatt/.htaccess

This pull request modifies the .htaccess file for digibatt to remove the redundant "digibatt" string from the PURL, such that the following redirection is valid:
`https://w3id.org/digibatt` --> `https://digibatt.github.io/digibatt/index.html`

Update .htaccess for digibatt

---

mediatype/.htaccess

The current content at `conneg.info` is problematic. It appears the domain control was lost. Overriding to the source of what likely was there before and leaving to the maintainer (@nicholascar) to fix as needed.
More info: https://github.com/perma-id/w3id.org/issues/3625

Add override for mediatype/.

---

iaw/.htaccess

Added persistent URL entries for publications hosted in the Glycerine instance.

Add entries for IAW Glycerine instance

---

radx/.htaccess

add a default redirect to the ontology classes view when no terms are specified

add redirect ontology classes view by default

---

usgs/README.md
usgs/geokb/.htaccess

This rewrite rule resolves entities (properties and items) to the Wikibase instance we are using to develop a knowledge graph for all things USGS geoscience. It will support future mobility into other platforms for entities that are unique to this knowledge graph. I also followed some previous suggestions on formatting readme text.

Added documentation and rewrite rules for /usgs/geokb/

---

big-map/.htaccess
big-map/readme.md

This pull request initializes PURL redirects for the EU research project BIG-MAP. The goal is to provide resolvable URIs within an RDF knowledge graph for the creation of linked data. 
.htaccess rules have been tested and confirmed with [madewithlove ](https://htaccess.madewithlove.com/)

Init PURL redirects for BIG-MAP

---

gaia-x/.htaccess
gaia-x/README.md

This introduces the new redirection strategy for the latest Gaia-X Clearing House Registry version.
The README file also has been updated as it was outdated.

Update Gaia-X redirections & README for latest version

---

riverbench/.htaccess
riverbench/README.md

This pull request introduces a lot of changes in the handling of RiverBench's PURLs, due to adopting a new structure (with benchmark categories and tasks) in the upcoming version 2.0.0. Backwards compatibility was maintained where possible.
These changes were tested on a local instance of Apache.
RiverBench issue: https://github.com/RiverBench/RiverBench/issues/65

RiverBench: restructure PURLs for 2.0.0 release

---

omega-x/.htaccess
omega-x/README.md

The purpose of this request is to create a permanent URL for the omega-X project Common Semantic Data Model, using w3id.org.
This URL will redirect to the project's GitHub repository: https://github.com/FZ-HANNOU/Omega-X .
The Common Semantic Data Model is a modular ontology created to support semantic interoperability in the European Energy data space omega-X (https://omega-x.eu/). This ontology is used by the project's stakeholders, but also beyond, to discucss and enable interoperability with other European data space initiatives.
Thank you for considering this request.

Create a permanent link for the Omega-X CSDM (Common Semantic Data Model)

---

iaam/i40fd/profiles/canopen/.htaccess
iaam/i40fd/profiles/canopen/README.md
iaam/i40fd/profiles/iolink/.htaccess
iaam/i40fd/profiles/iolink/README.md
iaam/i40fd/units/canopen/.htaccess
iaam/i40fd/units/canopen/README.md
iaam/i40fd/units/iolink/.htaccess
iaam/i40fd/units/iolink/README.md

This is an update to the iaam namespace. Added a path for units and profiles for iolink and canopen.

iaam/i40fd: Added canopen and iolink paths for units and profiles

---

ro/wfrun/process/.htaccess
ro/wfrun/provenance/.htaccess
ro/wfrun/workflow/.htaccess

This PR removes trailing slashes from HTML redirect URLs (there was a similar fix previously in #2981). They are currently breaking versioned redirects such as https://w3id.org/ro/wfrun/process/0.4 (thanks @jmfernandez for reporting this).
It also reverts the swapping of `workflow_run_crate` and `provenance_run_crate` in `ro/wfrun/provenance/.htaccess` and `ro/wfrun/workflow/.htaccess`.
@dgarijo I think these problems were accidentally caused in #4137 when moving things around.

Fixes for ro/wfrun

---

riverbench/.htaccess

This PR fixes a small issue in how metadata dumps for stable releases in RiverBench are accessed.
The change was tested with a local Apache instance.
Issue: https://github.com/RiverBench/RiverBench/issues/67

RiverBench: Fix accessing metadata dumps for stable releases

---

catenax/.htaccess
catenax/README.md

- also includes domain taxonomy rules.
- tested with a suite of url patterns against a local apache equipped with the branch.
[test.csv](https://github.com/user-attachments/files/15514276/test.csv)
[test_local.csv](https://github.com/user-attachments/files/15514278/test_local.csv)
```console
#!/bin/bash
while IFS=";" read -r url1 url2; do
ret=$(curl -L -s -o /dev/null "$url1" -w "%{url_effective}\n")
if [ "$ret" != "$url2" ]; then
echo "Expected redirect from $url1 to $url2 but got $ret";
exit 1
fi
retr=$(curl -s -L -o /dev/null -w "%{http_code}\n" "$ret")
if [ "$retr" != "200" ]; then
echo "Expected success status 200 from $ret, but got $retr";
exit 1
fi
done < test_local.csv
```

chore: upgrade to Catena-X 24.05 (and refer to intermediate 24.03)

---

omega-x/.htaccess
omega-x/README.md

This PR aims to update the redirection of the Omega-X to capture: 
The ontology documentation website https://fz-hannou.github.io/Omega-X
The ontology repository https://github.com/FZ-HANNOU/Omega-X
The ontology source files https://github.com/FZ-HANNOU/Omega-X/blob/main/Omega-X-v1.0.ttl and modules. 
Best regards,

Update Omega-X redirection to capture website, repository and ontology files

---

stax/.htaccess
stax/README.md

This PR fixes an issue with downloading Nanopublication dumps from the RDF-STaX website.
The changes were tested on a local instance of Apache. The test links in the README were updated accordingly.
Issue: https://github.com/RDF-STaX/rdf-stax.github.io/issues/53

RDF-STaX: fix links to nanopub dumps

---

ro/crate/.htaccess

https://www.researchobject.org/ro-crate/1.1/context.jsonld becomes https://www.researchobject.org/ro-crate/specification/1.1/context.jsonld etc.

RO-Crate specifications in subfolder

---

ro/terms/.htaccess

... to ensure the Content-Type from GitHub Pages matches content negotiation
Also avoid file extension (which should not be in PIDs) for https://w3id.org/ro/terms/workflow-run/context

Redirect to .jsonld variant of JSON-LD context

---

battinfo/.htaccess
battinfo/readme.md

This pull request initializes PURL redirects for the Battery Interface Ontology (BattINFO). The goal is to provide resolvable URIs 2for the ontology and its terms.
.htaccess rules have been tested and confirmed with [madewithlove](https://htaccess.madewithlove.com/)

Create PURLs for Battery Interface Ontology

---

CityOWL/.htaccess
CityOWL/README.md

CityOWL is an ontology network created from the CityGML 3.0 UML model
* Two ontology networks for describing semantic 3D city models created from the [CityGML 3.0 UML model:](https://github.com/VCityTeam/UD-Graph/blob/master/Transformations/test-data/UML/CityGML_3.0-workspaces-documents.eap)
* [CityOWL CWA](https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityOWL/CWA/3.0/): a more constrained representation of the CityGML 3.0 UML model
* [CityOWL OWA](https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityOWL/OWA/3.0/): a less constrained representation of the CityGML 3.0 UML model
* Transformed using [ShapeChange](https://shapechange.net/) and [a model-driven transformation pipeline](https://github.com/VCityTeam/UD-Reproducibility/tree/c91da …

CityOWL Permanent Identifier

---

edc/.htaccess
edc/README.md

This PR add redirections for the [EDC](https://projects.eclipse.org/projects/technology.edc)  (Eclipse Dataspace Components) project.
It contains two redirects:
- The redirection for the JSON-LD context of the connector management API.  
- The fallback one to the docs website.

Add redirections for Eclipse Dataspace Components project

---

gaia-x/.htaccess

Just a quick update to map all `development` related URLs to our `development` environment instances and map all other requests to the Gaia-X ontology documentation.

Update Gaia-X redirects

---

CEIR/.htaccess
CEIR/README.md

Hello everyone,
I have added a permanent identifier for [CEIR (Center for Enterprise Information Research)](https://ceir.de/). This way we don't need to create a new "root" identifier for each of our projects. I think that our existing identifiers (SocDOnt & ColActDOnt) are still viable since the .htaccess-files for (these) ontologies are more complex (due to the individual versions and file formats) than the simple redirects we will use for CEIR/MOBDA, CEIR/IRECS, etc.
Regards
Martin

Add CEIR - Center for Enterprise Information Research

---

cop/.htaccess
cop/README.md

COP stands for 'Core Ontology of Phenotyping'
Changes:
* Add .htaccess configuration for https://w3id.org/cop
Tested with the Dockerfile provided by #3305.

Add cop config

---

xapi/.htaccess

Minor update to .htaccess to add redirect for navy xapi library to https://navy-xapi-library.bitbucket.io/ and also  update the redirect for adl concept searches to  https://profiles.adlnet.gov/search

Update .htaccess for /xapi

---

gfo/.htaccess
gfo/README.md

GFO is divided into sub modules, which are located at `/gfo/SUB_MODULE`. As it is not clear what and when modules will be added, we have taken a generic approach in `.htaccess`. See `README.md` for details.

Add gfo config

---

cno/.htaccess
cno/README.md

Dear w3id Team,
with this pull request I kindly request the /cno# identifier for the construction site network ontology (cno) we will present at this years EC3 conference. The ontology adds concepts to describe networks to realize signal strength estimation calculations.
I copy pasted and modified the readme and htaccess from another identifier of one of our ontologies, as this works as it sould :)
Thank you for your work, and have a nice day,
Lukas

Adding an identifier for the Construction Site Network Ontology (CNO) (EC3 Paper)

---

hadids/.htaccess
hadids/README.md

Added redirects for /hadids to https://datatracker.ietf.org/doc/draft-carter-high-assurance-dids-with-dns/

Add hadids url

---

EUREF-HDC/.htaccess
EUREF-HDC/README.md
GNSS-BE-REPO/.htaccess
GNSS-BE-REPO/README.md

EUREF-HDC 
EUREF HISTORICAL DATA CENTRE
Daily 30s Global Navigation Satellite System (GNSS) Receiver Independent Exchange Format (RINEX) data available from the EUREF historical data centre.
(example: https://epncb.oma.be/PID/catalog)
GNSS-BE-REPO
Daily 30s Global Navigation Satellite System (GNSS) Receiver Independent Exchange Format (RINEX) data available from the Belgian GNSS repository.
(example: https://gnss.be/PID/catalog)

Request to add identifiers for the GNSS-BE-REPO and for the GNSS-BE-REPO

---

vc-barcodes/.htaccess

- Use main homepage for base path.
- Use generic pattern for context redirect.

Fix vc-barcodes rules.

---

catenax/.htaccess
catenax/README.md

The Catena-X consortium ended at 2024-07-31
We are currently migrating the ontologies to the Catena-X association and its Open Source Organisation (Eclipse Tractus-X)
Until that migration is over, we temporarily introduce an intermediate location (at big-data-spaces orga) to avoid downtimes in any referring systems.

fix: temporarily migrate catenax ontologies 

---

aruna/.htaccess
aruna/README.md

Purpose: This pull request is submitted to request an identifier for the [ARUNA Data Orchestration Engine](https://aruna-storage.org).
As the representative of the ARUNA team, I am submitting this request on behalf of our team.
The identifier is needed to offer PIDs to our users, which is required for a FAIR data managment.
Notes: Please process this request to issue an identifier for the ARUNA Data Orchestration Engine. If any further information or documentation is needed, feel free to contact me.

Add PIDs for the ARUNA Data Orchestration Engine

---

lara/.htaccess
lara/README.md
oso/.htaccess
oso/README.md

Please add  oso w3id
The Open Science Ontologies - (OSO) are a set of lean, open and modular top-level and domain ontologies designed for interoperable scientific experimentation, fast reasoning and machine learning / AI applications in mind. 
Thanks a lot :)

Add oso w3id

---

drp/.htaccess
drp/README.md

dummyrepository.org is a demonstrator designed to show the possibilities for sharing and publishing the capabilities and metadata of (data) repositories. Therefore, the demonstrator needs a few persistent identifiers.

New re3ids for dummyrepository.org (drp)

---

riverbench/.htaccess
riverbench/README.md

This PR adds two new routes to support a new feature of RiverBench: metadata dumps that include benchmark results.
This change was tested on a local instance of Apache. I've also added a few new links to the README that should work after this is merged.
Issue: https://github.com/RiverBench/RiverBench/issues/101

RiverBench: add support for dumps w/ benchmark results

---

jelly/.htaccess
jelly/README.md

This PR adds a new prefix (`jelly`) for the Jelly RDF serialization format and streaming protocol.
The .htaccess file simply redirects all requests to GitHub Pages. The README contains a few test links that should work after this is merged.
I have tested this on a local Apache instance.

Add /jelly

---

resiliont/.htaccess
resiliont/Readme.md

Could you create the perm-id for the ResiliOnt?
ResiliOnt is an OntoUML ontology for resilience. We had a paper accepted in this year's ER. Other related artifacts will be produced in the future.

Add ResilOnt perma-id

---

yang/README.md
yang/library/.htaccess

This PR adds a namespace for the YANG Library Ontology under `/yang/library`.

Add YANG Library Ontology

---

aerOS/README.md
aerOS/data-catalog/.htaccess

This PR adds a new namespace for the Data Catalog Ontology of the [aerOS](https://aeros-project.eu) project.

Add aerOS Data Catalog Ontology

---

riskman/.htaccess
riskman/README.md

We added new ontology and SHACL shapes and would like new permanent ids to reflect that.
Thanks.

Add riskman security shapes/ontology.

---

nanolinks/.htaccess
nanolinks/README.md

This namespace provides a persistent URI namespace for NanoLinks, a demo Knowledge Graph for interoperable nanosafety data semantic data model.

Add nanolinks namespace to w3id.org

---

laderr/.htaccess
laderr/README.md

Could you please add the LaDeRR project folder?
"The Language for Describing Risk and Resilience (LaDeRR) is an ontology-based domain-specific description language designed to standardize the way risks, resilience factors, and related entities are represented."
My GitHub ID is in the README file, inside the html table. Is that ok?
Thank you.

Add LaDeRR project

---

resiliont/.htaccess
resiliont/Readme.md

@dgarijo , the redirection is almost working. We are getting there. =)
Instead of redirecting to `https://raw.githubusercontent.com/pedropaulofb/resiliont/main/resources/Ontological%20Foundations%20of%20Resilience.pdf` it is redirecting to `https://raw.githubusercontent.com/pedropaulofb/resiliont/main/resources/Ontological0Foundations0of0Resilience.pdf``. Seems that adding quotation marks will solve the problem. 
Thank you for your patience regarding that.

Fixing ResiliOnt redirection to paper

---

ad4gd/.htaccess

Update generic RAINBOW URIs.
The new rules work will redirect `https://w3id.org/ad4gd/<pilot-name>/<type>/<term>` to the Hosted RAINBOW instance, where:
* `pilot-name` is a path component (`water-quality` and `air-quality` for now, with more to come later)
* `type` is one of `properties`, `sensors`, `sensor-manufacturers` and `procedures`.
* `term` is the URI component for the term. If omitted, the CS will be displayed instead.
@rapw3k , please confirm you're ok with this. Thanks.

[AD4GD] Update RAINBOW URIs

---

GayLesbianBisexualTVCharacters/.htaccess
GayLesbianBisexualTVCharacters/README.md
Greens/.htaccess
Greens/README.md

Adding redirects from two sources that utilized hashes (`#`) in their identifiers. The reason for doing this is so that the external identifiers datatype property utilized in instances of Wikibase can access these identifiers. These redirects have been tested using the online tool (https://htaccess.madewithlove.com/).

Adding Green's Dictionary of Slang and Gay/Lesbian/Bisexual Television Characters.

---

GayLesbianBisexualTVCharacters/.htaccess
Greens/.htaccess

Did not realize that including Greens or GayLesbianBisexualTVCharacters in the match pattern portion of the RewriteRule would nest the redirect, i.e. redirecting https://w3id.org/Greens/Greens/qv5rkjq to https://greensdictofslang.com/entry/qv5rkjq and not matching https://w3id.org/Greens/qv5rkjq at all.
Fixed this and added a base redirect so /Greens redirects as well. Apologies for the mistake!

Fixed issue with nesting directories (Greens/Greens e.g.) and added a base redirect.

---

Greens/.htaccess

Did not initially realize that subdefinitions were linkable in Green's (example: https://greensdictofslang.com/entry/fiwvawq#sn4c). Modified the regular expression to allow for matching.

Redid Green's for subdefinitions (sn4a, for example). Currently the 'a' after 'sn4' would not match, so fixed that.

---

odissei/cv/.htaccess

Also redirect controlled vocabularies in the https://w3id.org/odissei/cv/ namespace to the triply triple store

ADDED: https://w3id.org/odissei/cv/ redirect

---

gaia-x/.htaccess
gaia-x/README.md

Enables a redirect from specs/criteria/cd24.06/criteria/XXX to either the JSON criteria or its HTML documentation depending on the Accept header.

feat: enable redirection for Compliance Document criteria

---

openebench/.htaccess
openebench/README.md
openebench/scientific-schemas/.htaccess
openebench/scientific-schemas/1.0/.htaccess
openebench/scientific-schemas/2.0/.htaccess

This namespace declares several redirections to elements of OpenEBench ecosystem. This first pull request is about providing PIDs for the JSON Schemas of OpenEBench Scientific Benchmarking

First commit to declare `openebench` namespace within w3id.org

---

iiot/.htaccess
iiot/readme.md

Reverts perma-id/w3id.org#4479.
Reverting due to maintainer confusion and the `iiot` contents added here duplicate `IIoT` and we want to avoid case similar directories.

Revert "updated iiot entry redirection".

---

spm/.htaccess

The subdomain of userpages.uni-koblenz.de will be removed in the near future, thus, we migrated the docs to a new domain. This pull request changed the related redirects.

spm: update redirect urls

---

.htaccess
CEIR/.htaccess

Hello everyone,
in this commit we have made our sub-redirects case-**in**sensitive.
However, we have also made the main-redirects for CEIR, ColActDOnt and SocDOnt ( which are all **our** projects) case-**in**sensitive. Unfortunately, this is necessary because **lower-case** links are expected in some publications and misunderstandings have already occurred.
Kind regards

Turn several redirects case-insensitive

---

fep/.htaccess

URLs of the form https://w3id.org/fep/888d/ used to land you on the FEP folder instead of the FEP document. This issue was made worse by some autolinkers inserting a / before a fragment identifier. Fix this so that FEP documents are looked up before subresources in the case of a single trailing slash.

Fix: trailing slash and lookup order for FEP documents

---

drk/.htaccess
drk/README.md

**Purpose:** This pull request is submitted to request an identifier for the DRK project.
As the representative of Fraunhofer FIT, I am submitting this request on behalf of our organization.
The identifier is needed to properly manage and track the DRK project within our systems and collaborations.
**Notes:** Please process this request to issue an identifier for the DRK project. If any further information or documentation is needed, feel free to contact me.

Datenraum Kultur(Cultural Data Space) identifier 

---

opengpt-x/.htaccess
opengpt-x/README.md

[OpenGPT-X](https://github.com/OpenGPTX/AP5/tree/main/opengptx-ontology) ontology is designed by Fraunhofer IAIS to establish a comprehensive and standardized framework for describing Large Langage Models (LLMs) within the Gaia-X infrastructure. It includes classes, properties, and relationships necessary to model LLMs related datasets.
We need the permalink for the ontology for the users to leverage the ontology.

Create permalink for OpenGPT-x ontology

---

vc/render-method/.htaccess

- Use shorter version for the generated context package files.
- May use longer version if/when this links to a spec context.

Update vc-render-method redirect.

---

hereditary/ontology/genomics/.htaccess
hereditary/ontology/phenoclinical/.htaccess

The redirect seems to not work as expected.
1. From https://w3id.org/hereditary/ontology/phenoclinical/ I should be redirected to https://hereditary.dei.unipd.it/ontology/phenoclinical, instead the redirected URL is http://hereditary.dei.unipd.it/ontology/phenoclinical/http://hereditary.dei.unipd.it/ontology/phenoclinical/. 
2. Rewrite rules with schema and resource were missing a backslash. The URL https://w3id.org/hereditary/ontology/phenoclinical/schema wrongly redirected to https://hereditary.dei.unipd.it/ontology/phenoclinicalschema/.
I should have fixed it now.

Modified redirect URL

---

hereditary/ontology/genomics/.htaccess
hereditary/ontology/phenoclinical/.htaccess

There was a problem with the redirect of https://w3id.org/hereditary/ontology/genomics/schema/ not redirecting to the correct URL.

Fixed schema and resource redirect

---

openbadges/.htaccess

This pull request includes a small but important change to the `.htaccess` file in the `openbadges` directory. The change updates the URL for the `v1` context JSON to point to a new location.
* [`openbadges/.htaccess`](diffhunk://#diff-e87c681fdba7000ed4eea740077e4d6fbc688e48bf4c429ce1c1175f81aa46d9L3-R3): Updated the `RewriteRule` for `^v1 to redirect to `https://purl.imsglobal.org/spec/ob/v1p0/context/context.json` instead of `https://openbadgespec.org/v1/context.json`.

Update v1 redirect to point to the correct context JSON URL

---

openbadges/.htaccess

This pull request includes a small change to the `.htaccess` file in the `openbadges` directory. The change adds a new rewrite rule to redirect requests for schema files in version 1 to the appropriate URL.
* [`openbadges/.htaccess`](diffhunk://#diff-e87c681fdba7000ed4eea740077e4d6fbc688e48bf4c429ce1c1175f81aa46d9R4): Added a rewrite rule to redirect requests matching `^v1/schema/(.*) to `https://purl.imsglobal.org/spec/ob/v1p0/schema/$1`.

Add redirect rule for v1 schema in .htaccess

---

dpv/.htaccess

- the examples links e.g. https://w3id.org/dpv/examples#E0029 give a 404 as the rule is set to go to https://w3c.github.io/dpv/examples/#E0066 which results in a 404
- the correct link should go to the 2.0 versioned page as examples are declared in every version even if the files are outside the versioned folders at root level
- so the file https://w3c.github.io/dpv/examples/E0066.ttl is shown as https://w3c.github.io/dpv/2.0/examples#E0066
- the fix is to write rules that go to the actual file for RDF content types and go to the versioned page for HTML content type
- fixes w3c/dpv#200

/dpv fix examples 404 - redirect to version

---

dspace-dcp/.htaccess
dspace-dcp/README.md

This PR adds redirection for [DCP](https://github.com/eclipse-dataspace-dcp/decentralized-claims-protocol) 
It contains redirect for:
- JSON-LD context
- JSON Schemas
- and a fallback to GH pages

feat: redirections for Eclipse Decentralized Claims Protocol project

---

memuk/.htaccess
memuk/README.md

This pull request introduces the "memuk" namespace, a key component of the knowledge graph created for my bachelor’s thesis. The knowledge graph is designed to represent concepts and relationships in the domain of melodic music information, particularly in the context of Music Information Retrieval (MIR) research.
- Created a dedicated namespace for `memuk` to provide access to relevant resources and ontologies.
- Implemented redirects for various paths under `w3id.org/memuk` to point to the corresponding resources hosted on GitHub.
- Example redirects:
- `/resource` → Redirect to the knowledge graph details on GitHub.
- `/ontology/meis` → Redirect to the raw OWL file for the "meis" ontology.
- `/memuk` → General redirect to the GitHub repository for the project.
I would appreciate it if …

Add "memuk" Namespace for Knowledge Graph (Bachelor Thesis)

---

env/.htaccess
env/README.md

Adding a new branch to /env/ for the Australian National Environmental Accounts (NEA) definitions and crosswalks
First crosswalk: ALUMv8 --> IUCN GET
Currently hosted on the ARDC demo service https://demo.vocabs.ardc.edu.au/viewById/1099
When this is proved up, will be moved to ARDC production service.

Add http://w3id.org/env/nea/alum8-get

---

303/.htaccess
303/README.md
x303/.htaccess
x303/README.md

We came to realize that https://w3id.org/303 is not a good solution as it doesn't work well with RDF+XML, in particular qnames do not permit local parts that start with a number.

move from 303 to x303 due to qname issue

---

odre/odre-time/.htaccess
odre/odre-time/readme.md

This new identifier will serve to identify ontologies developed for [ODRE](https://github.com/ODRE-Framework/odre-framework) (an ODRL enforcement mechanism).

W3id for ODRE framework

---

display/.htaccess
display/README.md

add /display path for the Display ontology
https://w3id.org/display# is the namespace URI for the Display ontology terms.
https://ouvroir.github.io/display-ontology/ is the URL of the Display ontology documentation.
https://w3id.org/display redirects to https://ouvroir.github.io/display-ontology/
Ontology maintained by David Valentine at the [Ouvroir Laboratory](https://github.com/ouvroir).
- David Valentine <david.valentine@umontreal.ca>
- Zoë Renaudie <zoe.renaudie@umontreal.ca>
- Emmanuel Château-Dutier <emmanuel.chateau.dutier@umontreal.ca>

add /display path for the Display ontology

---

catenax/.htaccess
catenax/README.md

- documents the catena-x namespace releases
- links to the new markdown documentation base (without github pages)
- introduces rewrite rules for intermediate versions and links current and next version to the right tags.
- tested on a local installation of w3id.org

feature: setup up to Catena-X 2412

---

opengpt-x/.htaccess

The permalink for https://w3id.org/opengptx is not working. To update this, the .htaccess file has been updated. Please merge the pull request.

Update .htaccess file for "opengpt-x" 

---

dspace-dcp/.htaccess

Changes the context URI to be  in format
`https://w3id.org/dspace-dcp/<version>/dcp.jsonld`
according to https://github.com/eclipse-dataspace-dcp/decentralized-claims-protocol/discussions/128
The json schema redirects are not affected

chore: renames dcp context

---

CMECS/.htaccess

Changed rewrite rule to redirect to CMECS on Bioportal site but am not sure this will work. 
I am hoping that the redirect will resolve to the individual Class pages via the IRIs, e.g., https://bioportal.bioontology.org/ontologies/CMECS/?p=classes&conceptid=https://w3id.org/CMECS/CMECS_00000395 resolves to the Gravelly Mixes Class page.
However, testing the rule in an [htaccess tester](https://htaccess.madewithlove.com?share=3c8fdaa3-5d98-499f-a1dd-c07c528b8f7e) the generated link only resolves to the main CMECS ontology summary page https://bioportal.bioontology.org/ontologies/CMECS
Should I ask about this on the public-perma-id@w3.org mailing list?

Update .htaccess to Bioportal

---

dspace-dcp/.htaccess

This PR makes the dspace-dcp links point to the correct locations in the github-pages deployment on https://eclipse-dataspace-dcp.github.io/decentralized-claims-protocol/
Check the rules here:
[https://htaccess.madewithlove.com?share=b22a62ff-8449-4e3f-8e6f-caf537bdaaf3](https://htaccess.madewithlove.com/?share=b22a62ff-8449-4e3f-8e6f-caf537bdaaf3)
cc @wolf4ood

fix(dspace-dcp): hard-redirect versions

---

rml/.htaccess

RML Resources contains the full shape and ontology. If the user asks for the shape or ontology of a specific RML module, prioritize this

rml: shapes LV and Star have priority over resources

---

dseco/.htaccess

Please note that the dseco project (https://github.com/Orange-OpenSource/dseco) is work in progress, hence some redirection tests might fail right now (notably for the https://w3id.org/dseco/doc/ link).

Added dseco rules (access to documentation and ontology files)

---

dspace/.htaccess
dspace/README.md

This changes the redirects:
- version 0.8 and before redirect to the IDSA's github pages deployment for the ids-specifications repo
- version 2024-1 as well
- version 2025-1 redirects to the github pages deployed by the EDWG.

feat(dspace): separate redirects to IDSA and EDWG depending on version

---

crmrp/.htaccess
crmrp/README.MD

Please consider to merge this PR adding content negotiation for https://w3id.org/crmrp uris .
Persistent URIs related to the CRMro Ontology, an ontology to support the digital documentation of the conservation and restoration practice. 
TThis work has been partially supported by Fondazione Cariplo in the framework of the project IncrASTible! The incredible Monastery of Astino Call Per la Cultura 2020, Rif. 2020-3879, June 2022 - June 2024 and is driven by Italian National Research Council - [Istituto di matematica applicata e tecnologie informatiche "Enrico Magenes" (IMATI)](https://imati.cnr.it/)
===================
We have created:
+  `https://w3id.org/crmrp` for actual ontology serialized in different syntaxes.
Contacts:
+ Chiara Eva Catalano (CNR-IMATI): github …

adding crmrp conf

---

ctp/.htaccess

Please consider merging this pull. It fixes a typo (https://w3id.org/https://w3id.org/ctp/nfc should be https://w3id.org/ctp/ncf).
Thanks, 
Riccardo

fixing typo nfc --> ncf

---

AlmesCore/.htaccess
AlmesCore/json/.htaccess

- Redirected deprecated terms (`data`, `metadataId`) to https://almescore.github.io/Almes-Core/deprecatedElements.html
- Updated active term redirects to match the latest GitHub Pages structure
- Ensured no broken links

Updated W3ID redirects for AlmesCore schema

---

spec-ontology/.htaccess
spec-ontology/README.md

Creating persistant URI's for the Specifications Ontology: https://docs.crow.nl/spec-ontology/

Adding the spec-ontology to w3id.org.

---

spec-ontology/.htaccess

My apologies, the rewrite rule did not escape the `#` character

Fixed: rewrite rule for escaping `#`

---

gerps/README.md
gerps/ontology/process/.htaccess
gerps/ontology/software/.htaccess

Update redirect targets for datafield and process ontologies; also enable version in the redirects using regex. Add software ontology redirect too (currently pointing at 404)

Update gerps/ontology redirects 

---

arp/.htaccess
arp/README.md

Adds support for dynamic domains for demo environments, eg:
```
https://w3id.org/arp/arpdemo.orgx/schema/my-schema-id
https://w3id.org/arp/arpdemo.orgx/ro-id/hdl:21.15109/ARP/C27YUE/file/512862
https://w3id.org/arp/arpdemo.orgx/ro-id/hdl:21.15109/title/1234
https://w3id.org/arp/arpdemo.orgx/ro-id/hdl:21.15109/unique-element
```

Add support for dynamic domains for use in demo environments

---

dspace/.htaccess
dspace/README.md

As the DSP will get versioned releases on github pages, this PR changes the redirect to the `HEAD` deployment for the upcoming RCs. This will change once there is a stable release. Then, the `2025/1` URIs will be redirected to the pinned version.
cc @ssteinbuss

chore(dspace): redirect to HEAD until release in Q3/2025

---

my-ontology/.htaccess

I would like to request a permanent URI for my ontology.
The new URI: https://w3id.org/my-ontology
It redirects to: https://umi0529.github.io/my-ontology/
The `.htaccess` file has been added to handle content negotiation, allowing different formats to be accessed.
Thank you for your time and consideration!

Request for permanent URI: https://w3id.org/my-ontology

---

bess/.htaccess
bess/README.md

Dear maintainer,
Could you please create a permanent identifier for the bess ontology?
I hope I provided you with the correct documents via this way.
Currently this project is under development so the redirect just goes to the github page. I will update the .htaccess file when the project is more stable and I have the HTTP + ttl representations backed off a triple store.
Project: Built Environment Scanning System Ontology
Prefix: bess
Namespace: https://w3id.org/bess
Best, Nat
[nathaniel@xri.online](mailto:nathaniel@xri.online)

Create a permanent identifier for the bess ontology

---

battery-data-alliance/.htaccess
battery-data-alliance/README.md

This PR creates the battery-data-alliance PURL namespace.
The namespace is maintained by the [Battery Data Alliance](https://lfenergy.org/projects/battery-data-alliance/) (BDA), a Linux Foundation Energy project. Its purpose is to enable persistent identifiers for application ontologies and other Semantic Web resources linked to BDA projects.
The .htaccess file has been tested using [https://htaccess.madewithlove.com/](https://htaccess.madewithlove.com/)
Maintainers:
- [Gabe Hege](https://github.com/pghege) – NVIDIA, AmpLabs  
- [Simon Clark](https://github.com/jsimonclark) – SINTEF

Create .htaccess for battery-data-alliance

---

moneygraph/.htaccess
moneygraph/README.md

https://w3id.org/moneygraph

---

gerps/ontology/datafield/.htaccess
gerps/ontology/process/.htaccess
gerps/ontology/software/.htaccess

Sorry for creating a pull request again so soon. With our last commit I broke a case which I had not tested properly, which is now being addressed: 
- eg w3id.org/gerps/ontology/process/1.0/ should redirect to localhost/gerps/ontology/process/1.0/, but is redirecting to https://fusion-jena.github.io/GerPS-Process/index-de.html#1.0/ right now

GerPS Ontologies: fix version redirects

---

gfo-light/.htaccess
gfo-light/README.md

This PR contains some minor modifications to the gfo-light configurations. Ontology artefacts now reside in a sub directory.

Update gfo-light redirects

---

security/.htaccess

> [!IMPORTANT]
> Wait to merge until VC side is ready.
- See https://github.com/w3c/verifiable-credentials/issues/61.
- https://w3id.org/security/data-integrity/v2
- https://www.w3.org/2025/credentials/vcdi/context/v2.jsonld
- https://w3id.org/security# (with content negotiation)
- https://www.w3.org/2025/credentials/vcdi/vocab/v2/vocabulary.html
- https://www.w3.org/2025/credentials/vcdi/vocab/v2/vocabulary.jsonld
- https://www.w3.org/2025/credentials/vcdi/vocab/v2/vocabulary.ttl
- https://www.w3.org/2025/credentials/vcdi/vocab/v2/vocabulary.svg
- https://w3id.org/security/multikey/v1
- https://www.w3.org/2025/credentials/vcdi/multikey/context/v1.jsonld
- https://w3id.org/security/jwk/v1
- https://www.w3.org/2025/credentials/vcdi/jwk/context/v1.jsonld
@iherman please review.

Update for final VC 2.0 URLs.

---

gfo-core/.htaccess
gfo-light/.htaccess

A trailing slash after a release tag is now properly handled

Update rewrite rules of gfo-core and gfo-light for release handling

---

g17/.htaccess

Not sure if that works: redirection with location hash handling:
```RewriteRule ^ontology[/#](.+)$ https://dhi-roma.github.io/g17-ontology/docs/widoco/doc/index.html#$1  [R=303,L,NE]```
Do you have any idea?

new rewrite rule with location.hash

---

rdf-tensor/.htaccess
rdf-tensor/README.md

I'm requesting to register the `rdf-tensor` prefix for an extension of RDF and SPARQL to process multi-dimensional arrays of numerical data (data tensors).
Website: https://rdf-tensor.github.io/jena-datatensor/
I am a co-owner of the original repository: https://github.com/RDF-tensor/jena-datatensor
The other owner is Piotr Marciniak (@cinekele).
The README file includes test links and maintainer information. I tested the .htaccess configuration on a local Apache Server instance and everything seems to work fine.

Add rdf-tensor

---

evr/.htaccess
evr/README.md

This [W3ID](https://w3id.org) provides persistent URLs for entities and artifacts in the [Event Venue Registry (EVR)](https://github.com/event-venue-registry/evr), a database and ontology cataloging and characterizing physical venues at which events (such as conferences) can take place.
This PR adds a configuration under the `evr` namespace for redirecting identifiers in this database and for resolving ontology artifacts generated from this database.

Add `evr` namespace for the Event Venue Registry

---

WEHI-RCP/.htaccess

Sorry, my last PR was incorrect. I intended to support `https://w3id.org/WEHI-RCP/<ANYTHING>` to redirect to `https://wehi-researchcomputing.github.io/<ANYTHING>`. Let me know if this rule is incorrect.

Fix for WEHI-RCP

---

standards/.htaccess
standards/README.md

New proposed w3id space "standards" for the IEC/ISO SMART project and other resources used by CEN, CENELEC, IEC and ISO Standards Developing Organizations.

New proposed w3id space "standards" for the IEC/ISO SMART

---

orbac.owl/.htaccess
orbac.owl/README.md

This PR adds a redirect from https://w3id.org/orbac.owl to an ontology hosted on GitHub.

Add redirect for orbac.owl

---

fip/.htaccess
fip/README.md

We are migrating FIP Wizard from https://fip-wizard.ds-wizard.org/wizard/ to https://fip.fair-wizard.com/wizard/ ([FAIR Wizard](https://fair-wizard.com) cloud solution). Contact information has been also updated.

Update FIP Wizard redirect

---

ssv/.htaccess

This PR updates /ssv/ to correctly redirect to the Signature Sound Vienna project's custom Platform for Reviewing and Interacting with Music Annotation Linked-data (Primal) viewer when text/html is requested. It also updates redirects when application/json and applicaton/ld+json is requested, and politely declines (406) when other content-types are requested.

SSV: Use custom viewer for HTML requests

---

projects/soil-dsi-bridge/.htaccess
soil-dsi-bridge/.htaccess
soil-dsi-bridge/README.md

This pull request adds a redirect for https://w3id.org/projects/soil-dsi-bridge
pointing to https://guapi-d.github.io/soil-dsi-bridge/soil-dsi-bridge.ttl

Add redirect for soil-dsi-bridge ontology

---

elita/.htaccess
elita/README.md

This PR adds a redirection for https://w3id.org/elita to the ELITA ontology hosted at:
https://github.com/elianadipalma/ELIta/blob/main/Ontology/elita.ttl
Includes:
- .htaccess for redirect
- README.md with maintainer information
Maintainer: Eliana Di Palma – eliana.dipalma [at] unito [dot] it

Add persistent identifier for elita ontology

---

healthdata/.htaccess
healthdata/README.md

This PR adds a new folder for the `/healthdata` namespace.
- Redirects were tested using [htaccess.madewithlove.com](https://htaccess.madewithlove.com/)
- The [README file](https://github.com/Health-RI/health-ri-metadata/blob/develop/README.md#health-ri) explains the connection between `healthdata` and Health-RI
- The same README lists the responsible maintainers with links to their GitHub profiles
Thanks!

Add /healthdata namespace

---

elmo/.htaccess

Had to add /elmo back to the first rewrite rule. Desired redirect for:
https://w3id.org/elmo/elmo_3620020
is
https://timalamenciak.github.io/elmo/elmo.html#elmo_3620020

Update .htaccess to properly process CURIEs

---

healthdata/.htaccess

This PR updates the .htaccess file in the /healthdata folder to ensure all subpaths (e.g., /healthdata/metadata) correctly redirect to the corresponding /health-ri/* paths.

Fix redirect for /healthdata/* paths

---

iprok/.htaccess
iprok/readme.md

Hi w3id.org maintainers,
This pull request adds the necessary files to configure a persistent URL (PURL) for the Iprok ontology.
**PURL:** `https://w3id.org/iprok/`
**Changes include:**
* Creation of the `/iprok/` directory.
* An `.htaccess` file within `/iprok/` to handle content negotiation and redirect to the ontology files and HTML documentation.
* A `README.md` file in `/iprok/` explaining the PURL setup and linking to the resources.
**The primary HTML documentation for the Iprok ontology is hosted at:**
https://konevenkatesh.github.io/IprokDoc/main.html
**The ontology source files are in the repository:**
https://github.com/konevenkatesh/IprokDoc/
Please let me know if any changes are required.
Thank you!

Add Iprok ontology to w3id.org

---

onfood/ontology/.htaccess
onfoods/ontology/.htaccess
onfoods/ontology/README.md

This PR registers a new persistent identifier for the Onfood ontology.
- Persistent IRI: https://w3id.org/onfood/ontology
- Redirects to: https://gitlab.inf.unibz.it/dbs/onfood-ontology/-/raw/main/onfood_ontology.owl
The goal is to make the ontology findable and citable in research papers and by the wider semantic web community.
Maryam Mozaffari
maryam.mozaffari@unibz.it
Thank you for your support!

Create .htaccess (Add persistent identifier for Onfoods Ontology)

---

ontouml-models/.htaccess

This PR adds a new redirect rule under the `/ontouml-models/` path to point to the OntoUML dashboard service hosted at:
```
https://ontouml-dashboard-995390128580.herokuapp.com/
```
The following redirection was added to `.htaccess`:
```
RedirectMatch 302 ^/ontouml-models/dash(board)?(/?)$ https://ontouml-dashboard-995390128580.herokuapp.com/
```
This supports both `/dash` and `/dashboard` variants for flexibility.

Add redirect for OntoUML dashboard

---

cfc/.htaccess
cfc/Readme.md

This pull request registers the path `/cfc` for the Circular Future Cities Ontology (CFC), developed as part of the Future Cities Laboratory – Circular Future Cities Project.
- Ontology: https://raw.githubusercontent.com/DigiConstructLab-TU-Delft/CircularFutureCitiesOntology/main/ontology/cfc.owl
- Documentation: https://raw.githubusercontent.com/DigiConstructLab-TU-Delft/CircularFutureCitiesOntology/main/docs/index.md
- Examples: TTL files under `/examples/`
- Imports: TTL/OWL files under `/ontology/imports/ontology/imports/`
Maintainer: Ranjith Kuttantharappel Soman  
Email: r.soman@tudelft.nl
Thank you for providing the W3ID infrastructure.

Add W3ID redirects for Circular Future Cities Ontology

---

NLM/.htaccess
NLM/README.md

Added a redirect mechanism for the National Library of Medicine (NLM) Classification. It uses an odd construction that is difficult to reference. For example, a code like "QS 642" has the equivalent link "https://classification.nlm.nih.gov/schedules/QS#QS 642", with the "QS" portion duplicated.

Built out and tested NLM Classification redirects.

---

laderr/.htaccess

Added a specific redirect rule in the .htaccess file to map `/laderr/engine/edoc_examples` to the corresponding GitHub folder containing EDOC example scenarios.

chore(routing): add redirect for EDOC example scenarios in LaDeRR Engine

---

certi/.htaccess
certi/README.md

This commit introduces the .htaccess file for the new 'certi' identifier.
It establishes the following redirection rules:
- The root path (/) redirects to https://www.certi.world.
- The path /v1 redirects to the specific context file at .../v1/schema/context.json.
- All other paths are redirected to https://api.certi.world/jsonld/$1.
Necessary CORS headers are also included.

feat(certi): Add initial redirection rules for certi project

---

catenax/.htaccess
catenax/README.md

this PR adds rules linking to the json schemas representing the ODRL constraints for the Catena-X Saturn release.
cc @hfocken

feat(catenax): link to updated odrl constraint schemas

---

contentdesc/.htaccess
contentdesc/readme.md

This is an update of the urls used in this ontology. We have migrated the documentation to the following domain: reliance.expertcustomers.ai. We have also changed the maintainers of this ontology.

Updated domain and people in charge of the ontology

---

RoboAlchemyVaV/.htaccess
RoboAlchemyVaV/README.md

This pull request registers the permanent IRI:
https://w3id.org/RoboAlchemyVaV
It redirects to the OWL ontology file hosted at:
https://chris-bishop8.github.io/RoboAlchemyVaV/RoboAlchemyVaV.owx
The folder includes:
- `.htaccess` file for content negotiation (RDF/XML and HTML)
- `README.md` with maintainer info
This ontology is under development and focuses on V&V for robotic systems.

Add redirect for RoboAlchemyVaV ontology

---

odrl-fs/.htaccess
odrl-fs/README.md

Add namespace `odrl-fs` to redirect to the ontology definition of the ODRL Formal Semantics. 
Relates to this Pull Request in the ODRL repository: https://github.com/w3c/odrl/pull/130

feat: add namespace redirection for ODRL Formal Semantics Ontology definition

---

catenax/.htaccess

As the schemas atomic-constraint-schemas.json, context-schema.json and policy-schema.json are in the root , this needs to be covered by a separate redirect rule

added redirect for overarching schemas

---

qualo/.htaccess
qualo/README.md

This pull request adds a namespace for the Qualification Ontology, an ontology of qualifications, distinctions, and certifications that uses the Phenotype And Trait Ontology term quality (PATO:0000001) as a root term.
It's available under the CC0 license at https://github.com/cthoyt/qualo
It includes an .htaccess file that enables redirecting to the website with the ontology terms at https://cthoyt.github.io/qualo/ as well as the ontology artifacts saved on GitHub

Add namespace `qualo` for the Qualification Ontology

---

golem/.htaccess
golem/README.md

Dear support,
This pull request adds a permanent redirect for the GOLEM ontology, a project developed within the Digital Humanities field to support the ontological modeling of narrative and fiction through Semantic Web technologies.
Thanks for your support,
Luca

Add permanent redirect for GOLEM ontology

---

SCIMOnto-ontologies/CFMO.owl/.htaccess
SCIMOnto-ontologies/ECMO.owl/.htaccess
SCIMOnto-ontologies/EvMO.owl/.htaccess
SCIMOnto-ontologies/IMO.owl/.htaccess
SCIMOnto-ontologies/README.md
SCIMOnto-ontologies/SCIMOnto.owl/.htaccess
SCIMOnto-ontologies/SMO.owl/.htaccess

This pull request adds new persistent identifier entries for the SCIMOF Ontology Suite under '/SCIMOnto-ontologies/'.
The following redirects are included:
https://w3id.org/SClMOnto-ontologies/CFMO.owl → https://zhu-huiwen.github.io/scimonto-ontology/CFMO.owl
https://w3id.org/SClMOnto-ontologies/ECMO.owl → https://zhu-huiwen.github.io/scimonto-ontology/ECMO.owl
https://w3id.org/SClMOnto-ontologies/EvMO.owl → https://zhu-huiwen.github.io/scimonto-ontology/EvMO.owl
https://w3id.org/SClMOnto-ontologies/IMO.owl → https://zhu-huiwen.github.io/scimonto-ontology/IMO.owl
https://w3id.org/SClMOnto-ontologies/SMO.owl → https://zhu-huiwen.github.io/scimonto-ontology/SMO.owl
https://w3id.org/SClMOnto-ontologies/SCIMOnto.owl → https://zhu-huiwen.github.io/scimonto-ontology/SCIMOnto.owl
Each entry …

Add redirects for SCIMOF ontology suite

---

GayCities/.htaccess
GayCities/README.md

I was trying to add a specific URL and noticed that there was a special character I hadn't prepared for. The URL was "https://warsaw.gaycities.com/bars/308665-pogłos" and the character was "ł". On lgbtDB, the URL is represented in the entity here: https://lgbtdb.wikibase.cloud/wiki/Item:Q86607, so you can see that it currently is not functioning.
I added this to the character to the appropriate line, tested the new regex using htaccess, and documented the change in the README.

Modified to be able to match a special character found in a specific special character found in a GayCities URL

---

grndstt/.htaccess
grndstt/README.md

This pull request adds a namespace for `grndstt`, for now a github website holding the ISDB (In Silico Database) ressources.
It's available under the CC-BY-SA license at https://oolonek.github.io/ISDB/

Adds the `grndstt` namespace

---

emi/.htaccess
emi/README.md

This permanent w3id is meant to share vocabularies and ontologies related to the Earth Metabolome Initiative.
https://w3id.org/emi redirects to https://www.earthmetabolome.org/earth_metabolome_ontology/
- Pierre-Marie Allard (pierre-marie.allard@unifr.ch)
- Emmanuel Defossez (emmanuel.defossez@unine.ch)
- Tarcisio Mendes de Farias (tarcisio.mendes@sib.swiss)
- Earth Metabolome Initiative data stewardship team (data@earthmetabolome.org)

establishing the `emi` namespace

---

salemWitchTrials/.htaccess
salemWitchTrials/README.md

This Pull Request adds a new permanent identifier redirect for the salemWitchTrials project under the salem-witCHes organization.
Changes included:
- Created a new directory salemWitchTrials/ to hold the redirect rules.
- Added an .htaccess file with a permanent redirect from https://w3id.org/salemWitchTrials to the project’s official GitHub repository:
https://github.com/salem-witCHes/salemWitchTrials/
- Added a README.md file containing contact and project information.
Redirect details:
- Source URL: https://w3id.org/salemWitchTrials
- Target URL: https://github.com/salem-witCHes/salemWitchTrials/
- HTTP status code: 301 (Permanent Redirect)

Add w3id redirect for salemWitchTrials project

---

objectcore/.htaccess
objectcore/README.md

Added README.md  and .htaccess redirecting from https://w3id.org/objectcore/<ANYTHING> to https://n4o-rse.github.io/OCMDP/<ANYTHING>

initialization of objectcore redirect

---

comptox/.htaccess
comptox/README.md

create new namespace to host chemicals as identified and described by EPA's CompTox dashboard

created \comptox namespace

---

rdf-tensor/.htaccess
rdf-tensor/README.md

Adds support for content negotiation and explicit URLs for JSON-LD and RDF/XML. Follow-up of: https://github.com/RDF-tensor/jena-datatensor/pull/8
Tested on a local Apache instance, it works.

rdf-tensor: add ontology files in RDF/XML, JSON-LD

---

dongshin.seo/.htaccess
dongshin.seo/README.md

This pull request adds a new persistent identifier for https://w3id.org/dongshin.seo/.
The identifier redirects permanently (HTTP 301) to the personal webpage of Dongshin Seo at:
→ https://dh.aks.ac.kr/~dongshin/
The `.htaccess` file uses Apache rewrite rules to handle:
- Base path redirection:
→ https://w3id.org/dongshin.seo/ → https://dh.aks.ac.kr/~dongshin/
- Subpath redirection:
→ https://w3id.org/dongshin.seo/something → https://dh.aks.ac.kr/~dongshin/something
This w3id is maintained by:
Dongshin SEO  
📧 oriental.neo@gmail.com  
🐙 GitHub: @dongshins
All files are placed under the `dongshin.seo/` directory, following w3id.org conventions.

Add new w3id for dongshin.seo

---

ssv/.htaccess

Redirects visits to <https://w3id.org/ssv> or <https://w3id.org/ssv/> to the Signature Sound Vienna GitHub organization at <https://www.github.com/Signature-Sound-Vienna/>

`ssv`: Redirect visits to namespace URI to SSV GitHub organization

---

worldstatesmen/.htaccess
worldstatesmen/README.md

Added rewrite rules. Unfortunately, seemingly at random, a small number of pages end in ".htm" instead of ".html". I documented all of those in separate rewrite rules that trigger first; this required investigating the page here (https://www.worldstatesmen.org/CONTENTS.html) and finding all links ending with ".htm". Tested and ready for action!

Adding rewrite rules for worldstatesmen.org.

---

gnss-dcat-ap/.htaccess
gnss-dcat-ap/README.md

Add Persistent identifier (/gnss-dcat-ap) for the latest version of the GNSS-DCAT-AP Controlled vocabulary.

GNSS-DCAT-AP

---

archlink/branches/.htaccess

https://w3id.org/archlink/branches/ redirects to https://w3id.org/archlink/terms/conservationthesaurus
This allows the publication of seperate branches of our vocabulary with own Concept Scheme URIs, while still leading to the base thesaurus URI.

https://w3id.org/archlink/branches/ redirection

---

health-ri/.htaccess

refactor(routing): fix, simplify, and improve ontology file redirections in .htaccess
- Replaced RewriteRule-based redirections with RedirectMatch for clarity and maintainability
- Updated latest ontology file redirects (ttl, vpp, json, doc, spec)
- Added clean support for versioned ontology files using semantic version capture (vX.Y.Z)
- Changed doc/spec redirects to use GitHub Pages for proper HTML rendering
- Removed obsolete RewriteRule-based versioned redirect logic

Fix, simplify, and improve ontology file redirections in health-ri's .htaccess

---

hmontology/.htaccess
hmontology/README.md

This PR registers a permanent IRI namespace for the HM-Ontology under:
`https://w3id.org/hydromet/hm-ontology/`
The HM-Ontology is a lightweight, domain-specific ontology developed to describe hydrological concepts, variables, and relationships in a semantically consistent and machine-readable way. It supports the FAIR principles for hydrological data by enabling semantic annotation, RDF transformation, and integration into knowledge graphs.
This ontology is developed as part of the NFDI4Earth project, focusing on transforming conventional hydrology datasets (e.g., CSV) into semantically enriched RDF knowledge graphs, allowing better interoperability, SPARQL querying, and integration with other datasets using Semantic Web technologies.
It:
- Links to existing vocabularies (e.g., SOSA, …

Add permanent identifier for HM-Ontology (hydromet/hm-ontology)

---

hmontology/.htaccess

This PR updates the `.htaccess` for the `hmontology` namespace to ensure that individual ontology term IRIs (e.g., `https://w3id.org/hmontology/hasDominantGeologicalClass`) redirect correctly to their corresponding term pages in the current hosting location.
- Added rewrite rules to handle subpaths and redirect them either to:
- The matching term page (`/<term>/`) on the backend site, or
- A section (`#<term>`) of the main ontology HTML page, depending on hosting structure.
- Preserved existing content negotiation and 303 redirects for the ontology root.
Previously, only the base namespace (`https://w3id.org/hmontology/`) redirected to the ontology’s main HTML page or RDF serializations.  
Requests to term IRIs did not resolve as intended, impacting linked data usability.
Maintainer: …

Enhance hmontology namespace to redirect individual ontology terms

---

foodhkg/.htaccess
foodhkg/README.md

This pull request introduces initial setup and documentation for the Food Health Claims Knowledge Graph (foodhkg) project. It adds a redirect rule to the project and provides a README with a project overview and contact information.
* Added a `README.md` file in the `foodhkg` directory describing the FoodKG project, its purpose, and contact details.
* Created a `.htaccess` file in the `foodhkg` directory to redirect visitors to the project's GitHub Pages site.

Add redirect to foodhkg

---

emi/.htaccess

ols changed to ols.ttl. helps in recognition of content type. See also here for context: https://github.com/EBISPOT/ols4/issues/814

changed ols redirection for handling error at ebispot/ols4

---

cerif2/.htaccess
cerif2/README.md

For an updated version of CERIF, the Common European Research Information Format, we need a new prefix: `cerif2`.
We’ve got a very basic website running at https://cerif2.eu/ where we suggest the forwarding leads.

Add w3id.org/cerif2

---

health-ri/.htaccess

refactor(.htaccess): remove content negotiation, simplify ontology redirects, and add mappings redirects
- dropped RewriteEngine and all content negotiation logic for /ontology
- unified latest ontology redirect with optional /ttl segment
- simplified versioned ontology redirects (ttl, vpp, json)
- removed redundant default TTL redirect
- added new redirects for SSSOM mappings (ttl, tsv)

refactor(.htaccess): remove content negotiation, simplify ontology redirects, and add mappings redirects

---

health-ri/.htaccess

* Add latest TTL redirect: `/health-ri/mapping-vocabulary[/ttl]` → `vocabulary/latest/health-ri-vocabulary.ttl`
* Add latest spec redirect: `/health-ri/mapping-vocabulary/(spec|specification)` → site `method/specification.html`
* Add versioned TTL redirect: `/health-ri/mapping-vocabulary/vX.Y.Z[/ttl]` → `vocabulary/versioned/health-ri-vocabulary-v$1.ttl`
* Add versioned spec redirect: `/health-ri/mapping-vocabulary/vX.Y.Z/(spec|specification)` → `vocabulary/versioned/documentations/specification-v$1.html`

feat(w3id): add redirects for Health-RI Mapping Vocabulary (latest & versioned)

---

PrOM/.htaccess
PrOM/README.md

This pull request adds the 'PrOM' folder under the 'perma-id' namespace in the w3id.org repository. 
The folder includes:
- README.md with basic information and contact details
- .htaccess file for URL redirection
Purpose:  
To enable permanent, resolvable URLs for the PrOM project as part of w3id.org. 
No existing content was modified; this is an addition only.
Please review and merge if everything is in order.

PrOM folder addition

---

dspace/.htaccess
dspace/README.md

The release of Dataspace Protocol 2025-1 is finalized. The final PR executing on the decision to release is pending [1]. This one should be reviewed and merged soon afterwards.
Closes [2]
[1] https://github.com/eclipse-dataspace-protocol-base/DataspaceProtocol/pull/223
[2] https://github.com/eclipse-dataspace-protocol-base/DataspaceProtocol/issues/197

chore(dspace): redirect 2025-1 to now published release 2025-1

---

catenax/.htaccess

As we limited the allowed scope of odrl in this file https://github.com/catenax-eV/cx-odrl-profile/blob/main/schema/context/odrl.jsonld and thus need to reference this one in the constraints in CX-0152. 
New rule and sequence was tested in https://htaccess.madewithlove.com/ . Please remove in the "url that you are applying the rules to" /catenax if you test.

Redirect to catena-X odrl.jsonld

---

gaidet/.htaccess
gaidet/README.md

**Maintainers:**
- Serhii Nazarovets (@panbibliotekar) – serhii.nazarovets@gmail.com
**Purpose:**
GAIDeT (Generative AI Delegation Taxonomy) is a taxonomy and ontology that enables transparent disclosure of which research and writing tasks are delegated to generative AI tools.  
It complements CRediT (Contributor Roles Taxonomy) and CRO (Contributor Role Ontology) by adding structured, machine-readable roles for AI involvement.
**Redirects:**
- https://w3id.org/gaidet/ → https://panbibliotekar.github.io/gaidet-declaration/
- https://w3id.org/gaidet/gaidet.owl → OWL ontology in the GitHub repository
- https://w3id.org/gaidet/terms.yml → YAML source file for the taxonomy
**License:**
MIT License © 2025 Yana Suchikova, Natalia Tsybuliak, Jaime A. Teixeira da Silva, Serhii Nazarovets

Add permanent prefix for GAIDeT

---

core-activity-ontology/.htaccess
core-activity-ontology/README.md

The Core Activity Ontology was created in the Activity Knowledge management project and is hosted on https://github.com/activity-knowledge-project/CAO/blob/main/v1/core_activity_ontology.ttl
The link for its URL is activity-knowledge-project.github.io

Adding Core Activity Ontology

---

tractusx-trust/.htaccess

stupid mistake - sorry
It's referenced to here:
https://github.com/eclipse-edc/Connector/blob/d831c31e9e14ab72807b5a045f4c7ad7816aab2e/spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/iam/identitytrust/spi/DcpConstants.java#L22

fix(tractusx-trust): path

---

health-ri/.htaccess

- change ontology redirect from `specification.html` → `specification-ontology.html`
- change mapping vocabulary redirect from `specification.html` → `specification-vocabulary.html`
Ensures external users are redirected to the correct renamed spec files.

fix(routing): update .htaccess redirects to new spec filenames

---

CoSMO/.htaccess
CoSMO/README.md

This PR adds a new folder CoSMO with a .htaccess file
to provide permanent URLs for the CoSMO ontology:
- https://w3id.org/CoSMO/ontology → CoSMO.owl
- https://w3id.org/CoSMO/ontology.ttl → CoSMO.ttl
- https://w3id.org/CoSMO/doc → documentation (GitHub Pages)

Add CoSMO ontology redirects

---

Ontocrime/.htaccess
Ontocrime/README.md

This pull request adds a new persistent namespace for OntoCrime.
OntoCrime is an ontology for modeling and publishing crime-related data as Linked Data.
The namespace will provide stable and persistent URIs for crime datasets and knowledge graph projects.
Changes included:
- Created the /ontocrime/ directory.
- Added .htaccess with content negotiation for RDF/XML (and optional TTL, JSON-LD).
- Added README.md describing the namespace and maintainers.
Maintainer:
- Francisco Carrillo (fcarrillob2022@cic.ipn.mx)
GitHub: https://github.com/fcarrillo-brenes
Please review and let me know if further adjustments are needed.

Add OntoCrime namespace

---

dggrs/.htaccess
dggrs/README.md
dggrs/implement/.htaccess
dggrs/system/.htaccess

This DGGRS registry is meant to support development in the [GeoPlegma](https://github.com/GeoPlegma) project. But more widely to become a web-based reference for DGGS development.
The DGGRS registry is also related to the [CRS ontology](https://opengeospatial.github.io/ontology-crs/) in development within the OGC.

Assets for DGGRS registry

---

pods/complete_03/.htaccess
pods/complete_03/README.md

This PR adds a temporary redirect for the PODS 03 ontology to the corresponding file hosted on GitHub.

Add redirect for PODS 03 ontology

---

OntoEvents/.htaccess
OntoEvents/README.md

Hi,
I would like to register the permanent identifier w3id.org/OntoEvents for my ontology OntoEvents.
Repository: https://github.com/fcarrillo-brenes/OntoEvents
Ontology file: eventsv2.rdf
Purpose: OntoEvents is an ontology for representing events, their participants, temporal information, and contextual data extracted from textual sources such as social media posts and news articles.
Maintainer: Francisco Carrillo-Brenes (@fcarrillo-brenes)
This PR adds the folder OntoEvents/ with an .htaccess file to redirect to the ontology in GitHub with content negotiation.
Thanks!

Add ID for OntoEvents ontology

---

stapi/.htaccess
stapi/README.md

Hi
I would like to add the ontology we created for the [SensorThings API](https://www.ogc.org/standards/sensorthings/).
Kind regards
Ruben

SensorThings API Ontology

---

solid-crdt-sync/.htaccess
solid-crdt-sync/README.md

This PR updates the permanent identifiers for the Solid CRDT Sync framework to redirect to the new Locorda domain:
- https://w3id.org/solid-crdt-sync/vocab/ - Now redirects to locorda.dev/vocab/
- https://w3id.org/solid-crdt-sync/mappings/ - Now redirects to locorda.dev/mappings/
- Updated .htaccess redirect rules from `kkalass.github.io/solid_crdt_sync/` to `locorda.dev`
- Updated project references to "Locorda Sync (formerly Solid CRDT Sync)"
- Maintained existing w3id.org namespace for backward compatibility
The Solid CRDT Sync framework has evolved into Locorda, a more general synchronization framework that supports not only Solid Pods but potentially other passive data stores. The framework continues to use CRDT (Conflict-free Replicated Data Types) for local-first, interoperable …

Update solid-crdt-sync redirects to point to locorda.dev
